### ISSUE TITLE
Check all `berkeley-db` linked dependents are AGPLv3-compatible

### ISSUE THREAD

**Issue by cho-m** [Homebrew/homebrew-core#100796]
`berkeley-db` had switched license from Sleepycat to AGPL-3.0-only in v6 (we are on v18). This has some restrictions on dependents that link to `libdb` such as requiring a compatible license. One example is that GPLv2 is incompatible (See https://www.gnu.org/licenses/license-list.en.html#AGPLv3.0).

Most Linux repositories had intentionally kept `libdb`/`db` package at v5 to avoid (re-)licensing issues (https://repology.org/project/db/versions) e.g.
- Arch https://archlinux.org/packages/core/x86_64/db/ 
  - Ref: https://lists.archlinux.org/pipermail/arch-dev-public/2013-August/025307.html
- Debian https://packages.debian.org/sid/source/db5.3 
  - Ref: https://lists.debian.org/debian-legal/2013/07/msg00000.html
- Fedora https://src.fedoraproject.org/rpms/libdb/tree/rawhide
  - Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1361971

I think we should make sure dependents are compatibly licensed, or modify them to meet license terms (e.g. downgrade to existing `berkeley-db@4` or a new `berkeley-db@5`, switch to another alternative, drop dependency, relicense, etc):
- [x] `bogofilter` - #158470
- [x] `gnu-cobol` - GPL 3+
- [x] `libpinyin` - GPL 3+
- [x] `apt` -- #158468
- [x] `dbxml` -- no issue as also AGPL-3.0 -- #100471
- [x] `heimdal` -- #106344
- [x] `isync` -- #107672
- [x] `jack` -- #107071
- [x] `jigdo` -- incompatible as GPL-2.0-only. Downgrading in #100883
- [x] `linux-pam` -- dropped dependency in #100703
- [x] `memcacheq` -- #107248
- [x] `moc` -- #107071
- [x] `nvi` -- #107073
- [x] `perl` -- #158468
- [x] `rpm` -- dropped dependency in #100885
- [x] `skktools` -- switch to `gdbm` in #103454
- [x] `swi-prolog` -- #106345
- [x] `webalizer` -- #107304

Other refs: 
- https://en.wikipedia.org/wiki/Berkeley_DB#Licensing

**Comment by SMillerDev** [comment]
See the link in the first paragraph

**Comment by SMillerDev** [comment]
Because it can't specify what would be in a hypothetical GPLv4. It does specify that 2 & 3 are incompatible with AGPL.

**Comment by mhmdanas** [comment]
AGPLv3 _is_ incompatible with GPLv2-only, but not with GPLv3 really:

> It is also technically not compatible with GPLv3 in a strict sense: you cannot take code released under the GNU AGPL and convey or modify it however you like under the terms of GPLv3, or vice versa. However, you are allowed to combine separate modules or source files released under both of those licenses in a single project, which will provide many programmers with all the permission they need to make the programs they want

I'm inclined to say that AGPLv3 is compatible with GPLv2.0-or-later (not GPLv2.0-only), GPLv3.0-or-later, and AGPLv3.0-or-later, but I'm no lawyer.

**Comment by cho-m** [comment]
In case of GPL-2.0-or-later, it may need to be relicense to GPL-3.0-or-later (https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility -- https://www.gnu.org/licenses/gpl-faq.en.html#compat-matrix-footnote-3). Similar situation with BSD-style licenses.

Debian discussion mentioned they would probably never do this for `apt` as they would want every contributors' confirmation https://lists.debian.org/debian-legal/2013/07/msg00017.html
> a) APT is GPL2+ licensed and will stay that way out of no other choice as
I bet its more likely that hell freezes over than that we track down every
contributor since 1997 to ask for an agreement for a license change …
(yes, we could switch to GPL3+ "for free", but it's not like we would gain
 anything from it – beside generating problems for GPL2-only dependees on
 libapt of course)

---

Then, one thing to worry about is propagation of licensing terms on dependents. It is possible that some formulae may no longer be distributable via Homebrew based on license of dependencies (incompatibility with GPL-2.0-only and Apache-2.0). 

I would say the above is part of headache in licensing as the onus would be on Homebrew to track the licenses. Most upstreams assume Sleepycat variant of Berkeley DB due to catering to Linux distros, which have blocked Berkeley DB 6+ from entering repositories.

**Comment by mhmdanas** [comment]
`gnu-cobol` and `libpinyin` are both licensed under `GPL-3.0-or-later` (at least according to the Homebrew formulae), so they should need no change.

**Comment by mhmdanas** [comment]
According to [a comment by a Jack team member from 2020](https://github.com/jackaudio/jack2/issues/557#issuecomment-602190378), Jack supports libdb 5.3+. What do you all think about adding a `berkeley-db@5` formula?

**Comment by mhmdanas** [comment]
I opened PRs for many of the dependents of `berkeley-db`. The remaining ones are:
- [ ] `apt`: `GPL-2.0-or-later`, we

**Comment by iMichka** [comment]
I have one question: how do we enforce this, and how do we prevent maintainers from changing back to the latest version?

**Comment by mhmdanas** [comment]
@iMichka I have no answer for the first question, but for the second one, I plan to add comments to all the places where the `berkeley-db` dependency was downgraded to clarify the reason. I think that should be sufficient.

**Comment by SMillerDev** [comment]
This really should be an audit or at least fail the build since comments never stopped anyone from updating dependents.

**Comment by MikeMcQuaid** [comment]
> This really should be an audit or at least fail the build since comments never stopped anyone from updating dependents.

Strongly agree 👍🏻
