### ISSUE TITLE
Tracking Ventura bottling issues for top-usage formulas

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#116910]
The idea of this issue is to track and solve the build issues for macOS Ventura on our most used formulas. We already have an issue where all bottling failures are reported (https://github.com/Homebrew/homebrew-core/issues/113717), this one is to keep an eye on the most important formulas (top 1500 in analytics). This top post can be edited with a short summary of current status, while our efforts and discussion of each formula can take place below.

----

# Fail on both ARM and Intel

- [x] `r` (https://bugs.r-project.org/show_bug.cgi?id=18426) https://github.com/Homebrew/homebrew-core/pull/116998
- [x] `ncdu` (`zig` errors; different one on Intel and ARM) (https://code.blicky.net/yorhel/ncdu/issues/213) - #121034
- [x] `gtk-vnc` (and therefore `virt-manager`): https://gitlab.gnome.org/GNOME/gtk-vnc/-/issues/21 - #116964
- [ ] `swiftgen` - (upstream issue, https://github.com/SwiftGen/SwiftGen/issues/1030)
- [x] `octant`: `npm ERR! Invalid Version: ^3.0.8` - #117430
- [x] `xapian`
- [x] `notmuch`, `mu` ... all depend on `xapian`
- [X] `sdl_sound` (`Libraries were compiled with a flat namespace`): #123161 deprecated

# Fail on ARM only

- [x] `ghc` (https://gitlab.haskell.org/ghc/ghc/-/issues/21964)
- [x] `git-annex`, `pandoc`, `cabal-install`, `jupyterlab`, `exa`, `shellcheck`, `hadolint`… all depend on `ghc`
- [ ] `mono`
- [ ] `btop` (console-related test error; program builds and runs fine locally)
- [ ] `bazel` (https://github.com/bazelbuild/bazel/issues/13944)
- [ ] `hashcat`
- [x] `haskell-stack`
- [x] `ipmitool` https://github.com/Homebrew/homebrew-core/pull/117205
- [x] `nb`

# Fail on Intel only

- [x] `pyqt@5` https://github.com/Homebrew/homebrew-core/pull/117149
- [x] `vtk`, `opencv`, `octave`, `qscintilla2`, … all depend on `pyqt@5`
- [x] `poetry`
- [x] `mono` (https://github.com/mono/mono/issues/21567) https://github.com/Homebrew/homebrew-core/pull/117052
- [x] `vault` - #117298
- [x] `ruby@2.7`
- [ ] `upx` https://github.com/upx/upx/issues/612
- [x] `volk`
- [x] `gnuradio`
- [x] `meilisearch`
- [x] `pcl`

**Comment by cho-m** [comment]
Updated list with some upstream issues and related Homebrew PRs. Additional comments:
- `octant` and `vault` probably need `node` downgrade
- `pyqt@5` inreplace may need to match `sip` python version
- `hashcat` seems to build even though ephemeral ARM doesn't have OpenCL support. If the resulting bottle does work on local machines, could just skip the test.

**Comment by cho-m** [comment]
- `swiftgen` - Xcode version requirement `~> 13.0` means it can only build with Xcode **13**. May be intentional to avoid major version changes? One option is to just modify Rakefile logic to allow Xcode 14+. Otherwise, this formula will only work on 1-2 versions of macOS at a time.
- `volk` - trying to bottle again as failure was due to a missing dependency (maybe `cpu_features`). It looks like everything is bottled now.
- `bazel` - seems like an x86_64 binary is used at some point so may not work without Rosetta. Could be better on development releases (v6 / v7) as there are some commits relating to adding universal binaries, but might still be a problem as upstream issue is open.

**Comment by chenrui333** [comment]
- failed an issue for hashcat, https://github.com/hashcat/hashcat/issues/3525 (I can not run the test in my local.)

**Comment by cho-m** [comment]
`ncdu` may be blocked until new release as it currently needs `zig 0.9` to build but support for Ventura was added in `zig 0.10`. Could try applying commits from upstream's [zig-0.10 branch](https://code.blicky.net/yorhel/ncdu/commits/branch/zig-0.10) but upstream issue mentions there is noticeable performance degradation.
