### ISSUE TITLE
Tracking Ventura bottling (Intel)

### ISSUE THREAD

**Issue by iMichka** [Homebrew/homebrew-core#123214]
Extracted with `brew unbottled --eval-all --dependents --tag=ventura`

Might want to close #116910 soon to keep the final list only here.

- [x] wandio (4 dependents) #123343
- [x] rrdtool (3 dependents) #129417
- [x] libtrace (2 dependents): unbottled deps: wandio #126051 #134422
- [x] audiofile (2 dependents) #123217, deprecated
- [x] keystone (1 dependents) #129233
- [x] czmq (1 dependents) #129234
- [x] sdl_sound (1 dependents): #123161 deprecated
- [x] blast (1 dependents) #136946
- [x] gnu-prolog (1 dependents) #129336
- [x] libspectrum (1 dependents): unbottled deps: audiofile, #123217, deprecated
- [x] vorbis-tools (1 dependents) #130403
- [x] mcrypt (1 dependents): deprecated
- [x] getdns (1 dependents): #125253
- [x] libowfat (1 dependents) #132464
- [x] libflowmanager (1 dependents): unbottled deps: wandio libtrace #135692
- [x] upx (0 dependents) https://github.com/upx/upx/issues/612, #150872
- [x] datamash (0 dependents) #132895
- [x] lm4tools (0 dependents) #136839
- [x] abyss (0 dependents) #130187
- [x] rdup (0 dependents): unbottled deps: mcrypt: deprecated
- [x] xcprojectlint (0 dependents): deprecated 2008041fbf47ebe2a0a612fdac8f4f5053f7c040
- [x] aida-header (0 dependents): disabled #128198
- [x] fastp (0 dependents) #128110
- [x] bgpstream (0 dependents): unbottled deps: wandio
- [x] visitors (0 dependents) #130401
- [x] soci (0 dependents): #126173
- [x] libbpg (0 dependents) #137996, #146035
- [x] libprotoident (0 dependents): unbottled deps: wandio libtrace libflowmanager #136632
- [x] bluetoothconnector (0 dependents) #132463, https://github.com/lapfelix/BluetoothConnector/issues/25
- [x] shc (0 dependents) bf6982d955714b075bdc823e05a42acaf792c6bf
- [x] snowpack (0 dependents) #127365
- [x] raylib (0 dependents): https://github.com/Homebrew/homebrew-core/pull/124121
- [x] fwknop (0 dependents) #128109
- [x] nethack (0 dependents) #124039
- [x] fastfec (0 dependents) #123222, #123946
- [x] mrboom (0 dependents) #140912
- [x] dfix (0 dependents) #134948
- [x] ubertooth (0 dependents) #130402
- [x] libpinyin (0 dependents) #125414
- [x] cling (0 dependents) #131473, #140393
- [x] rinetd (0 dependents) #127132, f0a7198f26f03d51c77bc4035a85b8848987c5c5
- [x] rpm2cpio (0 dependents): 8ebbfbf8a4604bb37ae76b01f5923d28200fcd40
- [x] xhyve (0 dependents): deprecated
- [x] swimat (0 dependents) https://github.com/Jintin/Swimat/issues/244, #130576
- [x] mp3val (0 dependents): 515e067d81cc60414a86a6ba56e1fca1c87bb3a5
- [x] ssed (0 dependents) https://github.com/aureliojargas/sed.sf.net/issues/11#issuecomment-1523843491,  #129704
- [x] ncp (0 dependents): deprecated; unbottled deps: libowfat (deprecated)
- [x] kyua (0 dependents): deprecate #123218
- [x] sigrok-cli (0 dependents) #128215
- [x] ipmiutil (0 dependents) a4e37a800ef4524a7c045daee2e7655a075bf236
- [x] sdf (0 dependents): disabled
- [x] gcc@6 (0 dependents) deprecated
- [x] metashell (0 dependents) https://github.com/metashell/metashell/issues/282, #128202, #138798, #140453
- [x] tenyr (0 dependents) #129783
- [x] getmail (0 dependents): disabled af6558337086e29084ec580d9f125d8595c741c4
- [x] rubyfmt (0 dependents) https://github.com/fables-tales/rubyfmt/issues/440, #137470
- [x] aacgain (0 dependents) #128605
- [x] apollo-cli (0 dependents) #128606
- [x] pyflow (0 dependents) #128611
- [x] libming (0 dependents): deprecated
- [x] zyre (0 dependents): unbottled deps: czmq #135691
- [x] genometools (0 dependents) https://github.com/genometools/genometools/issues/1025
- [x] liblunar (0 dependents) #128607
- [x] smali (0 dependents) #128612
- [x] vfuse (0 dependents) #135687
- [x] libwandevent (0 dependents) #130567
- [x] lexicon (0 dependents): #118944
- [x] tth (0 dependents) #135054
- [x] zpaq (0 dependents) #128614
- [x] viewvc (0 dependents) #128608
- [x] cfv (0 dependents) #125412
- [x] libsvm (0 dependents) #124484
- [x] abricate (0 dependents): unbottled deps: blast #137046
- [x] kubernetes-service-catalog-client (0 dependents) #128609
- [x] libbitcoin-explorer (0 dependents) #137428
- [x] app-engine-python (0 dependents) #128610
- [x] tofrodos (0 dependents) #128622
- [x] wv (0 dependents) 96391fc712b92aecf44a5a4e311cdcd9a4f0319a
- [x] gtk-gnutella (0 dependents) #134688
- [x] rfcmarkup (0 dependents) #129784
- [x] gcc@7 (0 dependents) #131132
- [x] ruby@2.6 (0 dependents): disabled
- [x] shakespeare (0 dependents) #127948
- [x] elektra (0 dependents) #125863
- [x] pixz (0 dependents) #129996
- [x] dosbox (0 dependents): unbottled deps: sdl_sound: deprecated
- [x] ispell (0 dependents) #152859
- [x] ntopng (0 dependents): unbottled deps: rrdtool #129702
- [x] gcal (0 dependents) #129779, #137834
- [x] logtalk (0 dependents): unbottled deps: gnu-prolog #129510
- [x] varnish (0 dependents) 4846b09732a821daa4169cf78ddbd7d8cd154039
- [x] arturo (0 dependents) #129994
- [x] cataclysm (0 dependents) #124604
- [x] clang-format@8 (0 dependents) #134682
- [x] cassandra@3 (0 dependents): disabled
- [x] fsh (0 dependents) #128800
- [x] icoutils (0 dependents) #130568
- [x] ship (0 dependents) #128802
- [x] termshark (0 dependents) f05bf60cc5586e19fd2b5c465791b5abbec1fb30
- [x] opencsg (0 dependents) #127947
- [x] opentsdb (0 dependents) 2072aeeb79995c78b5d2f6ea2c27ba233998ae71
- [x] trafshow (0 dependents) #125044
- [x] hping (0 dependents) #125413
- [x] autopsy (0 dependents) ee21b9a52550a46b4f0afeeaff561d69dc63bc7e
- [x] gcc@8 (0 dependents) #131138
- [x] compface (0 dependents) #125047
- [x] stubby (0 dependents): unbottled deps: getdns
- [x] gcc@9 (0 dependents) #138961
- [x] dar (0 dependents)
- [x] gpsim (0 dependents)
- [x] appscale-tools (0 dependents) #129231
- [x] argus-clients (0 dependents): unbottled deps: rrdtool #129703
- [x] rawgl (0 dependents): disabled e306eba42f2de4e255f24cb958cea4850fada91b
- [x] mit-scheme (0 dependents) https://savannah.gnu.org/bugs/index.php?64611
- [x] whalebrew (0 dependents) #139468, e1a8bddd2e9fe41646962369d81573118224df16
- [x] abcde (0 dependents): unbottled deps: vorbis-tools #132587
- [x] v8@3.15 (0 dependents): disabled
- [x] platypus (0 dependents): deprecated
- [x] vala-language-server (0 dependents): https://github.com/Homebrew/homebrew-core/pull/124189
- [x] libntlm (0 dependents) 222ad071bf77e473c10a2432985f24e9b7bb617f
- [x] alerter (0 dependents) https://github.com/vjeantet/alerter/issues/53, #130571
- [x] sgn (0 dependents): unbottled deps: keystone #129335
- [x] odo-dev (0 dependents): 06d22165481ac00b91588f38c2fc76301c914eed
- [x] omega-rpg (0 dependents): #123330
- [x] freedink (0 dependents) #137994
- [x] bashdb (0 dependents) #132931
- [x] waffle (0 dependents) #135056
- [x] wbox (0 dependents) #123331
- [x] llvm@8 (0 dependents): deprecated
- [x] partio (0 dependents) #132468
- [x] qpm (0 dependents): deprecated
- [x] ne (0 dependents) #135690
- [x] llvm@9 (0 dependents): deprecated
- [x] statik (0 dependents) #130400
- [x] stlink (0 dependents): #126172
- [x] nu-smv (0 dependents): #125411
- [x] ganglia (0 dependents): unbottled deps: rrdtool #130577
- [x] swiftgen (0 dependents) #133119
- [x] mermaid-cli (0 dependents) #125048
- [x] clfft (0 dependents) #125341
- [x] fuse-emulator (0 dependents): unbottled deps: audiofile libspectrum, #123217, deprecated
- [x] ghc@8.8 (0 dependents): deprecated
- [x] chronograf (0 dependents) 965fd0ba6a72cda5e6365c087f873eb93fbc5006
- [x] openmodelica (0 dependents): deprecated

**Comment by iMichka** [comment]
All done :)
