### ISSUE TITLE
Tracking issue for cleaning up python lib formulae

### ISSUE THREAD

**Issue by cho-m** [Homebrew/homebrew-core#167905]
A dedicated tracker for any tasks to handle based on decision in #157500. 

For Homebrew/core:
- [ ] Triage python library formulae:
  * Remove python library formulae that do not meet our acceptable requirements and have low number of installs
  * Deprecate python library formulae that do not meet our acceptable requirements and have high number of installs
  * Convert/revert Python application formulae that are installed to `prefix` to instead use virtualenvs
  * Document anything remaining as approved exceptions

Extras for Homebrew/brew:
- [ ] Improve audit checks, particularly for `--new` formulae, e.g. https://github.com/Homebrew/brew/pull/16663
- [ ] Improve `brew doctor` and `--ignore-dependencies` "recommendation" for removed formulae to avoid users blindly running commands
- [ ] Optional: Maybe perform automatic "migration" to new rebuild/revision for removed formulae (which would also need to handle tab of recursive dependents)

---

Quick table based on 90-day install-on-request analytics data.

| Formula | 90-day<br>installs | 90-day<br>rank | # direct<br>dependents | Decision/comment | 
| --- | --- | --- | --- | --- |
| pycparser | 38,795 | 136 | 4 | dependency of `cryptography` |
| numpy | 38,584 | 138 | 44 | keep, https://github.com/Homebrew/brew/pull/16662 |
| cffi | 33,997 | 154 | 7 | dependency of `cryptography` |
| python-cryptography | 24,100 | 205 | 0 | renamed to `cryptography` |
| pillow | 14,684 | 293 | 21 | keep |
| pyqt@5 | 10,765 | 352 | 5 |  |
| pyqt | 10,336 | 363 | 3 |  |
| python-setuptools | 7,381 | 463 | 96 |  |
| sip | 6,932 | 477 | 6 |  |
| cryptography | 6,285 | 511 | 69 | keep, https://github.com/Homebrew/brew/pull/16662 |
| scipy | 6,248 | 512 | 4 | keep, https://github.com/Homebrew/brew/pull/16662 |
| python-requests | 4,118 | 650 | 0 | deprecated, #166056 |
| six | 2,887 | 806 | 9 |  |
| python-matplotlib | 2,823 | 820 | 0 |  |
| python-certifi | 2,262 | 928 | 0 | renamed to `certifi` |
| python-tabulate | 1,771 | 1083 | 0 |  |
| python-markupsafe | 1,742 | 1093 | 0 | removed, #165568 |
| certifi | 1,707 | 1109 | 164 | keep, https://github.com/Homebrew/brew/pull/16662 |
| python-lxml | 1,648 | 1135 | 2 |  |
| python-build | 1,564 | 1176 | 1 |  |
| python-packaging | 1,547 | 1189 | 6 |  |
| pyyaml | 1,319 | 1293 | 3 |  |
| python-markdown | 1,293 | 1313 | 0 |  |
| python-pytz | 1,104 | 1447 | 0 |  |
| python-typing-extensions | 1,033 | 1499 | 2 |  |
| pygit2 | 904 | 1630 | 0 |  |
| python-urllib3 | 877 | 1667 | 1 | deprecated, #166056 |
| pymupdf | 824 | 1717 | 1 |  |
| python-argcomplete | 813 | 1731 | 0 |  |
| lit | 678 | 1908 | 1 |  |
| python-dateutil | 644 | 1959 | 1 |  |
| wxpython | 639 | 1962 | 0 |  |
| python-psutil | 603 | 2019 | 0 |  |
| python-ply | 559 | 2101 | 1 |  |
| python-trove-classifiers | 507 | 2224 | 0 |  |
| python-chardet | 494 | 2260 | 0 |  |
| python-platformdirs | 447 | 2369 | 0 | removed, #163603 |
| python-idna | 441 | 2385 | 1 | deprecated, #166056 |
| python-boto3 | 398 | 2511 | 0 | removed, #163229 |
| python-pyparsing | 389 | 2541 | 1 |  |
| python-jinja | 366 | 2631 | 0 | removed, #165495 |
| python-hatchling | 339 | 2749 | 0 | removed, #166358 |
| python-distlib | 247 | 3277 | 0 | removed, #163570 |
| meson-python | 235 | 3363 | 1 |  |
| python-charset-normalizer | 218 | 3503 | 1 | deprecated, #166056 |
| pyqt-builder | 214 | 3530 | 3 |  |
| python-setuptools-scm | 179 | 3879 | 3 |  |
| python-flit-core | 174 | 3942 | 4 |  |
| python-click | 171 | 3983 | 0 | removed, #165496 |
| python-toml | 170 | 4000 | 0 | removed, #165493 |
| python-sympy | 169 | 4010 | 0 | removed, #165494 |
| python-mako | 169 | 4016 | 0 | removed, #165568 |
| python-pluggy | 149 | 4239 | 0 | removed, #166358 |
| python-pycurl | 148 | 4247 | 0 | removed, #164368 |
| python-mutagen | 116 | 4715 | 0 | removed, #164365 |
| python-pathspec | 114 | 4742 | 0 | removed, #166358 |
| pawk | 111 | 4785 | 0 |  |
| python-brotli | 107 | 4869 | 0 | removed, #165112 |
| python-attrs | 102 | 4937 | 0 | removed, #163625 |
| python-networkx | 95 | 5069 | 0 | removed, #166185 |
| python-botocore | 84 | 5306 | 0 | removed, #163229 |
| python-magic | 81 | 5374 | 0 | removed, #164158 |
| python-filelock | 78 | 5446 | 0 | removed, #164940 |
| python-openapi3 | 71 | 5638 | 0 | removed, #163442 |
| python-cli-helpers | 70 | 5666 | 0 | removed, #163436 |
| python-colorama | 69 | 5694 | 0 | removed, #163437 |
| python-distro | 67 | 5750 | 0 | removed, #164160 |
| python-cycler | 64 | 5839 | 1 |  |
| python-abseil | 62 | 5908 | 0 | removed, #163343 |
| python-regex | 61 | 5918 | 0 | removed, #164146 |
| ly | 58 | 6025 | 0 |  |
| python-docopt | 55 | 6100 | 0 | removed, #164149 |
| python-pbr | 55 | 6134 | 0 | removed, #164154 |
| python-configargparse | 52 | 6242 | 0 | removed, #163438 |
| python-hatch-vcs | 52 | 6243 | 0 | removed, #164144 |
| python-json5 | 52 | 6244 | 0 | removed, #163642 |
| python-xlsxwriter | 51 | 6288 | 0 | removed, #163646 |
| python-kiwisolver | 49 | 6382 | 1 |  |
| python-requests-oauthlib | 48 | 6421 | 0 | removed, #163590 |
| python-hatch-fancy-pypi-readme | 47 | 6462 | 0 | removed, #164085 |
| python-prompt-toolkit | 47 | 6463 | 0 | removed, #163576 |
| python-termcolor | 46 | 6511 | 0 | removed, #163378 |
| python-rich | 45 | 6557 | 0 | removed, #163623 |
| python-asn1crypto | 43 | 6655 | 0 | removed, #163363 |
| python-oauthlib | 43 | 6656 | 0 | removed, #163712 |
| python-cachetools | 41 | 6745 | 0 | removed, #163425 |
| python-pyproject-hooks | 39 | 6835 | 0 | removed, #166183 |
| python-websocket-client | 39 | 6836 | 0 | removed, #163645 |
| python-dicttoxml | 32 | 7219 | 0 | removed, #163567 |
| python-mpmath | 32 | 7220 | 0 | removed, #165494 |
| python-markdown-it-py | 30 | 7362 | 0 | removed, #164086 |
| python-anytree | 29 | 7431 | 0 | removed, #163424 |
| python-wcwidth | 28 | 7489 | 0 | removed, #163592 |
| python-msgpack | 27 | 7555 | 0 | removed, #164148 |
| python-jmespath | 13 | 9027 | 0 | removed, #163229 |
| python-configobj | 7 | 10540 | 0 | removed, #163565 |
| python-mdurl | 7 | 10541 | 0 | removed, #164086 |
| python-s3transfer | 6 | 10927 | 0 | removed, #163229 |

**Comment by carlocab** [comment]
Should probably keep `pygit2` -- it links with `libgit2`, and vendoring it into its dependents leads to really long build times (due to revision bumps) when `libgit2` is updated.

**Comment by LecrisUT** [comment]
I've opened an [issue](https://github.com/Homebrew/homebrew-core/issues/169501) to point out a potential problems with the build process, specifically affecting python projects which have `setuptools-scm` as a dependency

**Comment by SMillerDev** [comment]
> What is the reason for removing `python-requests`?

It's a library, not something that's useful on its own. People are better off adding it to their requirements.txt if they need it somewhere.

**Comment by saurik** [comment]
FWIW, my pitch for python-packaging -- apparently now deprecated and soon to be removed due to #176511 -- is that I see it being used as part of peoples' meson builds, and the workaround for it not being part of the distribution is both annoying and non-obvious (I certainly wouldn't have done it correctly), and yet winds up being forced on everyone attempting to compile such packages, whether as a developer automating their build system or as a user who wants to one-off build a random project they checked out which uses meson.

You can actually see this at work in the glib formula: instead of merely marking python-packaging as a build dependency, it instead must vendor a specific version of the package -- which already feels wrong, as this is something that is going to have to get updated, and yet is going to be more coupled to python than glib -- and then futz around with the PYTHON_PATH to inject it into the system python search path, as, apparently, doing this work using a virtual env and passing that separate python context to meson causes glib to not work correctly, per the giant comment in the formula.

https://github.com/Homebrew/homebrew-core/blob/302c6d8548ee77a6753b7d8c3da66bab03758b55/Formula/g/glib.rb#L55-L58

https://github.com/Homebrew/homebrew-core/blob/302c6d8548ee77a6753b7d8c3da66bab03758b55/Formula/g/glib.rb#L71-L81

I also found a mention by a maintainer of meson (@eli-schwartz) in a discussion of what modules might be useful to include in a standalone copy of meson into which one cannot install additional dependencies--which, FWIW, seems to be the case with Homebrew now, given that python3 is externally managed and these packages that are normally used to accomplish the same goals are largely being deprecated--and packaging is specifically and narrowly called out as "probably a good thing to include" as it is apparently being commonly in various meson build scripts as a replacement for some useful functions from distutils. 

https://github.com/mesonbuild/meson/discussions/13007#discussioncomment-8951515

> The official MSI installer for meson on Windows doesn't include any third-party modules so that probably encourages users to avoid overreliance on such modules. However the packaging module does contain the version parsing and comparison code that replaces distutils functions, so that's probably a good thing to include just in case as people may have ported away from distutils in their script commands.

@cho-m @woodruffw Is there any hope of getting a stay of execution on the python-packaging formula?

**Comment by carlocab** [comment]
> Is there any hope of getting a stay of execution on the python-packaging formula?

The discussion above seems like good reasoning for this for me, but CC @Homebrew/core for thoughts.

**Comment by SMillerDev** [comment]
> Really, anything we're repeatedly resourceing in multiple formulae in this sort of non-trivial way feels better handled as a resource.

You mean resources where we have to mess with pythonpath might be eligible to be formulae right? Not just "anything that we resource a lot" because that used to be the strategy.

**Comment by MikeMcQuaid** [comment]
> You mean resources where we have to mess with pythonpath might be eligible to be formulae right? Not just "anything that we resource a lot" because that used to be the strategy.

Resources where we're having to write elaborate explanations and provide workarounds like this and we have helpful community members like @saurik taking the time to explain why.

I don't think a "follow this rule and you don't have to think about it" approach is going to work in either direction (not that I'm claiming you're saying that either, to be clear).

**Comment by daeho-ro** [comment]
`pydantic-core` reosurce for python packages now seen 61 times, could we make it as a formula? It depends on `rust` and so maybe we can reduce build time by doing this.

**Comment by MikeMcQuaid** [comment]
@daeho-ro if a resource needs `rust` or another heavy `:build` dependency: yes, definitely.

**Comment by GunniBusch** [comment]
i have a question. There are some python formulae that are both cli and can also be used as libraries. And since those are already in homebrew, would it be possible to also enable them to be used as libraries too for other formulae?

My reasoning behind this, is that this might reduce duplication in a lot of packages. For example `pygments` is used ass resource in around 100 python formulae, but there also exists [pygments](https://github.com/Homebrew/homebrew-core/blob/9a588d2335c1fda295cb0ce9ff76b9cff8ab8409/Formula/p/pygments.rb).

**Comment by MikeMcQuaid** [comment]
@GunniBusch I don't have a full understanding, there may be a reason we can't but, unless there is one: this seems to make sense to me?

**Comment by daeho-ro** [comment]
It doesn't require extra dependency like `rust`, so not much beneficial I think.

**Comment by GunniBusch** [comment]
> It doesn't require extra dependency like `rust`, so not much beneficial I think.

I think the benefit is the same as having dynamically linked stuff

**Comment by daeho-ro** [comment]
You can see that `requests` and `urllib3` they also in 200+ formulae but they were deprecated from formulae and being resources for now.

**Comment by MikeMcQuaid** [comment]
@daeho-ro what are pros and cons here on formula vs. resource?

**Comment by daeho-ro** [comment]
From https://github.com/Homebrew/homebrew-core/issues/157500, 

> > python-requests
>
> This has no non-Python build dependencies and the installation is very simple so 👎🏻, it should not be a formula.

--- 

Maybe we could reduce small build time, can handle single point of bump even if there is a CVE. But doing this is feel like a build pypi again and should handle `exclude_packages` in 200+ formulae.

I have only tried to make python package into formula if it takes too long to build or external build dependencies.

**Comment by GunniBusch** [comment]
> From https://github.com/Homebrew/homebrew-core/issues/157500, 
> 
> > > python-requests
> >
> > This has no non-Python build dependencies and the installation is very simple so 👎🏻, it should not be a formula.
> 
> --- 
> 
> Maybe we could reduce small build time, can handle single point of bump even if there is a CVE. But doing this is feel like a build pypi again and should handle `exclude_packages` in 200+ formulae.
> 
> I have only tried to make python package into formula if it takes too long to build or external build dependencies.

I get it. But there are python formulae that are used for like their cli. But those could also used as libraries. So my point is that we could just enable existing formulae to be able to bemused as packages

**Comment by daeho-ro** [comment]
Their library is usually installed in venv not global. You can try
```
pip3 list
```
and see it is listed here or not. I think mostly not.

**Comment by GunniBusch** [comment]
> Their library is usually installed in venv not global. You can try
> ```
> pip3 list
> ```
> and see it is listed here or not. I think mostly not. 

Yes but we can link to it via pyc? Or something like that. I think PyTorch pr so is doing that. 

Also my goal is not reducing build time. My goal is that if there is like a security vulnerability we only need to update one dependency

**Comment by eli-schwartz** [comment]
> Also my goal is not reducing build time. My goal is that if there is like a security vulnerability we only need to update one dependency

That is *always* one of the core arguments for a package manager to include packages containing shared resources (including but not limited to C/C++ libraries).

The existence of this tracking issue is a testimonial that homebrew has had a discussion about the topic and concluded that "if there is a security vulnerability we only need to update one dependency" is a BAD tradeoff for them compared to the complexity and effort (so they say) of including additional packages.

It is irrational and illogical to post to this ticket talking about the benefits of security vulnerability handling. Your argument is not applicable to this tracking ticket -- your argument is an attempt to propose that the original policy discussion which resulted in this implementation tracking ticket, made the *wrong* policy decision and should be overturned and reverted.

I mean, I don't disagree with you. I was `@mention`ed here because I'm an upstream maintainer of software that homebrew packages. I don't use homebrew and don't plan on ever doing so, because I'm quite happy with my Linux package manager -- for the distro I'm also a developer for. And I / we care about sharing python module dependencies, and it is *work* to share python module dependencies but we do it because we believe that sharing them is a valuable tradeoff and worth spending complexity and effort.

So I can speak from experience when I say that sharing python module dependencies is complexity and effort, and it's not because of writing out the build recipe ("formulae") -- it is running tinderboxing tests to ensure that upgrades to a dependency don't break other packages, and backporting upstream bugfixes to fix breakage. Some of this work is already needed if any package depends on a library that has a security issue and also a breaking change, but we pay the cost all the time in small quantities and then it's no effort when the security vulnerability itself shows up.

Homebrew doesn't wanna do it? Okay -- homebrew doesn't wanna do it. Respect that, or don't use homebrew, or become a homebrew developer and champion the movement to put in the effort.

Just it really seems silly to me to try to fight the system over one or two packages here and there on the basis of a formula already being present for the cli.

**Comment by MikeMcQuaid** [comment]
> or become a homebrew developer and champion the movement to put in the effort.

@eli-schwartz While I appreciate the defence of the Homebrew maitnainers here, @GunniBusch has made a large number of positive contributions to Homebrew recently so I very much did read his message with the context of "and if you agree: I will do the work" as that has been his approach throughout.

**Comment by GunniBusch** [comment]
> Just it really seems silly to me to try to fight the system over one or two packages here and there on the basis of a formula already being present for the cli.

I completely agree, and keeping maintainer workloads lower also has indirect positive impact on me.
But lately I have worked on multiple python formulae and found that there are already a lot of python formulae, that could be used as libraries but where used only for their cli. So enabling the library „feature“ would not add up any more work in my opinion, even in the contrary. Even if it reduces you local build time by 10 seconds, adding this up too all formulae using this python lib, will sum up to like 16 minutes.

Also maintaining more Ressource blocks are not less time expensive than maintaining one formulae. But I agree that this was already discussed, but since this issue was not closed, I felt that not everything was mentioned (else why wasn’t the issue closed). 

But yes I completely understand that normally comments do mean, „do that, I just complain“ 😛

**Comment by p-linnane** [comment]
One consideration here is that we have `brew update-python-resources` that runs and pulls the correct resources for most Python formulae automatically. We previously encountered lots of issues when something like a `requests` formula was updated, and then broke new builds of other software that wasn't ready for it. It's just easier to maintain this way.

**Comment by GunniBusch** [comment]
> One consideration here is that we have brew update-python-resources that runs and pulls the correct resources for most Python formulae automatically. We previously encountered lots of issues when something like a requests formula was updated, and then broke new builds of other software that wasn't ready for it. It's just easier to maintain this way.

This is a good point. I have also rarely (might be wrong here) seen a `update-python-resources` pr failing, or at least an elevated amount failing. (Except maybe when there was this setuptools issue 2 month ago).  I think I have been a bit ignorant regarding issues that happen when dependents are not compatible with a formulae, even though I have seen that first hand with `vapoursynth R75`. 

And the strange part is, my opinion changes regularly during: "seeing python software x taking longer to build than openjdk" and "fighting with formula x failing because it is incompatible with a recursive dependency is incompatible".

Maybe to solution here might not be around what formula/ressource to outsource but maybe more stupid, like enhancing caching or similar.

**Comment by Bo98** [comment]
The primary reason is basically that dependents will have a list of requirements listed in their package based on version bounds, e.g. `somepackage >= 1.2.3, < 1.4.5`. This is problematic because:

* Homebrew does not store or track this information itself (so test-bot cannot properly check for it without doing full build-from-source dependent test which would be insane to do for every Python library dependent)
* Homebrew is a rolling release package manager and does not support dependencies with version bounds itself, so everytime an older version is needed it would require a versioned formula or just bundling it as a resource again. The complexity of that could easily balloon out of control if not careful.

Is this fixable? Probably. Is it something we'd want? Only if it had a good design that was agreed beforehand.

The problem that led to this issue is that there were suddenly hundreds of Python library formulae that appeared in the span of just a few weeks. This was proven to be problematic and was done without consensus between maintainers and had to be reverted to restore health to dependents. You can read about the decision in https://github.com/Homebrew/homebrew-core/issues/157500, though a lot of that discussion was done in-person at the AGM.

With that said, the few we kept do still have the same risks associated to them - we just justified taking on those risks. For example, it is possible a `cryptography` update is incompatible with the version bounds of some dependents and `test-bot` does not detect this, but the security nature of the package and its build requirements have outweighed the risks in that particular scenario. For this reason, Python libraries that are also available on PyPI are only accepted if you are able to provide strong reasons for them that justify the risks.

There's definitely room for improvement here for sure but hopefully that clarifies the current state a little.

**Comment by MikeMcQuaid** [comment]
Thanks @Bo98. I think it's probably worth closing this out for now: it's been open a couple of years and there's no ongoing progress (and some confusion) from having it open.
