### ISSUE TITLE
 Failed during: /usr/local/bin/brew update --force when install brew

### ISSUE THREAD

**Issue by Jony-Gays** [Homebrew/homebrew-core#35596]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I have problem with my brew because suddenly command brew not found in terminal. So I uninstall and try to reinstall again using /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)

- What happened (include command output)
It show error
Failed during: /usr/local/bin/brew update --force

The log
```
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
HEAD is now at 2ff07a60 Merge pull request #5458 from Homebrew/readme-remove-coverage
.git/rebase-apply/patch:1935: trailing whitespace.
 
.git/rebase-apply/patch:1941: trailing whitespace.
 
.git/rebase-apply/patch:1944: trailing whitespace.
 
.git/rebase-apply/patch:1950: trailing whitespace.
 
.git/rebase-apply/patch:1953: space before tab in indent.
 	int cols = num_cols();
warning: squelched 383 whitespace errors
warning: 388 lines add whitespace errors.
error: Failed to merge in the changes.
Patch failed at 0001 pango: update 1.40.12 bottle.
Use 'git am --show-current-patch' to see the failed patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

To restore the stashed changes to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core run:
  'cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash pop'
Error: 784: unexpected token at '{
<<<<<<< HEAD
  "abyss": "homebrew/core",
  "ampl-mp": "homebrew/core",
  "armadillo": "homebrew/core",
  "arpack": "homebrew/core",
  "augustus": "homebrew/core",
  "bamtools": "homebrew/core",
  "bcftools": "homebrew/core",
  "beast": "homebrew/core",
  "bedops": "homebrew/core",
  "bedtools": "homebrew/core",
  "bioawk": "homebrew/core",
  "blast": "homebrew/core",
  "bowtie2": "homebrew/core",
  "bwa": "homebrew/core",
  "ceres-solver": "homebrew/core",
  "cfitsio": "homebrew/core",
  "clblas": "homebrew/core",
  "clfft": "homebrew/core",
  "clinfo": "homebrew/core",
  "cminpack": "homebrew/core",
  "cp2k": "homebrew/core",
  "cppad": "homebrew/core",
  "datamash": "homebrew/core",
  "diamond": "homebrew/core",
  "dlib": "homebrew/core",
  "fastqc": "homebrew/core",
  "field3d": "homebrew/core",
  "flann": "homebrew/core",
  "gdcm": "homebrew/core",
  "genometools": "homebrew/core",
  "glpk": "homebrew/core",
  "gmsh": "homebrew/core",
  "gmt": "homebrew/core",
  "gmt4": "homebrew/core",
  "graph-tool": "homebrew/core",
  "gromacs": "homebrew/core",
  "hdf5": "homebrew/core",
  "hdf5@1.8": "homebrew/core",
  "hmmer": "homebrew/core",
  "htslib": "homebrew/core",
  "hwloc": "homebrew/core",
  "hypre": "homebrew/core",
  "igraph": "homebrew/core",
  "igv": "homebrew/core",
  "kallisto": "homebrew/core",
  "lammps": "homebrew/core",
  "libmatio": "homebrew/core",
  "maxima": "homebrew/core",
  "metis": "homebrew/core",
  "nco": "homebrew/core",
  "ncview": "homebrew/core",
  "netcdf": "homebrew/core",
  "nlopt": "homebrew/core",
  "octave": "homebrew/core",
  "openblas": "homebrew/core",
  "opencascade": "homebrew/core",
  "opencv3": "homebrew/core",
  "orocos-kdl": "homebrew/core",
  "packmol": "homebrew/core",
  "pcb": "homebrew/core",
  "pcl": "homebrew/core",
  "petsc": "homebrew/core",
  "picard-tools": "homebrew/core",
  "prodigal": "homebrew/core",
  "qhull": "homebrew/core",
  "qrupdate": "homebrew/core",
  "r": "homebrew/core",
  "r-gui": "caskroom/cask/r-app",
  "root": "homebrew/core",
  "root6": "homebrew/core",
  "samtools": "homebrew/core",
  "scalapack": "homebrew/core",
  "seqtk": "homebrew/core",
  "shogun": "homebrew/core",
  "sickle": "homebrew/core",
  "spades": "homebrew/core",
  "sratoolkit": "homebrew/core",
  "suite-sparse": "homebrew/core",
  "sundials": "homebrew/core",
  "superlu": "homebrew/core",
  "tensorflow": "homebrew/core",
  "transfig": "homebrew/core",
  "vcftools": "homebrew/core",
  "veclibfort": "homebrew/core",
  "vips": "homebrew/core",
  "visp": "homebrew/core",
  "voro++": "homebrew/core",
  "vtk": "homebrew/core",
  "wxmaxima": "homebrew/core"
=======
  "adobe-air-sdk": "caskroom/cask",
  "android-ndk": "caskroom/cask",
  "android-platform-tools": "caskroom/cask",
  "android-sdk": "caskroom/cask",
  "auctex": "homebrew/tex",
  "avidemux": "caskroom/cask",
  "awsenv": "Luzifer/tools",
  "cantera": "homebrew/science",
  "cloudfoundry-cli": "pivotal/tap",
  "cmucl": "caskroom/cask",
  "crystax-ndk": "caskroom/cask",
  "corelocationcli": "caskroom/cask",
  "dart": "dart-lang/dart",
  "dgtal": "homebrew/science",
  "dotwrp": "homebrew/science",
  "drush": "homebrew/php",
  "dwarf-fortress": "caskroom/cask",
  "geany": "caskroom/cask",
  "geda-gaf": "homebrew/science",
  "ggobi": "homebrew/science",
  "gimp": "caskroom/cask",
  "grads": "caskroom/cask",
  "gtkwave": "caskroom/cask",
  "hdf@4": "homebrew/science",
  "helios": "spotify/public",
  "hexchat": "caskroom/cask",
  "horndis": "caskroom/cask",
  "inkscape": "caskroom/cask",
  "ipopt": "homebrew/science",
  "itsol": "homebrew/science",
  "jsl": "caskroom/cask",
  "kdiff3": "caskroom/cask",
  "keybase": "caskroom/cask",
  "magit": "dunn/emacs",
  "meld": "caskroom/cask",
  "n98-magerun": "homebrew/php",
  "newick-utils": "homebrew/science",
  "openfst": "homebrew/science",
  "opengrm-ngram": "homebrew/science",
  "osxfuse": "caskroom/cask",
  "pdf-tools": "dunn/emacs",
  "pebble-sdk": "pebble/pebble-sdk",
  "pocl": "homebrew/science",
  "quassel": "caskroom/cask",
  "salt": "homebrew/science",
  "shark": "homebrew/science",
  "slicot": "homebrew/science",
  "sqlitebrowser": "caskroom/cask",
  "tetgen": "homebrew/science",
  "ticcutils": "homebrew/science",
  "timbl": "homebrew/science",
  "transmission-remote-gtk": "caskroom/cask/transmission-remote-gui",
  "tuntap": "caskroom/cask",
  "wopr": "homebrew/science"
>>>>>>> pango: update 1.40.12 bottle.
}
'
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:571:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/tap.rb:710:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:228:in `block in report'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:207:in `each_line'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:207:in `report'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:426:in `add'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:105:in `block in update_report'
/usr/local/Homebrew/Library/Homebrew/tap.rb:589:in `block (2 levels) in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:588:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:588:in `block in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:587:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:587:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:94:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Failed during: /usr/local/bin/brew update --force
```

Please Help me
Thank You

**Comment by SMillerDev** [comment]
Could you remove `/usr/local/Homebrew` and try again?

**Comment by rmzse** [comment]
I had the same error message but with a different course of events 

```
Computername:~ localusername$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /usr/local/Homebrew
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/Homebrew
==> /usr/bin/sudo /bin/chmod 755 /usr/local/share/zsh /usr/local/share/zsh/site-functions
==> /usr/bin/sudo /usr/sbin/chown localusername /usr/local/Homebrew
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/Homebrew
==> Downloading and installing Homebrew...
remote: Enumerating objects: 78, done.
remote: Total 78 (delta 0), reused 0 (delta 0), pack-reused 78
Unpacking objects: 100% (78/78), done.
From https://github.com/<USER>/<REPO>
 * [new branch]      master     -> origin/master
HEAD is now at 09b50f5 complete grid and the colouring of boxes
Failed during: /usr/local/bin/brew update --force
```

We tried to remove the `/usr/local/Homebrew` directory but that did not work.

Then we tried to use the install script by saving it locally as an .rb file and run it with `ruby file.rb` without the command that gives the error by downloading and commenting out that specific line (line 357).

```
#!/usr/bin/ruby
# This script installs to /usr/local only. To install elsewhere (which is
# unsupported) you can untar https://github.com/Homebrew/brew/tarball/master
# anywhere you like.
HOMEBREW_PREFIX = "/usr/local".freeze
HOMEBREW_REPOSITORY = "/usr/local/Homebrew".freeze
HOMEBREW_CORE_TAP = "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core".freeze
HOMEBREW_CACHE = "#{ENV["HOME"]}/Library/Caches/Homebrew".freeze
BREW_REPO = "https://github.com/Homebrew/brew".freeze

# TODO: bump version when new macOS is released
MACOS_LATEST_SUPPORTED = "10.14".freeze
# TODO: bump version when new macOS is released
MACOS_OLDEST_SUPPORTED = "10.12".freeze

# no analytics during installation
ENV["HOMEBREW_NO_ANALYTICS_THIS_RUN"] = "1"
ENV["HOMEBREW_NO_ANALYTICS_MESSAGE_OUTPUT"] = "1"

# get nicer global variables
require "English"

module Tty
  module_function

  def blue
    bold 34
  end

  def red
    bold 31
  end

  def reset
    escape 0
  end

  def bold(code = 39)
    escape "1;#{code}"
  end

  def underline
    escape "4;39"
  end

  def escape(code)
    "\033[#{code}m" if STDOUT.tty?
  end
end

class Array
  def shell_s
    cp = dup
    first = cp.shift
    cp.map { |arg| arg.gsub " ", "\\ " }.unshift(first).join(" ")
  end
end

def ohai(*args)
  puts "#{Tty.blue}==>#{Tty.bold} #{args.shell_s}#{Tty.reset}"
end

def warn(warning)
  puts "#{Tty.red}Warning#{Tty.reset}: #{warning.chomp}"
end

def system(*args)
  abort "Failed during: #{args.shell_s}" unless Kernel.system(*args)
end

def sudo(*args)
  args.unshift("-A") unless ENV["SUDO_ASKPASS"].nil?
  ohai "/usr/bin/sudo", *args
  system "/usr/bin/sudo", *args
end

def getc
  system "/bin/stty raw -echo"
  if STDIN.respond_to?(:getbyte)
    STDIN.getbyte
  else
    STDIN.getc
  end
ensure
  system "/bin/stty -raw echo"
end

def wait_for_user
  puts
  puts "Press RETURN to continue or any other key to abort"
  c = getc
  # we test for \r and \n because some stuff does \r instead
  abort unless (c == 13) || (c == 10)
end

class Version
  include Comparable
  attr_reader :parts

  def initialize(str)
    @parts = str.split(".").map(&:to_i)
  end

  def <=>(other)
    parts <=> self.class.new(other).parts
  end

  def to_s
    parts.join(".")
  end
end

def macos_version
  @macos_version ||= Version.new(`/usr/bin/sw_vers -productVersion`.chomp[/10\.\d+/])
end

def should_install_command_line_tools?
  if macos_version > "10.13"
    !File.exist?("/Library/Developer/CommandLineTools/usr/bin/git")
  else
    !File.exist?("/Library/Developer/CommandLineTools/usr/bin/git") ||
      !File.exist?("/usr/include/iconv.h")
  end
end

def user_only_chmod?(path)
  return false unless File.directory?(path)

  mode = File.stat(path).mode & 0777
  # u = (mode >> 6) & 07
  # g = (mode >> 3) & 07
  # o = (mode >> 0) & 07
  mode != 0755
end

def chmod?(path)
  File.exist?(path) && !(File.readable?(path) && File.writable?(path) && File.executable?(path))
end

def chown?(path)
  !File.owned?(path)
end

def chgrp?(path)
  !File.grpowned?(path)
end

# Invalidate sudo timestamp before exiting (if it wasn't active before).
Kernel.system "/usr/bin/sudo -n -v 2>/dev/null"
at_exit { Kernel.system "/usr/bin/sudo", "-k" } unless $CHILD_STATUS.success?

# The block form of Dir.chdir fails later if Dir.CWD doesn't exist which I
# guess is fair enough. Also sudo prints a warning message for no good reason
Dir.chdir "/usr"

####################################################################### script
if RUBY_PLATFORM.to_s.downcase.include?("linux")
  abort <<-EOABORT
  To install Linuxbrew, paste at a terminal prompt:
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  EOABORT
elsif macos_version < "10.7"
  abort <<-EOABORT
Your Mac OS X version is too old. See:
  #{Tty.underline}https://github.com/mistydemeo/tigerbrew#{Tty.reset}"
  EOABORT
elsif macos_version < "10.9"
  abort "Your OS X version is too old"
elsif Process.uid.zero?
  abort "Don't run this as root!"
elsif !`dsmemberutil checkmembership -U "#{ENV["USER"]}" -G admin`.include?("user is a member")
  abort "This script requires the user #{ENV["USER"]} to be an Administrator."
elsif File.directory?(HOMEBREW_PREFIX) && (!File.executable? HOMEBREW_PREFIX)
  abort <<-EOABORT
The Homebrew prefix, #{HOMEBREW_PREFIX}, exists but is not searchable. If this is
not intentional, please restore the default permissions and try running the
installer again:
    sudo chmod 775 #{HOMEBREW_PREFIX}
  EOABORT
# TODO: bump version when new macOS is released
elsif macos_version > MACOS_LATEST_SUPPORTED || macos_version < MACOS_OLDEST_SUPPORTED
  who = "We"
  if macos_version > MACOS_LATEST_SUPPORTED
    what = "pre-release version"
  elsif macos_version < MACOS_OLDEST_SUPPORTED
    who << " (and Apple)"
    what = "old version"
  else
    return
  end
  ohai "You are using macOS #{macos_version.parts.join(".")}."
  ohai "#{who} do not provide support for this #{what}."

  puts <<-EOS
This installation may not succeed.
After installation, you will encounter build failures and other breakages.
Please create pull requests instead of asking for help on Homebrew's
GitHub, Discourse, Twitter or IRC. As you are running this #{what},
you are responsible for resolving any issues you experience.

  EOS
end

ohai "This script will install:"
puts "#{HOMEBREW_PREFIX}/bin/brew"
puts "#{HOMEBREW_PREFIX}/share/doc/homebrew"
puts "#{HOMEBREW_PREFIX}/share/man/man1/brew.1"
puts "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_brew"
puts "#{HOMEBREW_PREFIX}/etc/bash_completion.d/brew"
puts HOMEBREW_REPOSITORY.to_s

# Keep relatively in sync with
# https://github.com/Homebrew/brew/blob/master/Library/Homebrew/keg.rb
group_chmods = %w[bin etc include lib sbin share opt var
                  Frameworks
                  etc/bash_completion.d lib/pkgconfig
                  share/aclocal share/doc share/info share/locale share/man
                  share/man/man1 share/man/man2 share/man/man3 share/man/man4
                  share/man/man5 share/man/man6 share/man/man7 share/man/man8
                  var/log var/homebrew var/homebrew/linked
                  bin/brew]
               .map { |d| File.join(HOMEBREW_PREFIX, d) }
               .select { |d| chmod?(d) }
# zsh refuses to read from these directories if group writable
zsh_dirs = %w[share/zsh share/zsh/site-functions]
           .map { |d| File.join(HOMEBREW_PREFIX, d) }
mkdirs = %w[bin etc include lib sbin share var opt
            share/zsh share/zsh/site-functions
            var/homebrew var/homebrew/linked
            Cellar Caskroom Homebrew Frameworks]
         .map { |d| File.join(HOMEBREW_PREFIX, d) }
         .reject { |d| File.directory?(d) }

user_chmods = zsh_dirs.select { |d| user_only_chmod?(d) }
chmods = group_chmods + user_chmods
chowns = chmods.select { |d| chown?(d) }
chgrps = chmods.select { |d| chgrp?(d) }

unless group_chmods.empty?
  ohai "The following existing directories will be made group writable:"
  puts(*group_chmods)
end
unless user_chmods.empty?
  ohai "The following existing directories will be made writable by user only:"
  puts(*user_chmods)
end
unless chowns.empty?
  ohai "The following existing directories will have their owner set to #{Tty.underline}#{ENV["USER"]}#{Tty.reset}:"
  puts(*chowns)
end
unless chgrps.empty?
  ohai "The following existing directories will have their group set to #{Tty.underline}admin#{Tty.reset}:"
  puts(*chgrps)
end
unless mkdirs.empty?
  ohai "The following new directories will be created:"
  puts(*mkdirs)
end
if should_install_command_line_tools?
  ohai "The Xcode Command Line Tools will be installed."
end

wait_for_user if STDIN.tty? && !ENV["CI"]

if File.directory? HOMEBREW_PREFIX
  sudo "/bin/chmod", "u+rwx", *chmods unless chmods.empty?
  sudo "/bin/chmod", "g+rwx", *group_chmods unless group_chmods.empty?
  sudo "/bin/chmod", "755", *user_chmods unless user_chmods.empty?
  sudo "/usr/sbin/chown", ENV["USER"], *chowns unless chowns.empty?
  sudo "/usr/bin/chgrp", "admin", *chgrps unless chgrps.empty?
else
  sudo "/bin/mkdir", "-p", HOMEBREW_PREFIX
  sudo "/usr/sbin/chown", "root:wheel", HOMEBREW_PREFIX
end

unless mkdirs.empty?
  sudo "/bin/mkdir", "-p", *mkdirs
  sudo "/bin/chmod", "g+rwx", *mkdirs
  sudo "/bin/chmod", "755", *zsh_dirs
  sudo "/usr/sbin/chown", ENV["USER"], *mkdirs
  sudo "/usr/bin/chgrp", "admin", *mkdirs
end

sudo "/bin/mkdir", "-p", HOMEBREW_CACHE unless File.directory? HOMEBREW_CACHE
sudo "/bin/chmod", "g+rwx", HOMEBREW_CACHE if chmod? HOMEBREW_CACHE
sudo "/usr/sbin/chown", ENV["USER"], HOMEBREW_CACHE if chown? HOMEBREW_CACHE
sudo "/usr/bin/chgrp", "admin", HOMEBREW_CACHE if chgrp? HOMEBREW_CACHE

if should_install_command_line_tools?
  ohai "Searching online for the Command Line Tools"
  # This temporary file prompts the 'softwareupdate' utility to list the Command Line Tools
  clt_placeholder = "/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress"
  sudo "/usr/bin/touch", clt_placeholder

  clt_macos_version = if macos_version == "10.9"
    "Mavericks"
  else
    macos_version
  end
  clt_sort = if macos_version >= "10.13"
    "sort -V"
  else
    "sort"
  end
  clt_label_command = "/usr/sbin/softwareupdate -l | " \
                      "grep -B 1 -E 'Command Line (Developer|Tools)' | " \
                      "awk -F'*' '/^ +\\*/ {print $2}' | " \
                      "grep '#{clt_macos_version}' | " \
                      "#{clt_sort} | " \
                      "sed 's/^ *//' | " \
                      "tail -n1"
  clt_label = `#{clt_label_command}`.chomp

  unless clt_label.empty?
    ohai "Installing #{clt_label}"
    sudo "/usr/sbin/softwareupdate", "-i", clt_label
    sudo "/bin/rm", "-f", clt_placeholder
    sudo "/usr/bin/xcode-select", "--switch", "/Library/Developer/CommandLineTools"
  end
end

# Headless install may have failed, so fallback to original 'xcode-select' method
if should_install_command_line_tools? && STDIN.tty?
  ohai "Installing the Command Line Tools (expect a GUI popup):"
  sudo "/usr/bin/xcode-select", "--install"
  puts "Press any key when the installation has completed."
  getc
  sudo "/usr/bin/xcode-select", "--switch", "/Library/Developer/CommandLineTools"
end

abort <<-EOABORT if `/usr/bin/xcrun clang 2>&1` =~ /license/ && !$CHILD_STATUS.success?
You have not agreed to the Xcode license.
Before running the installer again please agree to the license by opening
Xcode.app or running:
    sudo xcodebuild -license
EOABORT

ohai "Downloading and installing Homebrew..."
Dir.chdir HOMEBREW_REPOSITORY do
  # we do it in four steps to avoid merge errors when reinstalling
  system "git", "init", "-q"

  # "git remote add" will fail if the remote is defined in the global config
  system "git", "config", "remote.origin.url", BREW_REPO
  system "git", "config", "remote.origin.fetch", "+refs/heads/*:refs/remotes/origin/*"

  # ensure we don't munge line endings on checkout
  system "git", "config", "core.autocrlf", "false"

  system "git", "fetch", "origin", "master:refs/remotes/origin/master",
         "--tags", "--force"

  system "git", "reset", "--hard", "origin/master"

  system "ln", "-sf", "#{HOMEBREW_REPOSITORY}/bin/brew", "#{HOMEBREW_PREFIX}/bin/brew"

  # system "#{HOMEBREW_PREFIX}/bin/brew", "update", "--force"
end

warn "#{HOMEBREW_PREFIX}/bin is not in your PATH." unless ENV["PATH"].split(":").include? "#{HOMEBREW_PREFIX}/bin"

ohai "Installation successful!"
puts

# Use the shell's audible bell.
print "\a"

# Use an extra newline and bold to avoid this being missed.
ohai "Homebrew has enabled anonymous aggregate formulae and cask analytics."
puts <<-EOS
#{Tty.bold}Read the analytics documentation (and how to opt-out) here:
  #{Tty.underline}https://docs.brew.sh/Analytics#{Tty.reset}

EOS

ohai "Homebrew is run entirely by unpaid volunteers. Please consider donating:"
puts <<-EOS
  #{Tty.underline}https://github.com/Homebrew/brew#donations#{Tty.reset}
EOS

Dir.chdir HOMEBREW_REPOSITORY do
  system "git", "config", "--local", "--replace-all", "homebrew.analyticsmessage", "true"
  system "git", "config", "--local", "--replace-all", "homebrew.caskanalyticsmessage", "true"
end

ohai "Next steps:"
puts "- Run `brew help` to get started"
puts "- Further documentation: "
puts "    #{Tty.underline}https://docs.brew.sh#{Tty.reset}"

```

But that didn't work, we still couldn't run `which brew` successfully without getting a command not found error.

Then we used the alternative installation described on the web page https://docs.brew.sh/Installation, where we cd'd into `/usr/local/` and then ran the command for the alternative command as suggested on the web page `mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/masteUnity:local rodrigomunoz$ mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew`

That did the trick! Now I could run `which brew` and `brew help` and more importantly `brew doctor`. However there was still some problem with the path, 

```Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
```

so I ran the suggested command `cho 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile` and sourced the bash profile file. That finally gave us the long lost answer we wanted `Your system is ready to brew.`

Finally! =))

**Comment by rmzse** [comment]
Just to clarify, the final command without a typo should be
`echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile` 
with an `e` in the `echo`.
