### ISSUE TITLE
MoltenVK checklist

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#36901]
In order to ship MoltenVK with system libs we need:
- [x] cereal, already in core
- [x] glslang, already in core.
- [x] vulkan-headers, [merged](https://github.com/Homebrew/homebrew-core/commit/6a870a788482465adcd2d1150e9f0a9def3674b1)
- [ ] vulkan-portability, #36903
- [ ] vulkan-tools
- [ ] vulkan-samples
- [ ] spirv-cross, #36875
- [ ] spirv-tools

**Comment by fxcoudert** [comment]
We'll happy review PRs for each formula, but we don't keep track of feature requests in issues. Closing accordingly.

**Comment by rafaga** [comment]
i made a tap with formulas for SPIRV-Cross, SPIRV-Tools, Vulkan-Headers, Vulkan-Portability, the correct revision of GLSlang to build MoltenVK. We can Join Efforts to make MoltenVK available in Homebrew

**Comment by yurikoles** [comment]
@rafaga https://github.com/KhronosGroup/MoltenVK/issues/509
