### ISSUE TITLE
Add --locked flag to Rust formulae with a Cargo.lock file

### ISSUE THREAD

**Issue by samford** [Homebrew/homebrew-core#46025]
The related PR that brought attention to this issue (#45839) is now merged and less visible, so I wanted to create an issue to continue any discussion around the `--locked` flag, track progress on related formulae updates, and to have something that people can see and reference.

The general idea here is that Rust formulae typically use `cargo install` to build/install but haven't been using the `--locked` flag, so builds aren't reproducible and can eventually fail over time if a dependency adds a breaking change in a newer version.  In contrast to `cargo build`, by default `cargo install` uses the latest dependencies in the build rather than the ones found in `Cargo.lock`.  Adding the `--locked` flag makes `cargo install` use the dependency versions in the `Cargo.lock` file, which is generally what you would expect when you're trying to build a binary of a specific version/revision of a project.

I threw together a little script that goes through the formulae and identifies which have the `--locked` flag already and which still potentially need it.  I've created lists of the formulae 1) with no `Cargo.lock` file, 2) with a `Cargo.lock` file now added to the repo but not yet in a release, 3) with a `Cargo.lock` file but no `--locked` flag, and 4) with a `Cargo.lock` file and the `--locked` flag (i.e., finished).

Feel free to mention this issue in any related PR, as I'll be trying to keep this relatively up to date to track progress.

## Does Not Have `Cargo.lock`
- [ ] dssim.rb (open issue: kornelski/dssim#59)
- [ ] pngquant.rb (open issue: kornelski/pngquant#347)

## `Cargo.lock` Added but Not Yet in a Release
- [x] shellharden.rb (PR: #46159, closed issue: anordal/shellharden#28)
- [ ] svgcleaner.rb (open issue: RazrFalcon/svgcleaner#157)

## Has `Cargo.lock` and Needs `--locked` Flag
- [ ] git-series.rb (closed PR: #46176 ----- Build fails due to errors that are fixed in upstream master but not yet in a release; `--locked` flag will be added in the next release after 0.9.1)
- [ ] rust.rb (Rust and Racer have lock files but not Cargo)

## Has `Cargo.lock` and `--locked` Flag
- [x] angle-grinder.rb (PR: #46148)
- [x] badtouch.rb (PR: #46182)
- [x] bat.rb (PR: #46134)
- [x] boringtun.rb (PR: #46183)
- [x] broot.rb (PR: #46184)
- [x] click.rb (PR: #46185)
- [x] cmdshelf.rb (PR: #46186)
- [x] deno.rb (PR: #45914)
- [x] diffr.rb (PR: #46187)
- [x] diskus.rb (PR: #46188)
- [x] dust.rb (PR: #46189)
- [x] fastmod.rb (PR: #46190)
- [x] fd.rb (PR: #46135)
- [x] ffsend.rb (PR: #46139)
- [x] fselect.rb (PR: #46624, closed issue: jhspetersson/fselect#61)
- [x] geckodriver.rb (PR: #45906)
- [x] genact.rb (PR: #46141)
- [x] gifski.rb (PR: #46173)
- [x] git-absorb.rb (PR: #46174)
- [x] git-delta.rb (PR: #46175)
- [x] gleam.rb (PR: #46177)
- [x] grin.rb (PR: #45946)
- [x] grin-wallet.rb (PR: #45833)
- [x] hexyl.rb (PR: #46138)
- [x] hyperfine.rb (PR: #46075)
- [x] interactive-rebase-tool.rb (PR: #46178)
- [x] just.rb (PR: #46179)
- [x] ktmpl.rb (PR: #46180)
- [x] loc.rb (PR: #46181)
- [x] lsd.rb (PR: #46142)
- [x] mdbook.rb (PR: #46144)
- [x] mdcat.rb (PR: #46171)
- [x] miniserve.rb (PR: #46172)
- [x] nushell.rb (PR: #46505)
- [x] onefetch.rb (PR: #45878)
- [x] oxipng.rb (PR: #46164)
- [x] pastel.rb (PR: #46165)
- [x] pijul.rb (PR: #46073)
- [x] procs.rb (PR: #46166)
- [x] rargs.rb (PR: #46167)
- [x] rbspy.rb (PR: #46168)
- [x] ripgrep.rb (PR: #46133)
- [x] ripgrep-all.rb (PR: #46169)
- [x] rustup-init.rb (PR: #46170)
- [x] sccache.rb (PR: #46156)
- [x] sd.rb (PR: #46157)
- [x] shadowenv.rb (PR: #46158)
- [x] sk.rb (PR: #46160)
- [x] sn0int.rb (PR: #46161)
- [x] ssh-permit-a38.rb (PR: #46162)
- [x] starship.rb (PR: #46140)
- [x] tealdeer.rb (PR: #46079)
- [x] tectonic.rb (PR: #46149)
- [x] toast.rb (PR: #46150)
- [x] tokei.rb (PR: #46151)
- [x] topgrade.rb (PR: #46152)
- [x] wagyu.rb (PR: #46153)
- [x] watchexec.rb (PR: #46154)
- [x] websocat.rb (PR: #46155)
- [x] xsv.rb (PR: #46137)
- [x] zola.rb (PR: #45839)

**Comment by samford** [comment]
On to questions and comments.

When updating these formulae, if there isn't a new version available to bump the version at the same time, should we bump the revision?  That is to say, if we want the bottles to be rebuilt (using the `--locked` flag) and for users to get an updated binary, does that require bumping the revision?  Once this is answered, I can start going through the list in my free time to tackle some of these formulae changes.

I saw that the `formula_creator.rb` file was updated (Homebrew/brew#6664), so the default `cargo install` command now contains the `--locked` flag.  The following files in the Homebrew/brew repo may still need to be modified as well:

* [/Library/Homebrew/rubocops/text.rb](https://github.com/Homebrew/brew/blob/2963bbec91aa0fdde145d7bf788da54c0bf792f4/Library/Homebrew/rubocops/text.rb#L62)
* [/Library/Homebrew/test/rubocops/text_spec.rb](https://github.com/Homebrew/brew/blob/2963bbec91aa0fdde145d7bf788da54c0bf792f4/Library/Homebrew/test/rubocops/text_spec.rb#L213)

Per the previous discussion (in the aforementioned PR), it may be necessary to create an audit for the `--locked` flag (when `cargo install` is used to build/install).  Just to be clear, I don't know enough about Homebrew's internals to take care of this, so this is something that someone else will have to tackle.

In general, if anyone has any additional comments/guidelines on how this should be tackled, please do let me know.

**Comment by fxcoudert** [comment]
> When updating these formulae, if there isn't a new version available to bump the version at the same time, should we bump the revision?

Probably no. As the formulas are currently working, we don't want to force the new binaries on all users, so no revision bump.

**Comment by samford** [comment]
Out of curiosity, are new bottles published after a formula modification without a revision bump?  That is, if a user newly installs a formula after the `--locked` flag has been added, will they receive a bottle that was built with the `--locked` flag present?

Besides the demonstrated issue with broken builds over time, my other concern was that without the `--locked` flag, the bottle may contain a binary that was built using newer crate versions (compared to what's in the lock file).  In that case, the build may succeed without errors and the binary may appear to work properly but it wouldn't be an accurate representation of what was intended for that version release.

I'll respect this decision regardless but I felt I would be remiss not to clarify this further.

**Comment by jonchang** [comment]
> Out of curiosity, are new bottles published after a formula modification without a revision bump? That is, if a user newly installs a formula after the `--locked` flag has been added, will they receive a bottle that was built with the `--locked` flag present?

This is possible; you can tell because the formulae will have `rebuild 1` or similar in bottle blocks.

**Comment by fxcoudert** [comment]
Bottles are systematically rebuilt as part of testing a pull request. Whether the new bottles are published depends on the maintainer's choice when merging, whether they decided to pull the bottles as well during the merge… we almost always do.

**Comment by chenrui333** [comment]
Besides `nushell.rb` (which currently builds on top of beta rust release) and `rust.rb`, I think every rust formula which has `cargo.lock` have been addressed.

cc @samford @fxcoudert

**Comment by fxcoudert** [comment]
Thanks to everyone involved!
