### ISSUE TITLE
Broken bottles and conflicts discovered in Python 3.8 CI builds

### ISSUE THREAD

**Issue by Bo98** [Homebrew/homebrew-core#46728]
The following formulae had issues when installed from bottles in CI builds 51635, 51811 and/or 52341 (handling Python 3.8 pull request #45337). The issues were not caused by the pull request (they weren't rebuilt) and I've been able to reproduce them locally.

---

- [ ] **abyss** - test failure - bcgsc/abyss#305
<details>
<summary>Log</summary>

```
curl: (22) The requested URL returned error: 404 Not Found
Error: abyss: failed
An exception occurred within a child process:
  DownloadError: Failed to download resource "abyss--testdata"
Download failed: http://www.bcgsc.ca/platform/bioinfo/software/abyss/releases/1.3.4/test-data.tar.gz
```
</details>

- [x] **arx-libertatis** - conflict with **arx** - #46716
<details>
<summary>Log</summary>

```
/usr/local/bin/arx -> /usr/local/Cellar/arx/0.3.2/bin/arx
```
</details>

- [ ] **bazelisk** - test failure (High Sierra only) - #46983
<details>
<summary>Log</summary>

```
==> /usr/local/Cellar/bazelisk/1.1.0/bin/bazelisk version
2019/11/23 11:32:45 Downloading https://releases.bazel.build/1.2.0/release/bazel-1.2.0-darwin-x86_64...
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /private/tmp/bazelisk-test-20191123-51820-dtwwzg/Library/Caches/bazelisk/bin/bazelbuild/bazel-1.2.0-darwin-x86_64 (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /private/tmp/bazelisk-test-20191123-51820-dtwwzg/Library/Caches/bazelisk/bin/bazelbuild/bazel-1.2.0-darwin-x86_64 (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Error: bazelisk: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<255>.
```
</details>

- [x] **bullet** - test failure (Xcode 11 only) - #46652 
<details>
<summary>Log</summary>

```
/usr/local/Cellar/bullet/2.88/include/bullet/LinearMath/btVector3.h:335:7: error: argument value 10880 is outside the valid range [0, 255] [-Wargument-outside-range]
                y = bt_splat_ps(y, 0x80);
                    ^~~~~~~~~~~~~~~~~~~~
```
</details>

- [x] **caf** - conflict with **bro** - #46735
<details>
<summary>Log</summary>

```
(all caf headers and...)
/usr/local/lib/libcaf_core.dylib -> /usr/local/Cellar/bro/2.6.4/lib/libcaf_core.dylib
/usr/local/lib/libcaf_io.dylib -> /usr/local/Cellar/bro/2.6.4/lib/libcaf_io.dylib
```
</details>

- [x] **cminpack** - broken linkage (Mojave and later only) - #46792
<details>
<summary>Log</summary>

```
Missing libraries:
  /tmp/cminpack-20191018-2847-vn5z4b/cminpack-1.3.6/libcminpack.1.dylib
```
</details>

- [x] **cucumber-cpp** - test failure (Mojave only, looks like a system header issue like with GCC and Git - maybe I should start a general issue about that?) - #47035
<details>
<summary>Log</summary>

```
ERROR:  Error installing cucumber:
	ERROR: Failed to build gem native extension.

    current directory: /private/tmp/cucumber-cpp-test-20191111-99460-loabuk/gems/google-protobuf-3.8.0/ext/google/protobuf_c
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20191111-99468-h9ou1c.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h
```
</details>

- [x] **google-benchmark** - conflict with **ampl-mp** - #46808
<details>
<summary>Log</summary>

```
/usr/local/include/benchmark/benchmark.h -> /usr/local/Cellar/ampl-mp/3.1.0_2/include/benchmark/benchmark.h
```
</details>

- [x] **googler** - test failure - jarun/googler#306, #47234
<details>
<summary>Log</summary>

```
==> /usr/local/Cellar/googler/3.9/bin/googler --noprompt Homebrew
No results.
Error: googler: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </Homebrew/> was expected to be =~
<"">.
```
</details>

- [x] **hana** - conflict with **boost** - #46711
<details>
<summary>Log</summary>

```
(total conflict - boost contains hana)
```
</details>

- [ ] **hatari** - test failure (High Sierra only)
<details>
<summary>Log</summary>

```
==> /usr/local/Cellar/hatari/2.2.1/bin/hatari -v
Error: hatari: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <1> expected but was
<nil>.
```
</details>

- [x] **infer** - test failure - #47007
<details>
<summary>Log</summary>

```
==> /usr/local/Cellar/infer/0.15.0/bin/infer --fail-on-issue -- javac FailingTest.java
Capturing in javac mode...
Found 1 source file to analyze in /private/tmp/infer-test-20191112-11175-10ouv0u/infer-out
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

FInternal Error: Error in infer subprocess: died after receiving sigsegv (signal number 11)
```
</details>

- [x] **libchaos** - test failure - #46738
<details>
<summary>Log</summary>

```
==> /usr/bin/clang++ -std=c++11 -lchaos -o t_libchaos t_libchaos.cc
ld: library not found for -lchaos
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: libchaos: failed
```
</details>

- [x] **libevhtp** - broken linkage and test failure - #46755
<details>
<summary>Log</summary>

```
Broken dependencies:
  /usr/local/opt/oniguruma/lib/libonig.5.dylib (oniguruma)
```
```
==> /usr/bin/clang test.c -I/usr/local/Cellar/libevhtp/1.2.18_2/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/libevent/include -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/libevent/lib -L/usr/local/Cellar/libevhtp/1.2.18_2/lib -levhtp -levent -levent_openssl -lssl -lcrypto -o test
In file included from test.c:1:
In file included from /usr/local/Cellar/libevhtp/1.2.18_2/include/evhtp.h:9:
In file included from /usr/local/Cellar/libevhtp/1.2.18_2/include/evhtp/evhtp.h:5:
/usr/local/Cellar/libevhtp/1.2.18_2/include/evhtp/config.h:48:10: fatal error: 'onigposix.h' file not found
#include <onigposix.h>
         ^~~~~~~~~~~~~
1 error generated.
```
</details>

- [x] **libftdi** - broken linkage - #46792
<details>
<summary>Log</summary>

```
Missing libraries:
  /tmp/libftdi-20190914-23127-9yk8o8/libftdi1-1.4/libftdi-build/src/libftdi1.2.dylib
```
</details>

- [x] **libgraphqlparser** - broken linkage (Mojave and later only) - #46792
<details>
<summary>Log</summary>

```
Missing libraries:
  /tmp/libgraphqlparser-20180821-11545-v1nemv/libgraphqlparser-0.7.0/libgraphqlparser.dylib
```
</details>

- [x] **llvm@4** - test failure (Catalina only) - #46801
<details>
<summary>Log</summary>

```
==> /usr/local/Cellar/llvm@4/4.0.1_1/bin/clang++ -v -nostdinc -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/include -I/usr/include test.cpp -o testCLT++
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /usr/local/Cellar/llvm@4/4.0.1_1/bin
 "/usr/local/Cellar/llvm@4/4.0.1_1/bin/clang-4.0" -cc1 -triple x86_64-apple-macosx10.15.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 409.12 -v -dwarf-column-info -debugger-tuning=lldb -nostdsysteminc -nobuiltininc -resource-dir /usr/local/Cellar/llvm@4/4.0.1_1/bin/../lib/clang/4.0.1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I /Library/Developer/CommandLineTools/usr/include/c++/v1 -I /include -I /usr/include -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -stdlib=libc++ -fdeprecated-macro -fdebug-compilation-dir /private/tmp/llvm@4-test-20191112-2104-1yoiibq -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.15.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -o /private/tmp/test-bfcebb.o -x c++ test.cpp
clang -cc1 version 4.0.1 based upon LLVM 4.0.1 default target x86_64-apple-darwin19.0.0
ignoring nonexistent directory "/include"
ignoring nonexistent directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /Library/Developer/CommandLineTools/usr/include/c++/v1
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include
End of search list.
In file included from test.cpp:1:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/iostream:38:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/ios:215:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:96:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:119:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/wchar.h:89:10: fatal error: 'stdarg.h' file not found
#include <stdarg.h>
         ^~~~~~~~~~
1 error generated.
```
</details>

- [x] **mariadb** - conflict with **groonga** - #46713
<details>
<summary>Log</summary>

```
/usr/local/share/groonga/COPYING -> /usr/local/Cellar/groonga/9.0.8/share/groonga/COPYING
```
</details>

- [x] **mariadb** - test failure - Homebrew/brew#6744
<details>
<summary>Log</summary>

```
  Test::Unit::AssertionFailedError: Failed to find /usr/local/etc/my.cnf.d/.homebrew_dont_prune_me!.
```
</details>

- [x] **mysql** - conflict with **protobuf** - #46682
<details>
<summary>Log</summary>

```
/usr/local/lib/libprotobuf-lite.dylib -> /usr/local/Cellar/protobuf/3.10.0_1/lib/libprotobuf-lite.dylib
/usr/local/lib/libprotobuf.dylib -> /usr/local/Cellar/protobuf/3.10.0_1/lib/libprotobuf.dylib
```
</details>

- [ ] **octomap** - broken linkage - OctoMap/octomap#262
<details>
<summary>Log</summary>

```
Missing libraries:
  /tmp/octomap-20180822-74275-1lz3o12/octomap-1.9.0/octomap/lib/liboctomath.1.9.dylib
```
</details>

- [x] **percona-server** - conflict with **percona-xtrabackup** (conflict already denoted the other way round) - #46796
<details>
<summary>Log</summary>

```
Linking /usr/local/Cellar/percona-server/8.0.17-8... Error: Could not symlink lib/plugin/keyring_vault.so
Target /usr/local/lib/plugin/keyring_vault.so
is a symlink belonging to percona-xtrabackup.
```
</details>

- [x] **pgbouncer** - broken linkage and test failure - #47132
<details>
<summary>Log</summary>

```
Broken dependencies:
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)
```
```
==> /usr/local/Cellar/pgbouncer/1.10.0_1/bin/pgbouncer -V
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/pgbouncer/1.10.0_1/bin/pgbouncer
  Reason: image not found
```
</details>

- [x] **sleuthkit** - conflict with **libusbmuxd** - libimobiledevice/libusbmuxd#84, #47230
<details>
<summary>Log</summary>

```
/usr/local/bin/icat -> /usr/local/Cellar/libusbmuxd/2.0.0_1/bin/icat
```
</details>

- [x] **sparkey** - conflict with **bench** - #46799
<details>
<summary>Log</summary>

```
/usr/local/bin/bench -> /usr/local/Cellar/bench/1.0.12/bin/bench
```
</details>

- [x] **sphinx** - conflict with **manticoresearch** (conflict already denoted the other way round) - #46800
<details>
<summary>Log</summary>

```
/usr/local/bin/indexer -> /usr/local/Cellar/manticoresearch/3.2.0/bin/indexer
/usr/local/bin/indextool -> /usr/local/Cellar/manticoresearch/3.2.0/bin/indextool
/usr/local/bin/searchd -> /usr/local/Cellar/manticoresearch/3.2.0/bin/searchd
/usr/local/bin/spelldump -> /usr/local/Cellar/manticoresearch/3.2.0/bin/spelldump
/usr/local/bin/wordbreaker -> /usr/local/Cellar/manticoresearch/3.2.0/bin/wordbreaker
```
</details>

- [x] **transmission-cli** - broken linkage and test failure - #47135
<details>
<summary>Log</summary>

```
Broken dependencies:
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)
```
```
==> /usr/local/Cellar/transmission-cli/2.94_1/bin/transmission-create -o /private/tmp/transmission-cli-test-20191124-28787-3tgw3c/test.mp3.torrent /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/test.mp3
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/transmission-cli/2.94_1/bin/transmission-create
  Reason: image not found
```
</details>

- [x] **ttyd** - broken linkage and test failure - #47133
<details>
<summary>Log</summary>

```
Broken dependencies:
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)
```
```
==> /usr/local/Cellar/ttyd/1.5.2_2/bin/ttyd --version
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/ttyd/1.5.2_2/bin/ttyd
  Reason: image not found
```
</details>

- [x] **urbit** - broken linkage and test failure - #47134
<details>
<summary>Log</summary>

```
Broken dependencies:
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)
```
```
==> /usr/local/Cellar/urbit/0.7.4/bin/urbit 2>&1
sh: line 1: 48762 Abort trap: 6           /usr/local/Cellar/urbit/0.7.4/bin/urbit 2>&1
Error: urbit: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <1> expected but was
<134>.
```
</details>

- [x] **vit** - test failure - #47238
<details>
<summary>Log</summary>

```
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <#<Pathname:/private/tmp/vit-test-20191123-61454-1u0bvoo/.task>>.exist? is true value expected but was
<false>
```
</details>

---

Needs further investigation:
* **dafny** - test failure on the second attempt onwards - probably a CI issue
```
==> /usr/local/Cellar/dafny/2.3.0/bin/dafny /private/tmp/dafny-test-20191115-19409-1kd33ep/test.dfy
04:37:55 /usr/local/Cellar/dafny/2.3.0/bin/dafny: line 2: mono: command not found
```
* **grafana** - occasional test timeout error
* ~~**mrboom** test hangs on High Sierra CI node - should be tested locally on High Sierra to see if it's CI specific~~ - #47004
* **opentsdb** - flaky test failure
* ~~**ungit** - test failure~~ - #47057

(alure and dromeaudio also had test failures but they seem to be CI specific because they were to do with audio)

As a FYI, on the second pass onwards the CI also occasionally forgets to unlink in certain scenarios:
```
==> brew install --only-dependencies fluent-bit
==> FAILED
Error: Cannot install fluent-bit because conflicting formulae are installed.
  mbedtls: because fluent-bit includes mbedtls libraries.
  msgpack: because fluent-bit includes msgpack libraries.
```

To reproduce those in the above list: `brew install <formula>` then `brew linkage --test <formula>` or `brew test <formula>` where relevant.

---

I've already looked into a few and will do some more on (likely) Friday.

Tick represents the issue being fixed and the pull request merged.

**Comment by fxcoudert** [comment]
Re. linkage audit failures with paths inside the same formula (and in the temp directory), like `octomap libftdi libgraphqlparser cminpack`: ideally we'd like to fix them, but sometimes the build system does not make it easy for us to specify a rpath for the library. As long as the software runs/the test is fine, we do not consider them blocking. It's a sort of “semi false positive”.

**Comment by Bo98** [comment]
For the sake of completion: caffe test is currently failing due to an upstream issue. BVLC/caffe#6864

Nothing needs to be done on the Homebrew side. It'll start working again soon.

**Comment by Bo98** [comment]
@fxcoudert It's mostly because their CMake scripts don't actually install everything and Homebrew then does a plain copy: https://github.com/Homebrew/homebrew-core/blob/4fb503e14e98bf56095a63e0905b9c4a7797a746/Formula/libgraphqlparser.rb#L22

While a CMake install would have ran `install_name_tool`.

**Comment by Bo98** [comment]
Actually, turns around you can workaround it with `-DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE`.

```
$ brew linkage libgraphqlparser
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
Homebrew libraries:
  /usr/local/Cellar/libgraphqlparser/0.7.0/lib/libgraphqlparser.dylib (libgraphqlparser)
```

**Comment by Amar1729** [comment]
re: `infer` test failure - I think `infer 0.15.0` actually may not build properly on Mojave or newer, resulting in internal errors when you try to run it. i'll @jvillard , a maintainer, so he knows about it, but it's possible 0.15.0 may have to be removed from core.

**Comment by bayandin** [comment]
> llvm@4 - test failure (Catalina only):

I have workarounded it by switching `ispc` (the only depended on `llvm@4` formulae) to latest `llvm` https://github.com/Homebrew/homebrew-core/pull/46789

**Comment by jvillard** [comment]
> re: `infer` test failure - I think `infer 0.15.0` actually may not build properly on Mojave or newer, resulting in internal errors when you try to run it. i'll @jvillard , a maintainer, so he knows about it, but it's possible 0.15.0 may have to be removed from core.

Possibly related to https://github.com/facebook/infer/issues/1081#issuecomment-487512452, but 0.15.0 is very old now so probably not worth keeping around.

**Comment by Bo98** [comment]
It's not without reason that it's 0.15.0.
An attempt to update to 0.17.0 failed: #42965.
This is following 3 failed attempts to update to 0.16.0: #35980, #39190, #40039.

I can revisit it myself if you think it should work - I've not looked into it.

**Comment by Amar1729** [comment]
@Bo98 the update to infer >= 0.16.0 is a pain mostly because of the update to opam 2.0, which we could never get building in homebrew core without the `x11` dependency. As a result, I'm currently providing infer 0.17.0 at [amar1729/homebrew-infer](https://github.com/amar1729/homebrew-infer) for Mojave, and I just version-pinned core's current 0.15.0 to it.

I don't know that my tap is very scalable though, because I haven't yet been able to set up CI builds of it (tried travis and azure) so I can only provide bottles for whatever macOS version i'm running.

**Comment by Bo98** [comment]
Had a look at infer. Homebrew/brew#5153 (unfortunately closed as stale) is a blocker on that continuing.

camlidl uses `cpp` internally and it's not really easy to bypass that, unless someone knows how to patch a Makefile during the `opam install` process. Disabling superenv is not an acceptable solution.

**Comment by Bo98** [comment]
Managed to fix the above issue in Homebrew/brew#6749.

I got Infer building fine on Java 8, just some linking issues I need to solve - I'm trying a build with a possible fix just now.

Java 10+ does not work due to an upstream issue with a dependency: antoinemine/apron#21. I've temporarily pinned the required Java to Java 8 but I'd really like not to.

If I get the linkage issues fixed, I'll open a pull request once the `cpp` shim issue is fixed to try it out on the CI.

**Comment by Bo98** [comment]
Infer pull request is a go: #47007.

I've changed a lot, and there might be more to change based on feedback. The previous build system was clearly in an unmaintainable state so I've had to make changes.

I also need to hope it works on Catalina and High Sierra. I've only tested it locally on Mojave.

**Comment by Bo98** [comment]
And we're down to one. Octomap requires a patch to fix the issue - a patch I submitted a week ago (OctoMap/octomap#262) but it hasn't had any response.

@fxcoudert Should we pull in the patch or wait and ignore the issue for now?

**Comment by fxcoudert** [comment]
@Bo98 if it's not blocking, just a linkage audit, ignore for now

**Comment by Bo98** [comment]
Cool, fine by me.

**Comment by fxcoudert** [comment]
octomap was the last one, and it was fixed in 06530b594db8c70b5ae2dfba00d6eb8736a67313
