### ISSUE TITLE
[epic] Remove GOPATH for go modules formula

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-core#47627]
Historically, golang builds need to happen under the GOPATH, as more and more formula has moved to go-modules, we can deprecate the GOPATH usage.

**Comment by jonchang** [comment]
Looks like there are 291 formula that still use GOPATH.

```console
$ rg -lF 'ENV["GOPATH"] = buildpath' | sort
acmetool.rb
ahoy.rb
akamai.rb
algernon.rb
aliyun-cli.rb
alp.rb
amazon-ecs-cli.rb
annie.rb
antibody.rb
anycable-go.rb
apache-brooklyn-cli.rb
apm-server.rb
aptly.rb
armor.rb
assh.rb
atlantis.rb
auditbeat.rb
aurora.rb
aws-es-proxy.rb
aws-iam-authenticator.rb
aws-okta.rb
benthos.rb
bettercap.rb
bitrise.rb
borg.rb
buildkit.rb
c14-cli.rb
calicoctl.rb
carina.rb
cayley.rb
certstrap.rb
cf-tool.rb
cfssl.rb
chamber.rb
charm.rb
chronograf.rb
cig.rb
circleci.rb
cli53.rb
clipper.rb
cointop.rb
collector-sidecar.rb
consul-backinator.rb
consul-template.rb
consul.rb
container-diff.rb
convox.rb
corectl.rb
cql.rb
ctop.rb
cwlogs.rb
dashing.rb
dcos-cli.rb
dehydrated.rb
deis.rb
deisctl.rb
dep.rb
devd.rb
devspace.rb
direnv.rb
dive.rb
dlite.rb
dnscontrol.rb
dnscrypt-proxy.rb
docker-credential-helper-ecr.rb
docker-credential-helper.rb
docker-gen.rb
docker-ls.rb
docker-machine-driver-hyperkit.rb
docker-machine-driver-vmware.rb
docker-machine-driver-vultr.rb
docker-machine-parallels.rb
docker-machine.rb
docker-swarm.rb
docker.rb
docker2aci.rb
dockerize.rb
dockviz.rb
dockward.rb
doctl.rb
drone-cli.rb
dvm.rb
elvish.rb
emp.rb
envconsul.rb
etcd.rb
exercism.rb
faas-cli.rb
fabio.rb
filebeat.rb
fleetctl.rb
flint-checker.rb
fluxctl.rb
fn.rb
forego.rb
fork-cleaner.rb
fortio.rb
frpc.rb
frps.rb
frugal.rb
fsql.rb
gauge.rb
gdm.rb
gdrive.rb
geoipupdate.rb
ghr.rb
git-appraise.rb
git-sizer.rb
git-town.rb
github-markdown-toc.rb
github-release.rb
gitlab-runner.rb
glide.rb
glooctl.rb
go-bindata.rb
go-jira.rb
go-md2man.rb
go.rb
go@1.10.rb
go@1.11.rb
go@1.12.rb
go@1.9.rb
goad.rb
gobuster.rb
gocryptfs.rb
godep.rb
gofabric8.rb
gollum.rb
gomplate.rb
goose.rb
gopass.rb
gor.rb
goreman.rb
gost.rb
gotags.rb
govendor.rb
gowsdl.rb
gox.rb
grafana.rb
gron.rb
grv.rb
gx-go.rb
gx.rb
heartbeat.rb
helm.rb
helm@2.rb
helmsman.rb
hey.rb
hivemind.rb
hostess.rb
hub.rb
iamy.rb
immortal.rb
influxdb.rb
infrakit.rb
inlets.rb
ipfs.rb
iron-functions.rb
ironcli.rb
istioctl.rb
jabba.rb
jd.rb
jfrog-cli-go.rb
jid.rb
jp.rb
juju.rb
jump.rb
jvgrep.rb
k3d.rb
k6.rb
kapacitor.rb
karn.rb
kedge.rb
kompose.rb
kops.rb
kube-aws.rb
kubeaudit.rb
kubebuilder.rb
kubeless.rb
kubeprod.rb
kubernetes-cli.rb
kubernetes-service-catalog-client.rb
kyma-cli.rb
landscaper.rb
lean-cli.rb
leaps.rb
lego.rb
lf.rb
linkerd.rb
lxc.rb
mage.rb
mailhog.rb
massren.rb
megacmd.rb
metricbeat.rb
micro.rb
minio-mc.rb
minio.rb
mmark.rb
modd.rb
mpdviz.rb
nats-server.rb
nats-streaming-server.rb
node_exporter.rb
nomad.rb
nsq.rb
oauth2_proxy.rb
octant.rb
opa.rb
openshift-cli.rb
operator-sdk.rb
overmind.rb
packer.rb
path-extractor.rb
peco.rb
perkeep.rb
pgweb.rb
piknik.rb
pilosa.rb
prest.rb
protoc-gen-go.rb
prototool.rb
pulumi.rb
pumba.rb
pup.rb
qpm.rb
rack.rb
rancher-cli.rb
rancher-compose.rb
rke.rb
s-search.rb
scc.rb
scw.rb
serve.rb
shellz.rb
shfmt.rb
ship.rb
sift.rb
skaffold.rb
skopeo.rb
slackcat.rb
slacknimate.rb
smimesign.rb
snag.rb
snap-telemetry.rb
sonobuoy.rb
spaceinvaders-go.rb
srclib.rb
ssh-vault.rb
ssllabs-scan.rb
step.rb
stolon.rb
stout.rb
syncthing-inotify.rb
syncthing.rb
td.rb
teleconsole.rb
telegraf.rb
teleport.rb
termshare.rb
terraform-docs.rb
terraform-inventory.rb
terraform-provisioner-ansible.rb
terraform.rb
terraform@0.11.rb
terraformer.rb
terragrunt.rb
terrahelp.rb
textql.rb
the_platinum_searcher.rb
tj.rb
traefik.rb
traefik@1.rb
triangle.rb
ultralist.rb
uru.rb
vault.rb
vegeta.rb
velero.rb
vert.rb
virgil.rb
virustotal-cli.rb
vultr.rb
warp.rb
websocketd.rb
wego.rb
wellington.rb
wsk.rb
wskdeploy.rb
wu.rb
yq.rb
```

**Comment by alebcay** [comment]
While we're here - would it be worth standardizing some of the flags that we use for building Go formulae? Specifically, I would advocate for always including
- [`-ldflags "-s -w"`](https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/), unless it breaks build
- `-trimpath`: "remove all file system paths from the resulting executable. Instead of absolute file system paths, the recorded file names will begin with either "go" (for the standard library), or a module path@version (when using modules), or a plain import path (when using `GOPATH`)."

**Comment by jonchang** [comment]
It looks like [Debian sets `-trimpath` but doesn't strip binaries with `-s -w`](https://salsa.debian.org/go-team/packages/dh-golang/blob/04ec6d4878296ede1203e5f87f7f955492a11c50/lib/Debian/Debhelper/Buildsystem/golang.pm#L539-540).

**Comment by alebcay** [comment]
> Would it be useful to add something like std_go_args (like we have for CMake builds)?

I think it would be useful. I've already seen some formulae floating around with stripped binaries, which is why I've brought this up. From my limited testing with the PRs above, there's a reduction of 15-20% in total formula size. I personally don't think it would be a bad idea to strip binaries, seeing as Go binaries are all statically linked.

**Comment by SMillerDev** [comment]
Maybe you want to wait @chenrui333 and do gopath at the same time as the `go_std_args`?

**Comment by chenrui333** [comment]
> Would it be useful to add something like std_go_args (like we have for CMake builds)?

+1 for `std_go_args` idea.

**Comment by FiloSottile** [comment]
You can use the GOFLAGS environment variable to always set `-trimpath`. I'd recommend against stripping DWARF, as people might want to use a debugger or a profiler on their binaries.

**Comment by SMillerDev** [comment]
That's not what's suggested here, this is about `GOPATH`

**Comment by chenrui333** [comment]
checkin, will add some more time to this issue.

**Comment by chenrui333** [comment]
checkin, give some more time for this issue.

**Comment by carlocab** [comment]
Looks like many of failures in go1.16 (#71289) need fixing by removing `GOPATH`. These are the formula that have failed to build on both Mojave and Catalina:

- [ ] ahoy
- [ ] akamai
- [ ] amazon-ecs-cli
- [ ] apache-brooklyn-cli
- [ ] aptly
- [ ] assh
- [ ] bitrise
- [ ] buildifier
- [ ] buildozer
- [ ] caddy
- [ ] carina
- [ ] cartridge-cli
- [ ] ccat
- [ ] cf-tool
- [ ] charm
- [ ] collector-sidecar
- [ ] confd
- [ ] cql
- [ ] cwlogs
- [ ] devd
- [ ] docker-credential-helper
- [ ] docker-gen
- [ ] docker-machine-driver-hyperkit
- [ ] docker-machine-driver-vmware
- [ ] docker-machine-driver-vultr
- [ ] dockerize
- [ ] dockviz
- [ ] dockward
- [ ] dvm
- [ ] emp
- [ ] envoy
- [ ] flint-checker
- [ ] fsql
- [ ] gdm
- [ ] gdrive
- [ ] git-appraise
- [ ] git-sizer
- [ ] github-release
- [ ] gollum
- [ ] gotags
- [ ] gx-go
- [ ] hivemind
- [ ] httpdiff
- [ ] ironcli
- [ ] jabba
- [ ] jp
- [ ] jsonpp
- [ ] kedge
- [ ] ko
- [ ] launch_socket_server
- [ ] leaps
- [ ] lunchy-go
- [ ] mailhog
- [ ] massren
- [ ] microplane
- [ ] modd
- [ ] mpdviz
- [ ] path-extractor
- [ ] pgweb
- [ ] piknik
- [ ] pup
- [ ] qpm
- [ ] rack
- [ ] s-search
- [ ] shellz
- [ ] sift
- [ ] snag
- [ ] snap-telemetry
- [ ] spaceinvaders-go
- [ ] ssh-vault
- [ ] stout
- [ ] sync_gateway
- [ ] td
- [ ] teleconsole
- [ ] termshare
- [ ] terraform-inventory
- [ ] textql
- [ ] traefik@1
- [ ] uru
- [ ] vert
- [ ] vultr
- [ ] wego

**Comment by chenrui333** [comment]
it is also a huge opportunity to disable/remove go formulae now.

**Comment by nklmilojevic** [comment]
I have started from the bottom of the list, for now `wego`, `vert` and `uru` don't have go modules in their repos.

**Comment by SMillerDev** [comment]
Could you make sure to make an upstream issue for those (mentioning that this will break go 1.16 compatibility) and link them here? That way we can keep track of the status.

**Comment by nklmilojevic** [comment]
^ Will do it one by one

**Comment by nklmilojevic** [comment]
@SMillerDev it seems that *all* of these formulas contain repos that don't have go.mod at all, so that is why there is GOPATH still there for install command. I think these formulas will have to update or keep depending on go@1.15.

**Comment by MikeMcQuaid** [comment]
> it is also a huge opportunity to disable/remove go formulae now.

Let's try and only do this for Go formulae that aren't widely used. Remember we're primarily a binary package manager for our users; it doesn't matter to them if we can't build from source.

**Comment by vvvvv** [comment]
regarding `mailhog`:  
[There is already a ticket](https://github.com/mailhog/MailHog/issues/339) but the maintainer seems to be pretty unresponsive as the last contribution is from jun 2020

**Comment by vvvvv** [comment]
regarding `termshare`:  
Last update was [7 years ago](https://github.com/progrium/termshare), maintainer doesn't answer issues or pr.  
The project seems to be pretty much dead so I'd suggest removing it.

**Comment by Bo98** [comment]
`GO111MODULE=auto` is probably an acceptable fix that can be done quite quickly for all of the above.

I'm quite happy 1.16 is making this change though. Formulae that's not built using Go modules have never been reproducible, and have had a history of breaking.

Going forward, we should probably not accept any new formula that uses `GO111MODULE=auto`, but that's a debate for later.

**Comment by vvvvv** [comment]
regarding `modd`:  
HEAD builds just fine as upstream already uses go modules in [master](https://github.com/cortesi/modd) not in the latest version.  
I don't know what to do in this case, just change the version to commit [8983974
](https://github.com/cortesi/modd/commit/8983974e54502110d67fcad1c82a989a9a3dc5d1) ?  
There's also already a ticket regarding arm support https://github.com/cortesi/modd/issues/95

**Comment by vvvvv** [comment]
regarding `mpdviz`:  
Last update was [7 years ago](https://github.com/lucy/mpdviz).  
Project seems to be dead.

**Comment by vvvvv** [comment]
regarding `path-extractor`:  
Project seems to be dead.  
@chenrui333 filed an issue [on 29 Jul 2020 noting the absence of any license](https://github.com/edi9999/path-extractor/issues/8) and maintainer didn't responde.

**Comment by Bo98** [comment]
For `path-extractor`, that is a valid reason to disable the formula. `disable! because: :no_license`.

**Comment by circa10a** [comment]
Ahoy hasn't been updated in years: https://github.com/ahoy-cli/ahoy/

**Comment by TimothyGu** [comment]
I see that people have started to add `GO111MODULE=auto` to a bunch of packages. However, according to https://blog.golang.org/go116-module-changes, that won't work in Go 1.17:

> We plan to drop support for GOPATH mode in Go 1.17. In other words, Go 1.17 will ignore `GO111MODULE`. If you have projects that do not build in module-aware mode, now is the time to migrate.

Instead of adding GO111MODULE everywhere, which is only a temporary band-aid, I think it would be better to properly convert formulae to not use GOPATH at all.

**Comment by Bo98** [comment]
> Instead of adding GO111MODULE everywhere, which is only a temporary band-aid, I think it would be better to properly convert formulae to not use GOPATH at all.

For pretty much all of the affected formulae, they don't use Go modules and only work in GOPATH. This requires upstream to release updates to correct.

`GO111MODULE` is a reasonable workaround so that Go 1.16 can ship this weekend. Otherwise, we're going to have to wait a lot longer while we wait for various updates from upstream.

Once Go 1.16 is shipped, we then have a known timeframe (until 1.17) for the affected formulae to be updated to use Go modules. If upstream do not issue an update, then we will disable those formulae, marking as unmaintained.

**Comment by roopakv** [comment]
@Bo98 would you be able to update the comment https://github.com/Homebrew/homebrew-core/issues/47627#issuecomment-780944517 to reflect the state of the world :) 

more of these have been opened/fixed and if I'm going to be honest I'm confusing myself 😂

**Comment by carlocab** [comment]
Whoops; I got it. Give me a few minutes.

**Comment by roopakv** [comment]
Is there any reason I shouldn't update all formulae and add `ENV["GO111MODULE"]` for all applicable formula in one PR? or at least group in ~5s or 10s?

Since we are not actually updating a release is that allowed?

**Comment by carlocab** [comment]
>or at least group in ~5s or 10s?

Something like this should be fine.

**Comment by roopakv** [comment]
@carlocab this look ok? https://github.com/Homebrew/homebrew-core/pull/71610

**Comment by carlocab** [comment]
Yes, that's fine. Thank you!

**Comment by roopakv** [comment]
All right! we are all done ( i think). We have PRs for all the tools listed in @carlocab's [comment](https://github.com/Homebrew/homebrew-core/issues/47627#issuecomment-780944517).

While we have filed issues with a LOT of the tools there I doubt that many of them will actually upgrade to go modules by the time go1.17 is out. Would the idea be to deprecate them or disable them or add a go1.16 formula when that time comes?

**Comment by Bo98** [comment]
Possibly both - we could deprecate as "unmaintained" if there is no response, but we'll let them depend on `go@1.16` for that deprecation period.

I'm very likely going to start tests with 1.17 RC1 when that lands rather than the final version so that we're better prepared.

**Comment by carlocab** [comment]
Thanks very much for all the help, @roopakv. There are still a handful of formulae that don't use `GOPATH` but nevertheless did not build with go1.16: https://github.com/Homebrew/homebrew-core/pull/71289#issuecomment-783077433

**Comment by alebcay** [comment]
### Upstream `HEAD` has module support but has not landed in a release
- [ ] ahoy
- [ ] apache-brooklyn-cli
- [ ] aptly
- [ ] devd
- [ ] dockerize
- [ ] goofys
- [ ] gx-go
- [ ] jabba
- [ ] modd
- [ ] pup
- [ ] textql

### Upstream is still not using modules yet
- [ ] amazon-ecs-cli
- [ ] ccat
- [ ] confd
- [ ] docker-machine-driver-vultr
- [ ] dockviz
- [ ] dockward
- [ ] emp (https://github.com/remind101/empire/issues/1167)
- [ ] flint-checker
- [ ] forego
- [ ] gdm
- [ ] github-release
- [ ] go-bindata
- [ ] jp
- [ ] launch_socket_server
- [ ] mailhog
- [ ] massren (https://github.com/laurent22/massren/issues/44)
- [ ] qpm
- [ ] rack
- [ ] sift
- [ ] snag
- [ ] termshare
- [ ] uru

### Upstream is still not using modules yet (deprecated/disabled)
- [ ] cf-tool
- [ ] corectl
- [ ] cosi
- [ ] cwlogs
- [ ] dep
- [ ] docker-machine-driver-hyperkit
- [ ] docker-machine-driver-xhyve
- [ ] docker-machine
- [ ] docker-swarm
- [ ] docker2aci
- [ ] fleetctl
- [ ] glide
- [ ] go@1.13
- [ ] go@1.14
- [ ] goad
- [ ] gofabric8
- [ ] govendor
- [ ] grv
- [ ] helm@2
- [ ] infrakit
- [ ] ironcli
- [ ] kedge
- [ ] landscaper
- [ ] mpdviz
- [ ] rancher-compose
- [ ] snap-telemetry
- [ ] stout
- [ ] teleconsole
- [ ] terraform@0.11
- [ ] vert

### Corner cases
- [ ] docker - upstream uses modules to manage a vendor folder but has no plans to move to a conventional Go modules setup
- [ ] gcsfuse - need a closer look; current approach involves deleting and maybe setting a custom `GOPATH`?
- [ ] kops - upstream supports modules but the Makefile seems to download the package from `k8s.io` at build time?
- [ ] operator-sdk - Makefile uses `GOBIN` to install binaries, but does not use `GOPATH`
- [ ] perkeep - upstream uses modules but their build system puts the binary in `GOPATH/bin` (i.e. in `HOMEBREW_CACHE/go_mod_cache/bin` if we don't set `GOPATH`)
- [ ] pulumi - Makefile downloads some prebuilt binaries?
- [ ] vault - Makefile downloads its own copy of Homebrew-provided stuff (e.g. gox)

**Comment by rahul3002** [comment]
I would like to contribute to this Project

**Comment by SMillerDev** [comment]
Go for it

**Comment by rahul3002** [comment]
can anyone guide me

**Comment by alebcay** [comment]
Hi @rahul3002, I encourage you to take a look at our [contributing guide](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) for info on how to contribute in this repository (Homebrew/homebrew-core), which stores formulae (packages) for Homebrew.

You may also be interested in contributing to the main `brew` repo (https://github.com/Homebrew/brew), which contains the code for the package manager itself. You can also refer to the [contributing guidelines for the `brew` repo](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) for info on how to contribute there.

You can also find more information relevant to contributing at [our docs site](https://docs.brew.sh/). I would ask that you to take further questions to [our Discussions forum](https://github.com/orgs/Homebrew/discussions), as this thread is dedicated to other purposes. Thanks for your interest!

**Comment by osalbahr** [comment]
I see that the "in progress" label was removed but this issue is still open and there is still a "help wanted" label. What does that mean?

**Comment by iMichka** [comment]
Not sure for the in progress label. Looking at it, we have been working on this since 2019 ... so progress has been slow. There are less than 50 formulae where GOPATH could be removed, so any help finishing this task is welcome.

**Comment by chenrui333** [comment]
Considering now we are at go 1.21, gonna use [gopath deprecation](https://github.com/Homebrew/homebrew-core/issues?q=label%3A%22gopath+deprecation%22) for further tracking or formulae deprecations.
