### ISSUE TITLE
HackIllinois 2020 formula upgrade issue tracker

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-core#50891]
- [ ] abook
- [x] abyss
- [ ] advancemenu
- [ ] adwaita-icon-theme
- [ ] agedu
- [x] aliyun-cli
- [x] amazon-ecs-cli
- [x] amqp-cpp
- [x] ansible
- [ ] aom
- [ ] aqbanking
- [x] arangodb
- [x] aravis
- [x] archi-steam-farm
- [x] arm-linux-gnueabihf-binutils
- [ ] arx-libertatis
- [x] astrometry-net
- [x] atk
- [ ] atkmm
- [x] auditbeat
- [ ] autopsy
- [x] awsume
- [x] babl
- [x] bacula-fd
- [x] bagit
- [x] bareos-client
- [x] bde
- [x] bear
- [x] bibtexconv
- [ ] bigloo
- [x] blazegraph
- [x] bluepill
- [x] bochs
- [x] bowtie2
- [x] bundletool
- [x] bzt
- [x] cacli
- [x] caddy
- [x] calabash
- [x] cartridge-cli
- [x] cassandra-reaper
- [x] ccm
- [x] certigo
- [x] cf-tool
- [x] cglm
- [ ] cgns

**Comment by GabriellaXue** [comment]
see #50893

**Comment by chenrui333** [comment]
Also just created a label for tracking down all the PRs:
https://github.com/Homebrew/homebrew-core/labels/hackillinois2020

**Comment by chenrui333** [comment]
Closing the issue now.
