### ISSUE TITLE
[epic] Refactor rust formulas to leverage `std_cargo_args`

### ISSUE THREAD

**Issue by vladimyr** [Homebrew/homebrew-core#56866]
Historically Rust formulas used following idiom for building:
```rb
system "cargo", "install", "--locked", "--root", prefix, "--path", "."
```

With the recent addition of `std_cargo_args`, it could be simplified to:
```rb
system "cargo", "install", *std_cargo_args
```

Due to the relatively simple nature of change (it fits under search/replace bucket) and the low number of targets (102 formulas, determined using `ag --ruby 'system "cargo"' -l | wc -l`), I propose addressing it through single PR. What do you think?

<details>
<summary>Formula list</summary>

- [x] [amp](https://github.com/Homebrew/homebrew-core/blob/master/Formula/amp.rb) (changes: 9cb21e617fd4a02ac5233718b19b94b4fceabbea)
- [x] [angle-grinder](https://github.com/Homebrew/homebrew-core/blob/master/Formula/angle-grinder.rb) (changes: 9304b5edf825e0a665a31abcea12145342739154)
- [x] [asuka](https://github.com/Homebrew/homebrew-core/blob/master/Formula/asuka.rb) (changes: cbfee1e1ec5d041028a43be64685954ab297155b)
- [x] [b3sum](https://github.com/Homebrew/homebrew-core/blob/master/Formula/b3sum.rb) (changes: 3438119720ca59967b564dcae1d96fb3a3940c86)
- [x] [badtouch](https://github.com/Homebrew/homebrew-core/blob/master/Formula/badtouch.rb) (changes: 148afdc80a36471fd8479f62d594d2d3483ffc7f)
- [x] [bandwhich](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bandwhich.rb) (changes: 79920ab67d7174d6301732b834f01a80222ba04e)
- [x] [bat](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bat.rb) (changes: cfa94ba5d7069382fdaecbeea218ea0622d7ff92)
- [x] [bingrep](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bingrep.rb) (changes: 90dc9f2884ea3bf22602b4ef919904824ee43650)
- [x] [boringtun](https://github.com/Homebrew/homebrew-core/blob/master/Formula/boringtun.rb) (changes: 3bf639155ee84c6093236f2647d3e539541112f3)
- [x] [broot](https://github.com/Homebrew/homebrew-core/blob/master/Formula/broot.rb) (changes: 82348462fc4f0b876fcbe071d5e2e8db0b2d3809)
- [x] [cargo-c](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cargo-c.rb) (changes: 9dc0839bdc19f58a5f6398a1f61833879954fb82)
- [x] [cargo-instruments](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cargo-instruments.rb) (changes: 4ee330ce6ea1da2aec412249094373f8d3bdf73c)
- [x] [click](https://github.com/Homebrew/homebrew-core/blob/master/Formula/click.rb) (changes: ec5418ba1d7d4839dc2e429782a4af2ab38d3b1e)
- [x] [cmdshelf](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cmdshelf.rb) (changes: 596f00361c4d2f99ba558cc6da3aa10ed9fb9807)
- [x] [cobalt](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cobalt.rb) (changes: 2e15983ba075b47d217734278a92ef2d6ec4f70c)
- [x] [deno](https://github.com/Homebrew/homebrew-core/blob/master/Formula/deno.rb) (changes: af0d129a9dc520a1b25aa3fee759e5b95d18682b)
- [x] [diffr](https://github.com/Homebrew/homebrew-core/blob/master/Formula/diffr.rb) (changes: 3416e027450c67f0831678e977fc6378785c4e76)
- [x] [diskus](https://github.com/Homebrew/homebrew-core/blob/master/Formula/diskus.rb) (changes: 2e38a0b196315b44e385950c6dcda1b781464b69)
- [x] [dssim](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dssim.rb) (changes: b3f00d065cd923652d15f86f9b2b8a6ea30c9a69)
- [x] [dust](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dust.rb) (changes: 4bfedddf2e5b34b58d9ac5bc1b3e92169657b7c5)
- [x] [eureka](https://github.com/Homebrew/homebrew-core/blob/master/Formula/eureka.rb) (changes: b9a14bcdf29478f4d5bf39ffdd362d9b28b04b56)
- [x] [eva](https://github.com/Homebrew/homebrew-core/blob/master/Formula/eva.rb) (changes: 5d96ac94cfa88d3769e565a8ebb4cf51f69c7402)
- [x] [fastmod](https://github.com/Homebrew/homebrew-core/blob/master/Formula/fastmod.rb) (changes: abc4eb1320c49947f2d4ebb79472baa5764ac252)
- [x] [fblog](https://github.com/Homebrew/homebrew-core/blob/master/Formula/fblog.rb) (changes: c2c6b7d7b1ef6b76fef22b80311cf2d796410a6e)
- [x] [fd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/fd.rb) (changes: 6dbb28ab37d1bd7dfe574b909d0e8bb852b92ba2)
- [x] [ffsend](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ffsend.rb) (changes: 6adc40054d1a53fd049375672cc21dc33ad4ca11)
- [x] [findomain](https://github.com/Homebrew/homebrew-core/blob/master/Formula/findomain.rb) (changes: 9b35dca2f1616aad540700e95b4684b24c8edfe9)
- [x] [fselect](https://github.com/Homebrew/homebrew-core/blob/master/Formula/fselect.rb) (changes: a118527813c27d0299de53e1f31f66802bd67e3e)
- [x] [geckodriver](https://github.com/Homebrew/homebrew-core/blob/master/Formula/geckodriver.rb) (changes: eddfb83031026d83c70f34df964fd4ef53f58afe)
- [x] [genact](https://github.com/Homebrew/homebrew-core/blob/master/Formula/genact.rb) (changes: 71e19c0e5b4c71db7db4b55be6a669530aef993b)
- [x] [gifski](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gifski.rb) (changes: 3d429575935f188af58cb2ad2913ca91b08bce28)
- [x] [git-absorb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-absorb.rb) (changes: 2467b709de850d2af75abe76296a2335da5e3bea)
- [x] [git-delta](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-delta.rb) (changes: 54bba9b3c4b30b082dc42ef5a9b929f4cf6567fe)
- [x] [git-interactive-rebase-tool](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-interactive-rebase-tool.rb) (changes: 0be5c56f2865e124048cd0c02eda80aeffcdca90)
- [x] [git-trim](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-trim.rb) (changes: e7ffe8040634b1a0818cfd43090e590071ac760a)
- [x] [gitui](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gitui.rb) (changes: 59d40715b062f71bb5bcbc8659e35edef803af44)
- [x] [gleam](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gleam.rb) (changes: b578808e04951f58139cf907732756c8f89e6862)
- [x] [gluon](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gluon.rb) (changes: 11726c10fe5e96c1348384b325ae93a7a276627d)
- [x] [grex](https://github.com/Homebrew/homebrew-core/blob/master/Formula/grex.rb) (changes: 1be4ddcc2c7d7884281eb220c4886c7398ed819c)
- [x] [grin-wallet](https://github.com/Homebrew/homebrew-core/blob/master/Formula/grin-wallet.rb) (changes: b090a40c8412f5072f8d64171e76dcbff43b0904)
- [x] [grin](https://github.com/Homebrew/homebrew-core/blob/master/Formula/grin.rb) (changes: 6a27c8397cabe0d387940a67fca955a76f498421)
- [x] [hexyl](https://github.com/Homebrew/homebrew-core/blob/master/Formula/hexyl.rb) (changes: 78fad909c0112b290cee9af9303823cdab4c3a5e)
- [x] [hyperfine](https://github.com/Homebrew/homebrew-core/blob/master/Formula/hyperfine.rb) (changes: e870a85dc7ef781fe20d98500225dc64454daa96)
- [x] [just](https://github.com/Homebrew/homebrew-core/blob/master/Formula/just.rb) (changes: ff984fb9e087cc5c9fbd62dc10dd98e86b71890a)
- [x] [ktmpl](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ktmpl.rb) (changes: 7fc3b3f26b3bb2530114c32072a2a63049e6d288)
- [x] [loc](https://github.com/Homebrew/homebrew-core/blob/master/Formula/loc.rb) (changes: af84cf9177ee0fe5bc19fedb27e88cea0409d9a2)
- [x] [lsd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/lsd.rb) (changes: 7207eb8bd4ccea503416259a911064e678603687)
- [x] [mask](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mask.rb) (changes: adbf1b47d690cd244a73eb7c23be86b3e23d795d)
- [x] [mdbook](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mdbook.rb) (changes: 6b87ebe4c6f03b935c1eabc573676f223243a4d7)
- [x] [mdcat](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mdcat.rb) (changes: 1cd61dcd7fa5a3a284b5744b60ae0e24dac37aab)
- [x] [meilisearch](https://github.com/Homebrew/homebrew-core/blob/master/Formula/meilisearch.rb) (changes: dad87f5b5daec38a7976013ecc655972b3a43091)
- [x] [miniserve](https://github.com/Homebrew/homebrew-core/blob/master/Formula/miniserve.rb) (changes: 9595e5f6ee71cd8a533e389afa2787fd5f1ac468)
- [x] [monolith](https://github.com/Homebrew/homebrew-core/blob/master/Formula/monolith.rb) (changes: 06911e70cbd42c04cdff74138b4d81d7b6f77988)
- [x] [navi](https://github.com/Homebrew/homebrew-core/blob/master/Formula/navi.rb) (changes: d8622c69da2a4f14d264e761a0ea383b6162024d)
- [x] [nushell](https://github.com/Homebrew/homebrew-core/blob/master/Formula/nushell.rb) (changes: 360acbb5640b753ad8b514563a63c5031d93a24a)
- [x] [oha](https://github.com/Homebrew/homebrew-core/blob/master/Formula/oha.rb) (changes: 329dab43a13cfac1178a3cb3dcf5d7cffedb89d6)
- [x] [onefetch](https://github.com/Homebrew/homebrew-core/blob/master/Formula/onefetch.rb) (changes: 6a1c6c26c7988c68f66fec52cda3c23ccbec790d)
- [x] [oxipng](https://github.com/Homebrew/homebrew-core/blob/master/Formula/oxipng.rb) (changes: 2c66ea979d631d8af75e55bd8b09f3d5b6f50366)
- [x] [pastel](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pastel.rb) (changes: 7dbe3899a2edff2ee85a856614a1917d0cee46e8)
- [x] [procs](https://github.com/Homebrew/homebrew-core/blob/master/Formula/procs.rb) (changes: 259cf7566fb9c1c284c2bfbe40b1b43b83e56f43)
- [x] [pueue](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pueue.rb) (changes: 856d81ac7bf601fa20fe5cd38f3f23269fffbeff)
- [x] [rargs](https://github.com/Homebrew/homebrew-core/blob/master/Formula/rargs.rb) (changes: 2b9da43d89b63e2935117bdb8e2a243eb845c59f)
- [x] [rav1e](https://github.com/Homebrew/homebrew-core/blob/master/Formula/rav1e.rb) (changes: 750c162abf80f842dd9874665d9238c359567269)
- [x] [rbspy](https://github.com/Homebrew/homebrew-core/blob/master/Formula/rbspy.rb) (changes: cc5c5557282a9182336e6e32738919a07ebfffe4)
- [x] [ripgrep-all](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ripgrep-all.rb) (changes: d593a4fe8fed3d451785d8462988cffaa08cdfba)
- [x] [ripgrep](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ripgrep.rb) (changes: d0632d779ca1b2cf63deaed96c56cc0af2e51e45)
- [x] [rust-analyzer](https://github.com/Homebrew/homebrew-core/blob/master/Formula/rust-analyzer.rb) (changes: c7b7d6033b066f1459bf4148f2b83cabce60a943)
- [x] [rustup-init](https://github.com/Homebrew/homebrew-core/blob/master/Formula/rustup-init.rb) (changes: 73347bd40312d2cdd75e847f8e9b37c0f990a6b7)
- [x] [sccache](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sccache.rb) (changes: 45f71e1653f075b54f25c59908747659a8a9151f)
- [x] [sd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sd.rb) (changes: 106038d727ac4df3aceb791102947d6ccefa6b99)
- [x] [shadowenv](https://github.com/Homebrew/homebrew-core/blob/master/Formula/shadowenv.rb) (changes: a7a8f88dd268d9943855b75f3a2e6c39e5243249)
- [x] [shellharden](https://github.com/Homebrew/homebrew-core/blob/master/Formula/shellharden.rb) (changes: 5d01cf3da5e4225ed0aa80a698598cd8fe67368b)
- [x] [sk](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sk.rb) (changes: 55654d8da79677be5d434bf00077c581474a6624)
- [x] [sn0int](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sn0int.rb) (changes: f7f019d68ac843b1260cc6b62e208b294f68bdd8)
- [x] [sniffglue](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sniffglue.rb) (changes: 0fa6cb5dee7e0a77bf15defed10d34b738278695)
- [x] [spotify-tui](https://github.com/Homebrew/homebrew-core/blob/master/Formula/spotify-tui.rb) (changes: bba2bb58742aa3e12a4c3b0ec1cba3f865a06a9e)
- [x] [spotifyd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/spotifyd.rb) (changes: c66ac7328051769ad02f7cabcea9c47ea92ef8c9)
- [x] [ssh-permit-a38](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ssh-permit-a38.rb) (changes: a8d6de9d7d9cf28b7e095c724924e44ba4b75c85)
- [x] [starship](https://github.com/Homebrew/homebrew-core/blob/master/Formula/starship.rb) (changes: 6685e1bc2f0354f8b21021c905e368760dbbf58d)
- [x] [svgcleaner](https://github.com/Homebrew/homebrew-core/blob/master/Formula/svgcleaner.rb) (changes: 41786a0aadf34cc8ab802467a6b128cc961bdc29)
- [x] [tealdeer](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tealdeer.rb) (changes: d4b9442cc579f313629836b0fc0962549285e728)
- [x] [tectonic](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tectonic.rb) (changes: 369d49f23bbcaad7401845929743ba03c9f33b4c)
- [x] [texlab](https://github.com/Homebrew/homebrew-core/blob/master/Formula/texlab.rb) (changes: bcfff3e2ed33c9f1df9c71419ec40aa353fff7b2)
- [x] [toast](https://github.com/Homebrew/homebrew-core/blob/master/Formula/toast.rb) (changes: c5e272f011158b8926d9a0899d36828184923d08)
- [x] [tokei](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tokei.rb) (changes: 4d33c37964b90cc81bcf3dc584e719d17bb84a25)
- [x] [topgrade](https://github.com/Homebrew/homebrew-core/blob/master/Formula/topgrade.rb) (changes: f842350e8e209b58964e8b2c35fa7ea33f14f803)
- [x] [tre-command](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tre-command.rb) (changes: c53508f91335a67853c03fcead8312d49d66ffe0)
- [x] [volta](https://github.com/Homebrew/homebrew-core/blob/master/Formula/volta.rb) (changes: e13a69a727a6a5ed25f20a18b25ecf0e30ebacb9)
- [x] [wagyu](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wagyu.rb) (changes: 5db9b91d4525c3bd0c3687f39fd40a1d307de74a)
- [x] [wapm](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wapm.rb) (changes: e05e00d536ba68e47da14a6a2929677c647944e3)
- [x] [wasm-pack](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wasm-pack.rb) (changes: cfea206362e9f56331a2adc44dfbc10b2580f4fb)
- [x] [wasmer](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wasmer.rb) (changes: 34a6fd3aa028ec058902b4d5e4ee4288473695c4)
- [x] [watchexec](https://github.com/Homebrew/homebrew-core/blob/master/Formula/watchexec.rb) (changes: 94dd5a0acc17dcbfb32396395dc1061d68ad9d17)
- [x] [websocat](https://github.com/Homebrew/homebrew-core/blob/master/Formula/websocat.rb) (changes: 99a757aa1a7fea4cb1e85751d352a720b10eaea6)
- [x] [xsv](https://github.com/Homebrew/homebrew-core/blob/master/Formula/xsv.rb) (changes: f75b39190c8829605c27e0157762c09379114afc)
- [x] [zenith](https://github.com/Homebrew/homebrew-core/blob/master/Formula/zenith.rb) (changes: e5b9ebf4005293248d91c474e2788a99e7a56373)
- [x] [zola](https://github.com/Homebrew/homebrew-core/blob/master/Formula/zola.rb) (changes: 2aa2b9d21110e91a9d7bab645360e8a4a48f88cb)
</details>

Script used to update/generate the upper list:
```bash
#!/bin/bash

ignored=(
  "diesel"
  "git-series"
  "gnirehtet"
  "pngquant"
  "rust"
)

ignore=""
for file in "${ignored[@]}"; do
  ignore=$(printf "%s --ignore %s.rb" "$ignore" "$file")
done

files=$(ag --ruby 'system "cargo"' $ignore -l | sort)

for file in $files; do
  name=$(basename -s .rb "$file")

  changes=""
  status=" "
  diff="$(git diff --shortstat master... "$file")"
  if [[ -n "$diff" ]]; then
    status="x"
    commit=$(git log -1 --format="%H" -- "$file")
    changes=" (changes: $commit)"
  fi

  printf "%s [%s] [%s](../blob/master/%s)%s\n" "-" "$status" "$name" "$file" "$changes"
done
```

**UPDATE:** I finished my exercise and updated 97 (see _**UPDATE 3**_) Rust formulas. These four I decide not to touch due to:

1. ~[diesel](https://github.com/Homebrew/homebrew-core/blob/master/Formula/diesel.rb) - does not use lockfile, would break if `--locked` gets applied~ #56922 
2. [gnirehtet](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnirehtet.rb) - uses both custom `--prefix` and `--path`
3. ~[pngquant](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pngquant.rb) - does not use lockfile, would break if `--locked` gets applied~ #56920 
4. [rust](https://github.com/Homebrew/homebrew-core/blob/master/Formula/rust.rb) - too risky to touch

⚠️ Following formulas didn't use `--locked` flag before and might break due to `cargo` argument changes:

- [dssim](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dssim.rb) (changes: b3f00d065cd923652d15f86f9b2b8a6ea30c9a69)
- [svgcleaner](https://github.com/Homebrew/homebrew-core/blob/master/Formula/svgcleaner.rb) (changes: 41786a0aadf34cc8ab802467a6b128cc961bdc29)

**UPDATE 2:** There are 3 new Rust formulas making total count go up to 105 but all three use `std_cargo_args` already:

1. [choose-rust](https://github.com/Homebrew/homebrew-core/blob/master/Formula/choose-rust.rb)
2. [sonic](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sonic.rb)
3. [zoxide](https://github.com/Homebrew/homebrew-core/blob/master/Formula/zoxide.rb)

**UPDATE 3:** Reverted [git-series](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-series.rb) changes due to build failure: https://github.com/Homebrew/homebrew-core/pull/56869#issuecomment-650494434

**Comment by SMillerDev** [comment]
Sounds good to me (separate commits though)

**Comment by chrmoritz** [comment]
You've missed [`deno`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/deno.rb#L46), which uses `-vv` as an extra argument to actually get build output from the `gn` based `V8` build phase.

**Comment by vladimyr** [comment]
Thank you for taking the time and double-checking! It is really easy to do things when there are so many great people covering your back! 🙂

**Comment by vladimyr** [comment]
Actually, I missed a bit more than `deno`:
```
❯ ag '"cargo", "install", "[^*]' -l | sort
Formula/b3sum.rb
Formula/deno.rb
Formula/diesel.rb
Formula/dssim.rb
Formula/git-series.rb
Formula/gluon.rb
Formula/gnirehtet.rb
Formula/meilisearch.rb
Formula/nushell.rb
Formula/pngquant.rb
Formula/rav1e.rb
Formula/ripgrep.rb
Formula/rust-analyzer.rb
Formula/svgcleaner.rb
Formula/tre-command.rb
Formula/wasmer.rb
Formula/websocat.rb
```

**Comment by vladimyr** [comment]
Now I'm down to:
```
Formula/b3sum.rb
Formula/diesel.rb
Formula/gluon.rb
Formula/gnirehtet.rb
Formula/meilisearch.rb
Formula/rust-analyzer.rb
Formula/rust.rb
```
Determined that using following script:
```bash
#!/bin/bash

files=$(ag --ruby 'system "cargo"' -l | sort)

for file in $files; do
  diff="$(git diff --shortstat master... "$file")"
  if [[ -z "$diff" ]]; then
    echo "$file"
  fi
done
```

**Comment by vladimyr** [comment]
⚠️ Following formulas didn't use `--locked` flag before and might break due to `cargo` argument changes:

- [dssim](../blob/master/Formula/dssim.rb) (changes: b3f00d065cd923652d15f86f9b2b8a6ea30c9a69)
- [git-series](../blob/master/Formula/git-series.rb) (changes: 681f2999265a4ed053a5e8877245631c8d8e3f43)
- [pngquant](../blob/master/Formula/pngquant.rb) (changes: af5c078d5e81fc9e34d83091c1c560351c1c31df)
- [svgcleaner](../blob/master/Formula/svgcleaner.rb) (changes: a93cb1585cbc279446224aeba2434743fd313463)

**Comment by vladimyr** [comment]
[dssim](https://github.com/kornelski/dssim), [git-series](https://github.com/git-series/git-series) and [svgcleaner](https://github.com/RazrFalcon/svgcleaner) all have commited lockfiles and should build successfully with `--locked` flag.

OTOH, [pngquant](https://github.com/kornelski/pngquant) does not have submitted `Cargo.lock` inside repo, and using `--locked` will most probably break that build. Additionally, it uses [`Makefile`](https://github.com/kornelski/pngquant/blob/7ffdc41525d80461d1f581644fbf9df135140c67/Makefile) so it is probably a good candidate for separate PR.
