### ISSUE TITLE
openjdk 14.0 upgrade failures

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/homebrew-core#57222]
### General
- [x] brew test —verbose hbase (#58150)
- [x] brew test —verbose opentsdb
- [ ] brew install —build-from-source mesos
- [ ] brew install —build-from-source gammaray (~~#57241~~)
- [ ] brew install —build-from-source mgba (https://github.com/Homebrew/homebrew-core/pull/56319)
  - Looks like a libzip issue
- [ ] brew install —build-from-source joshua
  - Source is offline and should be moved to the apache source.
- [x] brew install —verbose —build-bottle micronaut (https://github.com/Homebrew/homebrew-core/pull/57244)
- [x] brew fetch —retry orientdb (https://github.com/Homebrew/homebrew-core/pull/57248)
- [x] brew install —build-from-source elasticsearch (https://github.com/Homebrew/homebrew-core/pull/56530)
- [x] brew install —build-from-source —only-dependencies link-grammar
- [x] brew install —build-from-source link-grammar
- [x] brew install —build-from-source mlpack
- [x] brew install —build-from-source root
- [x] brew install root
- [x] brew test —verbose pax-construct
- [x] brew install —build-from-source cbmc (#57249)
### 10.15
- [x] brew install —build-from-source mercury
- [x] brew test —verbose xidel
### 10.14
- [x] brew install —build-from-source mercury
### 10.13
- [ ] brew install —build-from-source opencv@3

**Comment by zdavatz** [comment]
@claui @BytesGuy you think we can get this working on Big Sur/Apple Testkit machine? I am getting:
```
Last 15 lines from /Users/zdavatz/Library/Logs/Homebrew/openjdk/01.configure:
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking size of int *... 8
configure: The tested number of bits in the target (64) differs from the number of bits expected to be found in the target (32)
configure: error: Cannot continue.
/private/tmp/openjdk-20200717-63389-nsrfz6/jdk14u-jdk-14.0.1-ga/build/.configure-support/generated-configure.sh: line 82: 5: Bad file descriptor
configure exiting with result code 1
```

**Comment by claui** [comment]
> you think we can get this working on Big Sur/Apple Testkit machine?

@zdavatz I don’t think we can do it on our own. I suspect that as with several other complex compilers/runtimes, it’s going to involve lots of custom C++ and assembly code, tailored to the CPU and OS architecture.

**Comment by zdavatz** [comment]
@claui this worked well on the Apple TestKit machine:
```
brew tap AdoptOpenJDK/openjdk
brew cask install adoptopenjdk8
```
`java8` is now up and running. ;)

**Comment by SMillerDev** [comment]
I suspect based on the error that `configure` expects arm to be 32 bits, so we'd need to specify that ARM can mean aarch64
