### ISSUE TITLE
Python 3.9 Migration

### ISSUE THREAD

**Issue by Rylan12** [Homebrew/homebrew-core#62201]
Python 3.9 has been released and [added to homebrew-core](https://github.com/Homebrew/homebrew-core/pull/61163)!

Currently, there are 42 formulae in homebrew-core that depend on `python@3.8`. The next step in the migration process is to switch as many formulae as possible to depend on the new `python@3.9` formula.

See https://github.com/Homebrew/homebrew-core/issues/62201#issuecomment-715182529 for a list of formulae to be upgraded.

No need to ask before working on this. If there's a formula that you can update, go ahead and open a PR and we'll get to it as soon as we can!

---

This is a great first issue to work on if you're new to Homebrew and if you're participating in Hacktoberfest, this is a great way to knock out some genuine PRs that will be greatly appreciated!

Here are the basic steps to migrate a formula to Python 3.9:

1. Change `depends_on "python@3.8"` to `depends_on "python@3.9"`
1. Change any other occurrences of `python@3.8` to `python@3.9`
1. Add a line with `revision 1` (if the formula already has a revision, increment the number by one)
1. Test the change locally by running `brew install -s <formula>`, `brew test <formula>` and `brew audit --strict <formula>`
    - Try to fix any failures locally first. If you need help, feel free to open a PR, but please be prepared to continue to work on it.
1. Open a PR with the name: `<formula>: migrate to python@3.9`
1. Done!

If you're a new contributor and want to help out, make sure to read our [countributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) and check out [How To Open a Homebrew Pull Request](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) in our [documentation](https://docs.brew.sh)

**Comment by mayank** [comment]
@Rylan12 can I pick this one? Please assign to me!

**Comment by Rylan12** [comment]
@mayank thanks for your interest! Please feel free to work on this!

This is too big of a project for one person to tackle on their own, but feel free to open a PR to update one or a few formulae.

**Comment by mayank** [comment]
@Rylan12 I need to install all the formulas on mac? Is there anything like docker for this? 
I can write some testing script which will run all at once.

**Comment by fxcoudert** [comment]
There are 234 formulas that are independent: they depend on python@3.8 only directly, they have not reverse dependencies. I will deal with those first.

**Comment by Rylan12** [comment]
@LSmith-Zenoscave and @mayank, this is not an issue that will be closed with one PR that updates all 400 formulae. The best way to do it is just to make a few PRs, each with one formula. Take a look at some of the PRs that have been made so far if you need a model for what we're looking for.

If you're not already a Homebrew user this probably isn't a great issue for you. If you want to get more involved, though, feel free to check out some of the links I've added above for information about how to get set up.

**Comment by Rylan12** [comment]
@fxcoudert: can you post the list of independent formulae (maybe link a gist?) so others can help out with those?

**Comment by Rylan12** [comment]
FYI to anyone looking to help out here: The current `virtualenv` version we're using doesn't seem to support Python 3.9 so we should hold off on updating lots of formulae until that issue's been resolved.

**Comment by fxcoudert** [comment]
The list of independent formulas is below. If you don't mind, I'm happy to open PRs for all of them once `virtualenv` is fixed: it will literally take 2 minutes, the script is in place, and is already tracking locally which ones I have submitted or not.

There are plenty of other small "clusters" of formulas that can be migrated and where crowd-sourcing will be necessary.


<details>

```
airshare
ansible-lint
asciinema
atdtool
athenacli
auditbeat
austin
autopep8
aws-elasticbeanstalk
aws-google-auth
aws-shell
awscli@1
awscurl
awslogs
awsume
azure-cli
b2-tools
bagit
bandcamp-dl
beancount
bedtools
bento4
binwalk
black
borgmatic
buku
bumpversion
c7n
ccm
certbot
cfn-lint
charm-tools
choose
cloudformation-cli
coconut
codemod
codespell
commitizen
conan
cookiecutter
cppcheck
cppman
credstash
csvkit
csvtomd
ctemplate
datasette
ddgr
deheader
diceware
distcc
dnstwist
docker-compose
docker-squash
doitlive
dxpy
eg-examples
esptool
euler-py
eye-d3
fabric
fades
fava
fbi-servefiles
flake8
flawfinder
flintrock
flit
fonttools
fpp
gandi.cli
gcovr
gimme-aws-creds
ginac
git-filter-repo
git-plus
git-remote-codecommit
git-review
git-revise
gitup
glances
global
googler
goolabs
grc
grip
hashpump
heartbeat
homeassistant-cli
honcho
howdoi
hsd
httpie
hy
i386-elf-gdb
instalooter
internetarchive
iproute2mac
jailkit
jc
jenkins-job-builder
jinja2-cli
jrnl
keepassc
keepkey-agent
khal
khard
legit
liblouis
liblouis
libtcod
link-grammar
liquidctl
litecli
livestreamer
lizard-analyzer
localstack
mackup
macvim
magic-wormhole
mdv
metricbeat
micropython
mitie
mkdocs
mongo-orchestration
mps-youtube
mycli
nbdime
nicovideo-dl
node@12
notifiers
nyx
oci-cli
openstackclient
osc
packetbeat
pass-git-helper
passpie
pastebinit
percol
peru
pgcli
pipgrip
pipx
pius
platformio
poetry
ponysay
pre-commit
proselint
pssh
pwncat
pwntools
pygitup
pygments
pyinstaller
pyinvoke
pylint
python-markdown
python-yq
pyvim
q
rabbitmq
rbtools
recon-ng
redo
remarshal
reorder-python-imports
restview
robot-framework
rom-tools
rst-lint
rtv
s3ql
sceptre
scour
shallow-backup
shyaml
singular
snakemake
spoof-mac
sqlite-utils
sqlparse
ssh-audit
sshuttle
sslmate
statik
stone-soup
stormssh
streamlink
subliminal
supervisor
svtplay-dl
sync_gateway
tarsnapper
termius
termtosvg
thefuck
theharvester
todoman
toot
tox
trailscraper
translate-toolkit
trash-cli
trezor-agent
tvnamer
twarc
twine-pypi
twoping
twtxt
txt2tags
unoconv
vdirsyncer
vim
vpn-slice
vsts-cli
wakatime-cli
watchman
watson
weboob
whatmp3
x86_64-elf-gdb
xonsh
xxh
yapf
ydcv
ydiff
yle-dl
yosys
you-get
zabbix-cli
znc
```

</details>

**Comment by Rylan12** [comment]
Thanks, @fxcoudert. I've removed the community help tags for now. I jumped the gun a little bit—let's deal with the first round internally and then I'll reopen to the community.

I see that PRs are being generated, what's the plan for those? Mass approval of the ones that pass CI?

What's the plan for the `virtualenv` change now that the fix has been merged? Are we going to wait until Monday for a new tag or move ahead?

**Comment by fxcoudert** [comment]
The PRs should not be merged before the next Brew tag ships, which is expected on Monday (2020-10-12). That will give them time to go through CI, and we can see how many break, and fix them. After Monday, I welcome review and approval of the PRs.

**Comment by Rylan12** [comment]
> The PRs should not be merged before the next Brew tag ships, which is expected on Monday (2020-10-12). That will give them time to go through CI, and we can see how many break, and fix them. After Monday, I welcome review and approval of the PRs.

Got it, thanks.

**Comment by fxcoudert** [comment]
Brew 2.5.4 is tagged. Feel free to review / accept the pull requests.

**Comment by LSmith-Zenoscave** [comment]
> There are 234 formulas that are independent: they depend on python@3.8 only directly, they have not reverse dependencies. I will deal with those first.

Can you share how you came up with those numbers? I found a similar list but with 353.
I just looked for any files that depends_on "python@3.8" with no other deps; call it `deps_on_py`
Then found any files that were in a depends_on; call it `any_deps_on`
If there are 353 files that have a depends on python3.8 and only python3.8 are not depended on from my findings.

Perhaps I added extras or some were missed?
 I can add my script to generate these if needed

**Comment by fxcoudert** [comment]
- Start with the list of formulas that directly depend on python@3.8
- Remove those that are a dependency in another formula
- For each remaining formula, use `brew deps --tree --include-build --include-test` to remove those that  if they also depend indirectly on python@3.8

**Comment by NicoHaase** [comment]
I'm not really sure if this is connected, but could you have a look at https://github.com/Homebrew/discussions/discussions/37 and check whether upgrading to Python 3.9 broke `docker-compose`?

**Comment by cclauss** [comment]
Is this the right list of blocking PRs?
* [ ] auditbeat: migrate to python@3.9 #62243
* [ ] bandcamp-dl: migrate to python@3.9 #62256
* [ ] binwalk: migrate to python@3.9 #62260
* [ ] charm-tools: migrate to python@3.9 #62269
* [ ] distcc: migrate to python@3.9 #62288
* [ ] global: migrate to python@3.9 #62319
* [ ] heartbeat: migrate to python@3.9 #62325
* [ ] i386-elf-gdb: migrate to python@3.9 #62332
* [ ] keepassc: migrate to python@3.9 #62341
* [ ] mdv: migrate to python@3.9 #62357
* [ ] packetbeat: migrate to python@3.9 #62373
* [ ] passpie: migrate to python@3.9 #62375
* [ ] s3ql: migrate to python@3.9 #62411
* [ ] sceptre: migrate to python@3.9 #62412
* [ ] supervisor: migrate to python@3.9 #62429
* [ ] thefuck: migrate to python@3.9 #62436
* [ ] theharvester: migrate to python@3.9 #62437
* [ ] twtxt: migrate to python@3.9 #62449
* [ ] x86_64-elf-gdb: migrate to python@3.9 #62462
* [ ] Python 3.9 mass migration #62560
* [ ] OpenJDK upgrade strategy #62786

**Comment by fxcoudert** [comment]
There's a label, and help is welcome on any relevant PR. I don't think there is much use for this meta-issue, maybe we should close it?

**Comment by cclauss** [comment]
I missed the label... Thanks!

**Comment by Rylan12** [comment]
> There's a label, and help is welcome on any relevant PR. I don't think there is much use for this meta-issue, maybe we should close it?

Are we definitely going to do the mass migration in https://github.com/Homebrew/homebrew-core/pull/62560? If so, yeah I think this can be closed. If that's not going to work, there are still almost 200 formulae to be migrated so it might be worth keeping open in that case.

**Comment by alexchandel** [comment]
Sounds like some of `glib gobject-introspection pyqt protobuf bazel libtorch vtk@8.2 gdal vtk ansible emscripten gnuradio kibana libtensorflow libtensorflow@1 mame nest nwchem opencv opencv@3 semgrep wxpython` will be done separately

**Comment by xxyzz** [comment]
I wanna ask a dumb question: is it OK to upgrade `python`, `python3` and `python@3` aliases to `python@3.9`? I guess it won't affect other formulas.

**Comment by iMichka** [comment]
This question is best asked on https://github.com/Homebrew/discussions/discussions, but yes you can update your own alias if you want to.

**Comment by fxcoudert** [comment]
This is the list of formulas that remain to be migrated to Python 3.9. Almost all of them are independent, and should already have a PR open to which volunteers can contribute:

- [ ] afflib
- [ ] airshare
- [ ] auditbeat
- [ ] azure-cli
- [ ] binwalk
- [ ] charm-tools
- [ ] distcc
- [ ] fail2ban
- [ ] fdroidserver
- [ ] filebeat
- [ ] gdb
- [ ] gdbgui
- [ ] gjs
- [ ] global
- [ ] heartbeat
- [ ] i386-elf-gdb
- [ ] jrnl
- [ ] keepassc
- [ ] lc0
- [ ] ldns
- [ ] mdv
- [ ] mypy
- [ ] nicotine-plus
- [ ] onnxruntime
- [ ] packetbeat
- [ ] passpie
- [ ] s3cmd
- [ ] s3ql
- [ ] salt
- [ ] sceptre
- [ ] supervisor
- [ ] thefuck
- [ ] theharvester
- [ ] twtxt
- [ ] x86_64-elf-gdb

**Comment by fxcoudert** [comment]
Also part of the migration are test and audit failures that should be investigated and fixed:

10.15

```
brew audit vapoursynth --online --git --skip-style
brew audit gtk-doc --online --git --skip-style
brew audit uhd --online --git --skip-style
brew audit cryptominisat --online --git --skip-style
brew audit csound --online --git --skip-style
brew audit cxxtest --online --git --skip-style
brew audit dnsviz --online --git --skip-style
brew test --verbose gnuradio
brew audit mitmproxy --online --git --skip-style
brew audit mkvtomp4 --online --git --skip-style
brew install --verbose --build-bottle redex
```

10.14

```
brew audit vapoursynth --online --git --skip-style
brew audit gtk-doc --online --git --skip-style
brew audit uhd --online --git --skip-style
brew audit anime-downloader --online --git --skip-style
brew audit cmark-gfm --online --git --skip-style
brew audit cmark --online --git --skip-style
brew audit code-server --online --git --skip-style
brew audit cryptominisat --online --git --skip-style
brew audit csound --online --git --skip-style
brew audit gnuradio --online --git --skip-style
brew test --verbose gnuradio
brew audit gprof2dot --online --git --skip-style
brew audit rdiff-backup --online --git --skip-style
brew install --verbose --build-bottle redex
brew audit redex --online --git --skip-style
```

10.13

```
brew audit vapoursynth --online --git --skip-style
brew audit gtk-doc --online --git --skip-style
brew audit uhd --online --git --skip-style
brew audit cryptominisat --online --git --skip-style
brew audit genometools --online --git --skip-style
brew audit git-cola --online --git --skip-style
brew audit gitfs --online --git --skip-style
brew audit gitless --online --git --skip-style
brew test --verbose gnuradio
brew audit libproxy --online --git --skip-style
brew fetch --retry pytouhou --build-bottle --force
brew install --verbose --build-bottle pytouhou
brew install --verbose --build-bottle redex
```

**Comment by tieugene** [comment]
I don't know what is the source of problem (migrating to py39, brew bug/feature or something else), but as for newly (from scratch) installed homebrew and python@3.9 on it:
1. In [RTFM](https://docs.brew.sh/Homebrew-and-Python):
> Unversioned symlinks for python, python-config, pip etc. are installed here:
$(brew --prefix)/opt/python/libexec/bin

There is no $(brew --prefix)/opt/python/ directory

2. brew info python@3.9:
...
Python has been installed as
  /usr/local/bin/python3

No, there is no /usr/local/bin/python3

3. brew switch is useless

I don't know how to work with this "python3".
To call it as "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/bin/python3.9" is too complex.

**Comment by fxcoudert** [comment]
@tieugene the `python@3.9` binary currently resides in `/usr/local/opt/python@3.9/bin`. We'll be migrating to that as our primary formula soon, and then it will be in `/usr/local/bin/python3` (which means our documentation is currently wrong, indeed).

**Comment by shinysuittheory** [comment]
I've been trying to reinstall mpv from source so as to get the app bundle for macOS, similarly to the closed and now locked "Missing mpv.app bundle #46532", but keep getting an error which I believe has something to do with python but I can't figure out what. Can anyone shed some light? Wasn't sure if to create a separate issue  

link to error text from terminal - https://pastebin.pl/view/a5a1e0d0

<img width="675" alt="Screenshot 2020-10-26 at 3 13 37 PM" src="https://user-images.githubusercontent.com/73496105/97217674-0456c880-179e-11eb-9f2d-17ddc62d1d91.png">

**Comment by SMillerDev** [comment]
You should ask the mpv developers, homebrew doesn't provide support for modified builds.

**Comment by Raptoaaah** [comment]
I was trying to build LasVegas using VTK in cmake and get this not yet very understandable error message
![Bildschirmfoto 2020-10-27 um 07 55 47](https://user-images.githubusercontent.com/18486085/97267081-db7c1500-1829-11eb-8e01-8b718b1f9021.png)
Seems likely to me that migration to python3.9 was not completed successfully for this module
At least I would like to know if I have to install something manually

**Comment by hjmallon** [comment]
When trying to install matplotlib inside the jupyterlab venv after updating (to python 3.9 based jupyterlab) I am getting this error.

https://stackoverflow.com/questions/64245321/having-problems-running-numpy-error-about-buggy-accelerate-backend-python

**Comment by fxcoudert** [comment]
@hjmallon please open a new issue and provide all information requested, so we can help you

**Comment by fxcoudert** [comment]
@Raptoaaah please open a new issue and provide all information requested, so we can help you

**Comment by fxcoudert** [comment]
At this point we have migrated all the main Python formula to python 3.9.
425 of our Python-related formulas have been migrated to Python 3.9, and 22 are still using Python 3.8, due to incompatibilities with Python 3.9

I am closing this tracking issue, as it mostly attracts bug reports (for which we prefer people to file new issues). Any help with the remaining PRs is welcome, at least in reporting bugs to upstream so they get fixed at some point.
