### ISSUE TITLE
openjdk@8 migration tracking issue

### ISSUE THREAD

**Issue by jonchang** [Homebrew/homebrew-core#63290]
Now that `openjdk@8` [can be installed as a formula](https://github.com/Homebrew/homebrew-core/pull/63096), we should start migrating our current formulae that `depends_on java: "1.8"` to use `depends_on "openjdk@8"` instead.

This is part of our long-term goal to remove all cask Requirements from Homebrew/core, which will help speed up our CI deployment time. Once this is complete the only cask Requirements remaining would be osxfuse and xquartz.

General guidelines:

1. `revision` bump
2. `depends_on java: "1.8"` => `depends_on "openjdk@8"`

- [x] amdatu-bootstrap
- [x] apache-drill
- [x] apache-flink
- [x] apache-geode
- [x] app-engine-java
- [x] avian
- [x] aws-apigateway-importer
- [x] ballerina
- [x] bee
- [x] blazegraph
- [x] cassandra-reaper
- [x] ceylon
- [x] clojure-lsp
- [x] confluent-platform
- [x] couchdb-lucene
- [x] cypher-shell
- [x] digdag
- [ ] ~~drip~~ deprecated
- [ ] ~~druid~~ deprecated
- [x] elasticsearch@6
- [x] embulk
- [x] glassfish
- [x] gosu
- [x] grakn
- [ ] groovyserv
- [ ] henplus
- [x] hexgui
- [x] hive
- [ ] ~~infer~~ deprecated (but see https://github.com/Homebrew/homebrew-core/pull/62862)
- [x] javarepl
- [x] jing-trang
- [x] jmxterm
- [x] jmxtrans
- [ ] jooby-bootstrap
- [x] jvm-mon
- [x] jvmtop
- [x] kafka
- [x] kettle
- [x] libreadline-java
- [x] logstash
- [x] maxwell
- [x] mesos
- [ ] ~~nailgun~~ deprecated
- [ ] ~~opentsdb~~ deprecated
- [x] payara
- [x] pdftk-java
- [x] pillar
- [x] predictionio
- [x] sbt@0.13
- [x] scala@2.11
- [x] scm-manager
- [x] swagger-codegen@2
- [x] voldemort
- [x] wartremover
- [ ] ~~yeti~~ deprecated
- [x] zanata-client

**Comment by Moisan** [comment]
I couldn't get `avian` to work with `openjdk@8` and their homepage states
> PLEASE NOTE: This project is not currently being developed, maintained, or supported.

Should we deprecate it?

**Comment by SMillerDev** [comment]
Yes we should

**Comment by rook59** [comment]
I would block further migrations since openjdk@8 is broken, see https://github.com/Homebrew/homebrew-core/pull/64536

**Comment by SMillerDev** [comment]
Since it would install from a bottle that doesn't block migrating to it.

**Comment by rook59** [comment]
It would not install from a bottle on Linux / linuxbrew.

**Comment by jonchang** [comment]
A couple things would help here:

1. A better way to get the source code of a single tag for the entire set of jdk8u repositories, that doesn't rely on the whatever versions of bzip2 libraries (or whatever reason the checksum changed) that the jdk.net server uses.

2. Fixing the build on Linux so we can test it there (see https://github.com/Homebrew/linuxbrew-core/pull/21317)

**Comment by jonchang** [comment]
https://github.com/Homebrew/homebrew-core/pull/64659 has all test failures.
https://github.com/Homebrew/homebrew-core/pull/64662 has build and/or test failures. 

I'm not intending on having the adoptopenjdk8 cask on big sur so these will have to be fixed or left behind.

**Comment by MikeMcQuaid** [comment]
@jonchang https://github.com/Homebrew/brew/pull/9208 is worth a note, too. `/usr/libexec/java_home` has stopped working on Big Sur so I think we're probably in "deprecate and remove the formulae that don't build" territory soon.

**Comment by jonchang** [comment]
Given https://github.com/Homebrew/brew/issues/9194 we're just gonna start skipping these on CI and eventually remove them entirely once JavaRequirements are totally gone from Homebrew/core. When our old CI gets shut down, the Mojave and Catalina virtual machines on the new CI runners will no longer have any Casks preinstalled at all.

Now that https://github.com/Homebrew/homebrew-core/pull/64659 and https://github.com/Homebrew/homebrew-core/pull/64662 are merged, I consider this to be finished 🚀 

Thanks to @hyuraku, @mattrussi, @Moisan, @samford, and @abl123 (their first-ever contributions on GitHub!) for helping to migrate these formulae, and @bayandin, @chenrui333 and @SMillerDev for helping to review and test pull requests!

**Comment by magneticflux-** [comment]
> 
> 
> It would not install from a bottle on Linux / linuxbrew.

I'm running into the same issue I believe:
```
brew upgrade openjdk@8
==> Upgrading 1 outdated package:
openjdk@8 1.8.0.242 -> 1.8.0+275
==> Upgrading openjdk@8 1.8.0.242 -> 1.8.0+275
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/9976a857d574de2927c580f1f61bcd647fb795fe/openjdk%408/xcode.patch
Already downloaded: /home/mitchell/.cache/Homebrew/downloads/d8844da849e8898f5db143aabb6f28de2d5fe7e8d124afaa3c543a5d54b3163d--xcode.patch
==> Downloading https://cdn.azul.com/zulu/bin/zulu7.42.0.13-ca-jdk7.0.282-linux_x64.tar.gz
Already downloaded: /home/mitchell/.cache/Homebrew/downloads/c66230ef2081f49210fe61570c623dd2e7995d9e0b68bfa274fb425e163c0cc6--zulu7.42.0.13-ca-jdk7.0.282-linux_x64.tar.gz
==> Downloading https://openjdk-sources.osci.io/openjdk8/openjdk8u275-ga.tar.xz
Already downloaded: /home/mitchell/.cache/Homebrew/downloads/efe2d2bce71cf353bf93bda58910afdbba598747b78b88eb4a0fe713727f4445--openjdk8u275-ga.tar.xz
==> Patching
==> Applying xcode.patch
patching file common/autoconf/basics.m4
patching file common/autoconf/flags.m4
patching file common/autoconf/generated-configure.sh
Hunk #1 succeeded at 1897 (offset 2 lines).
Hunk #2 succeeded at 14009 (offset 1 line).
Hunk #3 succeeded at 26774 (offset 23 lines).
Hunk #4 succeeded at 26837 (offset 23 lines).
Hunk #5 succeeded at 41295 (offset 23 lines).
Hunk #6 succeeded at 41394 (offset 23 lines).
Hunk #7 succeeded at 41420 (offset 23 lines).
Hunk #8 succeeded at 41485 (offset 23 lines).
Hunk #9 succeeded at 42170 (offset 23 lines).
Hunk #10 succeeded at 42259 (offset 23 lines).
Hunk #11 succeeded at 48934 (offset 23 lines).
patching file common/autoconf/libraries.m4
patching file common/autoconf/platform.m4
patching file common/autoconf/toolchain.m4
patching file hotspot/make/bsd/makefiles/gcc.make
patching file hotspot/make/bsd/makefiles/jsig.make
patching file hotspot/src/os/aix/vm/decoder_aix.hpp
patching file hotspot/src/os/bsd/vm/decoder_machO.hpp
patching file hotspot/src/os/windows/vm/decoder_windows.hpp
patching file hotspot/src/share/vm/classfile/classLoader.hpp
patching file hotspot/src/share/vm/prims/jvmtiImpl.hpp
patching file hotspot/src/share/vm/runtime/perfData.hpp
patching file hotspot/src/share/vm/utilities/decoder.hpp
patching file hotspot/src/share/vm/utilities/decoder_elf.hpp
patching file jdk/make/lib/CoreLibraries.gmk
Hunk #1 succeeded at 414 (offset 4 lines).
Hunk #2 succeeded at 448 (offset 4 lines).
Hunk #3 succeeded at 509 (offset 4 lines).
patching file jdk/src/macosx/native/sun/osxapp/ThreadUtilities.m
Error: An exception occurred within a child process:
  TypeError: no implicit conversion of nil into String
```
Is there a workaround or migration to solve this?

**Comment by bayandin** [comment]
> Is there a workaround or migration to solve this?

Will be fixed in https://github.com/Homebrew/linuxbrew-core/pull/21317
