### ISSUE TITLE
x11 migration tracking issue

### ISSUE THREAD

**Issue by jonchang** [Homebrew/homebrew-core#64166]
Now that X in all its legion forms [can be installed as a formula](https://github.com/Homebrew/homebrew-core/pull/57995), we should start migrating our current formulae that `depends_on :x11` to instead depend on the brewed versions of the various X libraries.

This is part of our long-term goal to remove all cask Requirements from Homebrew/core, which will help speed up our CI deployment time. Once this is complete the only cask Requirements remaining would be java and osxfuse.

General instructions:

1. `brew install FORMULA` on this list (should be poured from a bottle, not built from source)
2. Run `brew linkage FORMULA` and observe which X11 libraries it links against
3. Modify the formula to remove `depends_on :x11` and replace it with e.g. `depends_on "libx11"` and any additional X libraries
4. Update `/opt/X11` or `MacOS::XQuartz` references to instead point them to the brewed formula paths
5. `revision` bump
6. `brew install -s FORMULA` and `brew linkage FORMULA` to check that it's now linking against brewed X and not XQuartz

See an example here: https://github.com/Homebrew/homebrew-core/pull/64165

Some caveats to these instructions:

* formulae that need to create or interact with an x11 GUI element might not work as not all components that exist in XQuartz.app have been ported over to our brewed versions. The missing X library (e.g. apple-wm) will need to be added as a new formula.
* formulae that have build time dependencies on X libraries won't show up in `brew linkage`. In this case you'll have to figure out what it's depending on based on the configure or cmake script. 
* if you really can't figure out how to build something and its usage is low (`brew info` analytics) consider disabling or removing the formula

- [x] cgoban - #64252
- [x] chezscheme - #64367
- [x] corectl https://github.com/Homebrew/homebrew-core/pull/64780
- [x] curlftpfs https://github.com/Homebrew/homebrew-core/pull/64491
- [x] ddd - #64407
- [x] diff-pdf https://github.com/Homebrew/homebrew-core/pull/64651
- [x] dmenu - #64279
- [x] dwm https://github.com/Homebrew/homebrew-core/pull/64281
- [x] feh https://github.com/Homebrew/homebrew-core/pull/64377
- [x] fizmo https://github.com/Homebrew/homebrew-core/pull/64378
- [x] fmsx 1ed8d74aab
- [x] fox https://github.com/Homebrew/homebrew-core/pull/64713
- [x] freeglut https://github.com/Homebrew/homebrew-core/pull/64419
- [x] freerdp https://github.com/Homebrew/homebrew-core/pull/64502
- [x] geomview https://github.com/Homebrew/homebrew-core/pull/64618
- [x] grace https://github.com/Homebrew/homebrew-core/pull/64481
- [x] hyperkit https://github.com/Homebrew/homebrew-core/pull/64613
- [x] imake https://github.com/Homebrew/homebrew-core/pull/64499
- [x] imlib2 https://github.com/Homebrew/homebrew-core/pull/64165
- [x] jnethack https://github.com/Homebrew/homebrew-core/pull/64347
- [x] lesstif https://github.com/Homebrew/homebrew-core/pull/64775
- [x] libxkbcommon https://github.com/Homebrew/homebrew-core/pull/64776
- [x] mesalib-glw https://github.com/Homebrew/homebrew-core/pull/64346
- [x] morse https://github.com/Homebrew/homebrew-core/pull/64333
- [x] mupdf #64479
- [x] ncview https://github.com/Homebrew/homebrew-core/pull/64777
- [x] nedit https://github.com/Homebrew/homebrew-core/pull/64356
- [x] openmotif https://github.com/Homebrew/homebrew-core/pull/64356
- [x] pdf2image https://github.com/Homebrew/homebrew-core/pull/64738
- [x] pgplot https://github.com/Homebrew/homebrew-core/pull/64332
- [x] rdesktop https://github.com/Homebrew/homebrew-core/pull/64611
- [x] robot-framework https://github.com/Homebrew/homebrew-core/pull/64749
- [x] rxvt-unicode https://github.com/Homebrew/homebrew-core/pull/64564
- [x] sng https://github.com/Homebrew/homebrew-core/pull/64646
- [x] startup-notification  https://github.com/Homebrew/homebrew-core/pull/64778
- [x] sxiv https://github.com/Homebrew/homebrew-core/pull/64278
- [x] tgif https://github.com/Homebrew/homebrew-core/pull/64528
- [x] tiger-vnc https://github.com/Homebrew/homebrew-core/pull/64608
- [x] wmctrl https://github.com/Homebrew/homebrew-core/pull/64581
- [x] wordnet https://github.com/Homebrew/homebrew-core/pull/64531
- [x] xclip https://github.com/Homebrew/homebrew-core/pull/64314
- [x] xdotool https://github.com/Homebrew/homebrew-core/pull/64204
- [x] xlispstat https://github.com/Homebrew/homebrew-core/pull/64203
- [x] xpa https://github.com/Homebrew/homebrew-core/issues/64166
- [x] xshogi https://github.com/Homebrew/homebrew-core/pull/64200

**Comment by issyl0** [comment]
`xpa` doesn't seem to link against any X11 libraries:

```
➜ brew linkage xpa
System libraries:
  /usr/lib/libSystem.B.dylib
```

**Comment by jonchang** [comment]
> xpa doesn't seem to link against any X11 libraries:

My guess is that it has a build-time dependency. Looking at the [README](https://github.com/ericmandel/xpa) maybe `depends_on "libxt" => :build` would work?

**Comment by SeekingMeaning** [comment]
Copy-and-pasteable checklist:

```
- [ ] `brew install FORMULA` on this list (should be poured from a bottle, not built from source)
- [ ] Run `brew linkage FORMULA` and observe which X11 libraries it links against
- [ ] Modify the formula to remove `depends_on :x11` and replace it with e.g. `depends_on "libx11"` and any additional X libraries
- [ ] Update `/opt/X11` or `MacOS::XQuartz` references to instead point them to the brewed formula paths
- [ ] `revision` bump
- [ ] `brew install -s FORMULA` and `brew linkage FORMULA` to check that it's now linking against brewed X and not XQuartz
```

**Comment by gromgit** [comment]
Just a couple of working notes:
* If `brew linkage` outputs `/opt/X11/lib/libXp.6.dylib`, that's [officially obsolete/deprecated](https://www.x.org/wiki/ModuleDescriptions/#obsoletedeprecated), and there's no formula for it even in `linuxbrew/xorg`. `openmotif` used to link to it, but seems to build just fine without it post-migration, and I suspect it can generally be ignored for the purpose of this exercise.
* If your migration fails on `#include <X11/bitmaps/...>`, I've created #64282 to add the `xbitmaps` formula that you can `depends_on`. (Would be great if someone could review that ASAP.)

**Comment by carlocab** [comment]
A number of formulae link against

    /opt/X11/lib/libGL.1.dylib

such as `freeglut` and `mesalib-glw`. I can't find a `libgl` formula (or one like it), unfortunately. I'm guessing this has to do with OpenGL being deprecated in favour of Metal?

**Comment by jonchang** [comment]
I believe we can link against opengl with `-framework OpenGL` but I don't know if that makes sense if Apple has deprecated that going forward. We disabled building `libgl` in https://github.com/homebrew/homebrew-core/pull/46992 so one solution might be to re-enable that in the `mesa` formula and then depend on `mesa` going forward for formulae that need OpenGL

**Comment by gromgit** [comment]
I've added a couple of new formulae that were not in #57995, which are needed in certain cases:
* `xbitmaps` (#64282) - for any formula that does `#include <X11/bitmaps/...>`
* `libxp` (#64337) - turns out I was wrong about not needing it. `nedit` actually refuses to build without it when linked with the migrated `openmotif`, and it's probably safer to have `openmotif` use it too. Add this if `/opt/X11/lib/libXp.6.dylib` is in the linkage list of the original formula.

**Comment by gromgit** [comment]
Important note: If you usually ssh into your macOS box like me, X11 migration builds and tests *absolutely need to be run from the console*. For instance, I was getting false successes from `brew install/test nedit` because the lack of a valid `DISPLAY` actually caused it to not attempt any GUI operations at all. When I started running it from the console, even `brew install` would fail with the same errors as the CI box.

It's also possible that remote-displaying to a separate X11 server could also trigger false successes, so best to stick to console runs.

**Comment by iMichka** [comment]
Just a small comment about the `libgl` thing: on linux we use the one provided by `mesa`, so this is the right thing to do.

**Comment by jonchang** [comment]
I've merged `libxp` in https://github.com/Homebrew/homebrew-core/pull/64337

**Comment by carlocab** [comment]
Not sure what I'm doing wrong, but `brew install fox` is giving me errors after I tried migrating fox. (It says it can't find the formula, but then suggests a similarly named formula called "fox". Weird.)

Anyway, if someone else wants to try migrating fox, here's a patch: [fox_diff.txt](https://github.com/Homebrew/homebrew-core/files/5531241/fox_diff.txt)

And the original linkage:
```
❯ brew linkage fox #before
System libraries:
  /opt/X11/lib/libGL.1.dylib
  /opt/X11/lib/libGLU.1.dylib
  /opt/X11/lib/libX11.6.dylib
  /opt/X11/lib/libXcursor.1.dylib
  /opt/X11/lib/libXext.6.dylib
  /opt/X11/lib/libXfixes.3.dylib
  /opt/X11/lib/libXft.2.dylib
  /opt/X11/lib/libXi.6.dylib
  /opt/X11/lib/libXrandr.2.dylib
  /opt/X11/lib/libXrender.1.dylib
  /usr/lib/libSystem.B.dylib
  /usr/lib/libbz2.1.0.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/fontconfig/lib/libfontconfig.1.dylib (fontconfig)
  /usr/local/Cellar/fox/1.6.56_1/lib/libFOX-1.6.0.dylib (fox)
  /usr/local/opt/freetype/lib/libfreetype.6.dylib (freetype)
  /usr/local/opt/jpeg/lib/libjpeg.9.dylib (jpeg)
  /usr/local/opt/libpng/lib/libpng16.16.dylib (libpng)
  /usr/local/opt/libtiff/lib/libtiff.5.dylib (libtiff)
```

**Comment by gromgit** [comment]
@carlocab, your patch is b0rked:
```
$ brew audit --strict --online fox
Error: fox: undefined method `on' for Formulary::FormulaNamespace5faef846cfba2b699fd0b4ba2c6a26ec::Fox:Class
```
which led me rather quickly to:
```
+  depends on "libxi"
```
Pretty sure that's supposed to be an underscore between `depends` and `on`, not a space.

**Comment by carlocab** [comment]
Yes, I figured I messed something up. :) Thanks for looking at it!

**Comment by carlocab** [comment]
On macOS:
```
❯ brew linkage robot-framework
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libffi.dylib
Homebrew libraries:
  /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib (openssl@1.1)
  /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib (openssl@1.1)
```

I'm guessing linkage needs to be checked on Linux, as in https://github.com/Homebrew/homebrew-core/pull/64584

I grepped the repo, though, and I couldn't find a reference to X11.

**Comment by carlocab** [comment]
The fmsx license (found [here](http://fms.komkon.org/fMSX/fMSX.html#LABC)) doesn't appear to be Homebrew-compatible:
>fMSX source code is open for everyone to see but it is not in public domain. You can look and learn from it, but you cannot change it or copy it without giving a credit to the original author and a few other conditions. If you would like to port fMSX to another platform or make changes to the code, please, contact me by email or some other means.
>
>You cannot use fMSX source code for commercial purposes unless you contact me to arrange the conditions of such usage. If your company intends to use MSX software in its products and you are considering using fMSX source code, please, email me about licensing.

At the very least, this seems similar to the case of pgplot: https://github.com/Homebrew/homebrew-core/pull/64332

**Comment by jonchang** [comment]
This is now complete! Thanks to @gromgit, @issyl0, @SeekingMeaning, @yurikoles, and new contributor @carlocab for helping with migrations, @fxcoudert and @SMillerDev for reviewing pull requests, and @iMichka and @maxim-belkin for maintaining and migrating the X formula to homebrew/core from linuxbrew/xorg!

:tada: :partying_face:

**Comment by iMichka** [comment]
Amazing. Who would have thought we would achieve this one day :)

**Comment by SMillerDev** [comment]
I wouldn't have expected it last month.
