### ISSUE TITLE
Rust-dependent formulae on Apple Silicon - upstream issue tracker

### ISSUE THREAD

**Issue by carlocab** [Homebrew/homebrew-core#68301]
There are a number of formulae that are not building with Rust 1.49 on Apple Silicon because of stale `Cargo.lock` files. (Cf. https://github.com/Homebrew/homebrew-core/pull/68089) Only upstream can update this, so we need to open issues upstream asking them for an updated lock file.

<details><summary>Why is this needed?</summary>
<p>

We need the `Cargo.lock` files to updated because our `cargo` builds use the `--locked` flag, and these builds will fail when the lock file is stale. Removing the `--locked` flag isn't an option, because:
1. We don't like unversioned dependencies. [[1](https://docs.brew.sh/Acceptable-Formulae#we-dont-like-install-scripts-that-download-unversioned-things)]
2. We like reproducible builds.
3. Builds with unpinned dependencies are prone to breakage when their dependencies upgrade to an incompatible version.

For more context, see: https://github.com/Homebrew/homebrew-core/issues/46025, https://github.com/Homebrew/brew/pull/10205

</p>
</details>

For each formula listed below:
1. File an upstream issue for the relevant formula regarding the stale `Cargo.lock` file. If they're willing to cut a new release to update their lock file, that would be helpful.
2. Link upstream issues here so we can track them.
3. When upstream updates their lock file, open a PR here in homebrew/core to update the relevant formula.
    - If they cut a new release with the updated lock file, this PR will just be a simple version bump.
    - If they don't, then the formula will need to be patched. Please include a comment before your patch with details on when the patch can be removed. (e.g. a commit to track, an upstream issue, etc.) 

If you want to help, feel free to do the above steps for any formula below that doesn't have an upstream issue filed yet.

- [x] angle-grinder -- https://github.com/rcoh/angle-grinder/issues/130, #68729
- [x] asuka
- [x] badtouch -- https://github.com/kpcyrd/badtouch/issues/76, #68806, #69022
- [x] bandwhich -- https://github.com/imsnif/bandwhich/issues/207
- [x] bingrep -- https://github.com/m4b/bingrep/issues/29, #68743
- [x] boringtun
- [x] click
- [x] dog
- [x] dssim
- [x] exa -- https://github.com/ogham/exa/issues/785, #68973
- [x] fblog
- [x] ffsend
- [x] fnm
- [x] git-delta -- https://github.com/dandavison/delta/issues/487, #68333
- [x] git-interactive-rebase-tool
- [x] git-trim
- [x] gleam -- https://github.com/gleam-lang/gleam/issues/920, #68957
- [x] grin
- [x] grin-wallet -- #69197, blocked by dependencies
- [x] ktmpl
- [x] kubie -- #68792, retry when `kubernetes-cli` has an ARM bottle
- [x] meilisearch -- #68788
- [x] rbspy -- https://github.com/rbspy/rbspy/issues/303, #74649
- [x] ripgrep-all -- https://github.com/phiresky/ripgrep-all/issues/96
- [x] rm-improved
- [x] rustscan -- #100255
- [x] saltwater -- #81256
- [x] shadowenv
- [x] silicon
- [x] sonic
- [x] ssh-permit-a38
- [x] texlab -- https://github.com/latex-lsp/texlab/issues/343, #68708
- [x] tree-sitter -- #68723
- [x] volta -- https://github.com/volta-cli/volta/issues/977, https://github.com/Homebrew/homebrew-core/commit/11e6a368c1f9fb260c7152996ce0cb154d92c495
- [x] wagyu
- [x] wapm
- [x] wasm-pack -- https://github.com/rustwasm/wasm-pack/issues/959, #68836
- [x] wasmer -- https://github.com/wasmerio/wasmer/issues/1986, #68603
- [x] zenith -- https://github.com/bvaisvil/zenith/issues/92, #68811
- [x] zola -- #68616

**Comment by ioan555** [comment]
Ок

**Comment by richiksc** [comment]
Is there a tracking issue for `ripgrep-all`? Looks like the CI build failure is the same issue as `texlab` was: an outdated version of the `cc` crate in a dependency, `lmdb-rkv-sys`:

```
The following warnings were emitted during compilation:

warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch
warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch

error: failed to run custom build command for `lmdb-rkv-sys v0.11.0`

Caused by:
  process didn't exit successfully: `/private/tmp/ripgrep-all-20210108-20170-1y2jt66/ripgrep-all-0.9.6/target/release/build/lmdb-rkv-sys-664251cca3dc46db/build-script-build` (exit code: 1)
```

So that would need to be updated, a new version released, and then ripgrep itself would need to be updated.

**Comment by carlocab** [comment]
It's listed above, but no issue has yet to be linked, so feel free to open an issue with them about the problem. Link the issue you open back here so I can update the list.

**Comment by richiksc** [comment]
@carlocab Done: https://github.com/phiresky/ripgrep-all/issues/96.

**Comment by richiksc** [comment]
@carlocab New tracking issue for `wasm-pack`: https://github.com/rustwasm/wasm-pack/issues/959

`master`@`HEAD` builds succesfully with `--locked` on my local M1 Mac.

**Comment by richiksc** [comment]
`boringtun` builds succesfully with `--locked` on `HEAD`. However, running `boringtun utun` (the test command) fails.

**Comment by carlocab** [comment]
That sounds like it needs a separate bug report. Do you mind opening one, @richiksc?

**Comment by richiksc** [comment]
Looks like I just needed to run with `sudo`. `boringtun` will be ARM-compatible on the next release, since it works on `master`.

**Comment by carlocab** [comment]
Might still be a problem, though, as I'm not sure we can use `sudo` in a test block. We'll have to figure out a way around that at some point.

**Comment by SMillerDev** [comment]
We don't use sudo anywhere in brew, so that's not a good solution. Can't we check for an expected error instead?

**Comment by aaomidi** [comment]
kubernetes-cli now has an m1 build: https://github.com/kubernetes/kubernetes/issues/97550

**Comment by smartin** [comment]
Having trouble completing `brew install mycli` and not sure how to contribute to this issue. Thanks for any help and comments. Here is the result of my `RUST_BACKTRACE` 

Traceback (most recent call last):
	26: from /usr/local/Homebrew/Library/Homebrew/build.rb:227:in `<main>'
	25: from /usr/local/Homebrew/Library/Homebrew/build.rb:134:in `install'
	24: from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	23: from /usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block in install'
	22: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1216:in `brew'
	21: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2241:in `stage'
	20: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	19: from /usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
	18: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	17: from /usr/local/Homebrew/Library/Homebrew/resource.rb:198:in `mktemp'
	16: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	15: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	14: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	13: from /usr/local/Homebrew/Library/Homebrew/resource.rb:117:in `block in unpack'
	12: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:87:in `stage'
	11: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:100:in `chdir'
	10: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:100:in `chdir'
	 9: from /usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block (2 levels) in unpack'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2261:in `block in stage'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2262:in `block (2 levels) in stage'
	 5: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1223:in `block in brew'
	 4: from /usr/local/Homebrew/Library/Homebrew/build.rb:175:in `block (2 levels) in install'
	 3: from /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rust.rb:88:in `install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2048:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2048:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2112:in `block in system': Failed executing: make (BuildError)
	9: from /usr/local/Homebrew/Library/Homebrew/brew.rb:155:in `<main>'
	8: from /usr/local/Homebrew/Library/Homebrew/brew.rb:167:in `rescue in <main>'
	7: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:494:in `dump'
	6: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:440:in `issues'
	5: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:444:in `fetch_issues'
	4: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:67:in `issues_for_formula'
	3: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:36:in `search_issues'
	2: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:165:in `search'
	1: from /usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:237:in `open_rest'
/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:307:in `raise_error': curl failed!   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current (GitHub::API::Error)
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: api.github.com

**Comment by carlocab** [comment]
Looks like a network problem, and isn't related to this issue. Please check your connection (e.g. if you have something like Little Snitch, please deactivate it) and try again.

If that doesn't help, you can ask for help at https://github.com/Homebrew/discussions/discussions.

**Comment by cprecioso** [comment]
`volta` has an open issue on volta-cli/volta#977. However it is not clear if any action is needed as it already works well when using `--build-from-source`. Can we enable bottles for it now?

**Comment by nandahkrishna** [comment]
@cprecioso `volta` has been bottled for ARM in https://github.com/Homebrew/homebrew-core/commit/11e6a368c1f9fb260c7152996ce0cb154d92c495, thanks.

**Comment by cho-m** [comment]
Updated list. Only `rustscan` is not bottled on Apple Silicon. There are at least 3 different PRs related to this upstream:
- https://github.com/RustScan/RustScan/pull/404
- https://github.com/RustScan/RustScan/pull/430
- https://github.com/RustScan/RustScan/pull/431

**Comment by amadejpapez** [comment]
New RustScan release [2.1.0](https://github.com/RustScan/RustScan/releases/tag/2.1.0) has just been made!

**Comment by cho-m** [comment]
Closing as all tasks are done.
