### ISSUE TITLE
cffi updates for Apple Silicon

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#68463]
Following-up on this PR https://github.com/Homebrew/homebrew-core/pull/68454
This is the list of python-based formulas that have an outdated cffi resource block, that cannot build on Apple Silicon. Updating to cffi-1.14.4 should allow most of these formulas to build!

- [x] `ansible-lint` #68624
- [ ] `ansible@2.8`
- [ ] `appscale-tools`
- [x] `aws-elasticbeanstalk` #68534
- [ ] `aws-google-auth`
- [x] `awscurl` #68533
- [ ] `charm-tools` #68532
- [ ] `conjure-up` #68531
- [x] `credstash` #68530
- [x] `docker-compose` #68454
- [x] `dxpy` #68525
- [x] `fdroidserver` #68524
- [x] `flintrock` #68522
- [x] `gimme-aws-creds` #68520
- [x] `gitfs` #68519 - depends on `fuse`
- [x] `gitless` #68518
- [x] `jupyterlab` [bottle request](https://github.com/Homebrew/homebrew-core/runs/1664942103?check_suite_focus=true) - blocked by `ghc` and friends
- [x] `literate-git` #68508
- [x] `magic-wormhole` #68479
- [x] `mycli` #68480
- [x] `nbdime` #68507
- [x] `ooniprobe` #68506 - deprecated
- [x] `openstackclient` #68492
- [x] `robot-framework` #68493
- [x] `s3ql` #68491 - depends on `fuse`
- [ ] `salt` #68490
- [x] `snapcraft` #68488
- [ ] `sslyze` #68487
- [x] `statik` #68486
- [x] `stormssh` #68484
- [x] `svtplay-dl` #68483
- [x] `theharvester` #68475
- [x] `vsts-cli` deprecated
- [x] `ykman` #68473

**Comment by carlocab** [comment]
`jupyterlab` already uses latest `cffi`. It's currently blocked by `ghc` and friends.

**Comment by fxcoudert** [comment]
@carlocab you rock!

**Comment by fxcoudert** [comment]
Closing now, thanks @carlocab for your work on this!

**Comment by carlocab** [comment]
I take payment in /sparkles
