### ISSUE TITLE
Unbottled Formulae on Monterey (Intel and ARM)

### ISSUE THREAD

**Issue by carlocab** [Homebrew/homebrew-core#94212]
Update from @danielnachun:
This is a final list of the formulae which remain unbottled on both Intel and ARM Monterey which are not deprecated, disabled, `:all`, or versioned formulae.

## Build failure
- [x] apollo-cli - `Error: Cannot find module 'graphql/validation/rules/KnownArgumentNamesRule'` - #116372
- [x] bluepill - `ld: framework not found DVTiPhoneSimulatorRemoteClient` - #111554
- [x] cadaver - `configure: incompatible neon library version 0.32.2: wanted 0.27 28 29 30 31` - #106403
- [x] chisel - `error: The Legacy Build System will be removed in a future release. You can configure the selected build system and this deprecation message in File > Project Settings.` #114379
- [x] drafter - `version` issue - happens in vendored copy of `boost`, and does not seem to allow use of system `boost` - #115518
- [x] hyperkit - `src/lib/block_if.c:141:1: error: static declaration of 'preadv' follows non-static declaration` - tries to build `xhyve` and fails in the same way. - #113251
- [x] idris2 - `Exception: (while loading libidris2_support.dylib) dlopen(libidris2_support.dylib, 0x0002): tried: 'libidris2_support.dylib' (no such file), '/usr/local/lib/libidris2_support.dylib' (no such file), '/usr/lib/libidris2_support.dylib' (no such file), '/private/tmp/idris2-20220531-53452-um0fim/Idris2-0.5.1/libs/prelude/libidris2_support.dylib' (no such file)` #112065
- [x] mcrypt - `checking for libmcrypt - version >= 2.5.0... configure: error: *** libmcrypt was not found` - this fails because the conftest binary segfaults. #114108
- [x] needle - `/private/tmp/needle-20220620-21368-lz0p9j/Generator/.build/checkouts/swift-syntax/Sources/SwiftSyntax/RawSyntax.swift:120:46: error: value of type 'CSyntaxNode' (aka 'swiftparse_syntax_node_t') has no member 'range'` - #109474
- [x] pgloader - `Fatal COMPILE-FILE-ERROR: COMPILE-FILE-ERROR while compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "opt" "sbcl" "x86oid-vm">` - #104688
- [x] platypus - build seems to hang indefinitely: https://github.com/sveinbjornt/Platypus/issues/240, #109580
- [x] psc-package - `Couldn't match type ‘Text’ with ‘Data.Aeson.Key.Key’ Expected type: PackageName -> Data.Aeson.Key.Key Actual type: PackageName -> Text`
- [x] winexe - `./configure: line 4695: syntax error near unexpected token 'fi'` - same failure as linux, also unbottled on Big Sur. -- #106626
- [x] xhyve - `src/block_if.c:125:1: error: static declaration of 'preadv' follows non-static declaration` - actively developed but hasn't produced a tagged release since 2015 #114741
- [x] xcprojectlint - `/private/tmp/xcprojectlint-20220604-76893-1xewum3/.build/checkouts/swift-package-manager/Sources/Basic/Await.swift:18:28: error: value of type '(@escaping (Result<T, ErrorType>) -> Void) -> Void' has no member 'dematerialize'` https://github.com/americanexpress/xcprojectlint/issues/37
## Test failure
- [x] compface - test hangs? #117174
- [x] tcc - `tcc: error: library 'c' not found` - #115368
- [x] mdxmini - `dyld[55857]: symbol not found in flat namespace '_SDL_CloseAudio'` - #106627
- [x] libtecla - `dyld[67203]: symbol not found in flat namespace '_setupterm'` - happens even after flat namespace usage is fixed
- [x] metaproxy - `dyld[52753]: symbol not found in flat namespace '__ZN5boost24scoped_static_mutex_lockC1ERNS_12static_mutexEb'` - #106435
## Unbottled dependencies
- [x] insect - `psc-package`
- [x] rdup - `mcrypt` #114108
- [x] sollya - `mpfi` (deprecated)
## Miscellaneous
- [x] gitslave - should maybe be `:all`?
- [x] mecab-unidic-extended - should maybe be `:all`?
- [x] montage - `Warning: Could not fix /private/tmp/montage-20220604-20194-e9zklg/montage/lib/src/freetype-2.5.4/../../freetype/lib/libfreetype.6.dylib in /usr/local/Cellar/montage/4.0/bin/mHistogram` - this causes an audit failure due to broken dynamic library links - #109834 
- [x] moz-git-tools - should maybe be `:all`? - https://github.com/Homebrew/homebrew-core/pull/105534
- [x] viewvc - Python 2 - #114121, https://github.com/Homebrew/homebrew-core/issues/93940
- [x] sersniff - head URL now returns `Forbidden`, but homepage and source URL still work. - #106423
- [x] tarsnap-gui - needs to make a new tagged release with build fixes - unbottled on Big Sur, may be time to deprecate - #106421

------
Below is a list of the most-installed formulae (ranked according to install events in the last 90 days) that have no bottles on Monterey (both Intel and ARM).

We should try to get these bottled where we can. Some of these still have no Big Sur bottles -- if they don't, this should be reported upstream for assistance.

A number of these will have no bottles because they have unbottled dependencies. You can check with:
```
brew unbottled --tag=monterey octave
brew unbottled --tag=arm64_monterey octave
```

<details><summary>Both Intel and ARM</summary>
<p>

```
Formula                      Install Events (90d)
hyperkit                     18752
mcrypt                       8283
elasticsearch                6658
logstash                     1803
docker-machine-driver-xhyve  1624
truncate                     1241
ipmitool                     1233
pgloader                     1183
winexe                       1104
percona-toolkit              976
grace                        860
ddcctl                       856
infer                        853
xhyve                        823
mermaid-cli                  790
bluetoothconnector           704
libbs2b                      676
mlt                          654
hbase                        645
volatility                   643
libstfl                      638
rtorrent                     632
gsmartcontrol                617
chisel                       599
freeradius-server            562
pdf2htmlex                   549
multitail                    548
lilypond                     537
apollo-cli                   492
fakeroot                     489
httping                      487
glade                        483
audacious                    464
buildapp                     455
pdflib-lite                  440
ical-buddy                   437
gdcm                         428
ki                           408
easy-tag                     404
pgrouting                    398
gwyddion                     374
allegro                      373
questdb                      366
xctool                       348
modd                         328
suricata                     302
kamel                        300
idris2                       298
clair                        297
ecl                          296
termshark                    285
libfaketime                  278
rakudo-star                  257
tnftpd                       246
libdv                        246
nedit                        241
needle                       234
mpfi                         234
purescript                   231
subliminal                   229
clojure-lsp                  225
moc                          224
platypus                     222
subversion@1.8               200
latexml                      191
ddd                          186
balena-cli                   182
mysql++                      180
kotlin-language-server       177
mytop                        176
sonarqube-lts                171
cadaver                      162
singular                     160
gmt@5                        160
dynare                       157
paperkey                     156
insect                       146
osm2pgrouting                144
apache-archiva               143
xsane                        140
sf-pwgen                     136
itk                          136
pig                          134
pth                          133
innotop                      129
afsctool                     125
alot                         117
synfig                       116
jumanpp                      115
tcc                          113
lesstif                      112
vera++                       104
i2p                          102
openmodelica                 100
libzdb                       95
gtranslator                  93
druid                        90
virtualpg                    89
lanraragi                    88
carla                        82
healpix                      81
ocp                          80
dsh                          80
mmseqs2                      78
itpp                         78
eiffelstudio                 77
bluepill                     76
libdshconfig                 74
alluxio                      74
pulp                         70
mesos                        69
makepkg                      69
beast                        68
gabedit                      66
nvi                          65
juman                        63
json-fortran                 62
ringojs                      60
xcprojectlint                59
montage                      59
manticoresearch              59
ivtools                      59
inlets                       58
klee                         57
envoy@1.18                   56
qt-percona-server            55
pev                          55
inspectrum                   55
hatari                       55
libiptcdata                  54
drafter                      54
ompl                         52
nailgun                      52
gjs                          52
coreos-ct                    51
libtensorflow@1              50
e2tools                      50
libtecla                     48
pkcrack                      45
extract_url                  45
pushpin                      43
compface                     43
acl2                         43
minuit2                      40
aida-header                  39
xsd                          38
soci                         38
lightning                    38
stellar-core                 37
cassandra@2.1                37
bareos-client                37
ht                           36
libglademm                   35
aterm                        33
libmusicbrainz               32
plowshare                    30
gnuplot@4                    30
geomview                     30
ship                         29
libopennet                   29
cstore_fdw                   28
pcb                          27
libetonyek                   27
jing-trang                   27
flowgrind                    27
rsstail                      25
gssh                         25
qmmp                         24
trafficserver                23
pike                         23
libmrss                      23
huexpress                    23
flactag                      23
falcon                       23
rex                          22
ngircd                       22
libxdiff                     22
libgtop                      21
garmintools                  21
corectl                      20
classads                     20
cmusfm                       19
adplug                       19
voro++                       18
yamdi                        17
rlog                         17
libident                     17
docker2aci                   17
braid                        17
opentsdb                     15
metaproxy                    15
harbour                      15
vrpn                         14
tpp                          14
scrollkeeper                 14
liquigraph                   14
ibex                         14
flac123                      14
omega                        13
mikutter                     13
echoprint-codegen            13
c10t                         13
xlispstat                    12
sdf                          12
nmh                          12
ganglia                      12
ekhtml                       12
clipsafe                     12
yamcha                       11
xshogi                       10
xlslib                       10
sec                          10
psc-package                  10
glulxe                       10
ekg2                         10
tarsnap-gui                  9
mruby-cli                    9
libgetdata                   9
genstats                     9
eventql                      9
wv2                          8
udis86                       8
texapp                       8
solid                        8
pgdbf                        8
libodfgen                    8
git-remote-hg                8
gel                          8
couchdb-lucene               8
bas55                        8
ogmtools                     7
objfw                        7
mecab-unidic-extended        7
lib3ds                       7
fbi-servefiles               7
dbxml                        7
cubelib                      7
appscale-tools               7
```

</p>
</details>

**Comment by carlocab** [comment]
These formulae are missing only ARM bottles on Monterey:

<details><summary>ARM only</summary>
<p>

```
Formula             Install Events (90d)
openjdk@8           48311
gdb                 38948
upx                 19486
mono                19335
node@10             12189
v8@3.15             6202
mysql@5.6           6110
mplayer             2146
luajit              2118
git-annex           1837
volk                1411
sysdig              1282
homebank            1123
chezscheme          1028
mit-scheme          1021
akamai              980
rethinkdb           893
minetest            884
mps-youtube         734
redis@4.0           601
dcmtk               594
sslyze              588
rdesktop            581
blast               572
librealsense        543
sratoolkit          536
rustscan            455
redis@3.2           448
babl                426
pympress            414
scummvm             384
openttd             361
hmmer               354
bwa                 354
joplin-cli          323
gtkspell3           321
unicorn             314
acpica              275
ace                 269
appstream-glib      262
gnu-smalltalk       255
kibana@6            247
gdbgui              245
sqliteodbc          241
kite                237
scriptcs            235
ipmiutil            228
lepton              209
systemc             206
gexiv2              203
gegl                198
cryptol             179
cquery              176
ginac               167
datalad             164
renameutils         162
librest             161
afl-fuzz            159
geocode-glib        153
ghc@9               149
mlton               147
clozure-cl          138
bigloo              138
cp2k                134
minizinc            130
gnome-recipes       124
hashlink            114
dar                 112
spades              104
nwchem              104
pjproject           97
io                  91
stella              89
mlkit               89
osm-gps-map         88
geogram             88
cucumber-ruby       86
cln                 85
dc3dd               83
fq                  82
rig                 75
hsd                 75
sigrok-cli          74
odin                74
efl                 71
raxml-ng            67
dvm                 67
box2d               66
luvit               65
julius              65
tracker             57
streamripper        52
openslp             48
nacl                48
mupen64plus         48
libgweather         48
openfast            47
libchamplain        47
grin-wallet         45
wput                44
libdbi              41
mercury             40
b2sum               40
jpeg-archive        39
speech-tools        38
abricate            37
xlearn              35
boringtun           35
cf-tool             33
blastem             33
valabind            32
agedu               32
nu                  31
mvtools             30
redex               29
picat               29
libpcl              29
cpu_features        29
blaze               29
clucene             27
ssdb                25
luaradio            25
tidyp               24
libcpuid            23
zydis               22
sdlpop              22
mongrel2            22
chakra              22
xplanet             20
biosig              20
awsweeper           20
teleconsole         19
snap7               19
rp                  17
lincity-ng          16
cmix                16
virgil              13
lcdproc             13
hyperestraier       13
libsquish           12
sgrep               11
s2geometry          11
mplayershell        11
fibjs               11
sagittarius-scheme  10
intercal            10
dnscrypt-wrapper    10
bde                 10
libsmf              9
gpsim               9
dgen                8
ctail               8
bic                 7
```

</p>
</details>

**Comment by carlocab** [comment]
These formulae are missing only Intel bottles on Monterey:

<details><summary>Intel only</summary>
<p>

```
Formula              Install Events (90d)
qt@5                 127482
pyqt@5               59848
gdal                 53344
vtk                  43272
poppler-qt5          41625
gnuplot              34031
postgis              17746
pinentry-mac         14921
qscintilla2          12317
qcachegrind          6375
dotnet               4697
gcc@9                3717
pcl                  2450
qwt-qt5              2318
xpdf                 2140
go@1.15              1990
gcc@10               1942
terraform@0.13       1670
git-cola             1533
gcc@8                1474
gcc@7                1466
minimal-racket       1397
gcc@6                1332
extra-cmake-modules  1248
go@1.13              1128
go@1.14              1101
vtk@8.2              920
arangodb             891
pyside@2             701
neovim-qt            658
libqalculate         652
truffle              651
karchive             650
swagger-codegen@2    619
ansible@2.8          593
gitversion           575
ki18n                516
nexus                499
qca                  360
matplotplusplus      342
openalpr             339
fceux                301
cassandra@3          301
threadweaver         295
qtkeychain           280
quazip               268
pdal                 267
siril                246
coin3d               224
gecode               194
mgba                 191
gwenhywfar           185
tsung                182
djview4              176
signal-cli           174
dafny                159
dspdfviewer          154
aqbanking            154
qcli                 138
visp                 137
elm-format           122
feedgnuplot          116
libgr                110
gammaray             108
suil                 107
qbs                  95
apache-pulsar        93
urh                  89
pc6001vx             83
libreadline-java     81
gradio               80
cassandra@2.2        76
qjson                63
opencsg              59
trimage              52
zurl                 50
qsoas                42
codequery            37
color-code           29
archi-steam-farm     26
gosu                 25
qtads                21
drake                20
icemon               16
neopop-sdl           14
hexgui               13
qxmpp                12
jmxtrans             9
```

</p>
</details>

**Comment by luca-drf** [comment]
Not sure if this is the right place for this (if it isn't, I'm sorry, please point me to the right place) but I've noticed that macvim 8.2-172 Monterey x86_64 bottle (`sha256:82b452d795bab0b1771eab28210e4a342b723724d3a90ed54f411e948cf26e37`) seems to have a build bug where `LSMinimumSystemVersion` is set to `12.2` (instead of `12.1`) resulting in the system refusing to start the app. The program actually works fine when launched from command line with `mvim`.

Brew info:
```
macvim: stable 8.2-172 (bottled), HEAD
GUI for vim, made for macOS
https://github.com/macvim-dev/macvim
Conflicts with:
  vim (because vim and macvim both install vi* binaries)
/usr/local/Cellar/macvim/8.2-172 (2,314 files, 43.8MB) *
  Poured from bottle on 2022-02-08 at 15:43:38
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/macvim.rb
```

Brew config:
```
HOMEBREW_VERSION: 3.3.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8a787e45ff45583fb245030757296548f82c1cbd
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0899794b825ce71cfe9869e2428ea0c7b3a1958c
Core tap last commit: 66 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.2jhModqlWg/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.35.1 => /usr/local/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
```
Building locally worked fine for me (`brew install --build-from-source macvim`)

Many thanks!

**Comment by SMillerDev** [comment]
That seems pretty normal, since 12.2 is the most recent Monterey version. You should update your OS.

**Comment by luca-drf** [comment]
> That seems pretty normal, since 12.2 is the most recent Monterey version. You should update your OS.

Is there any particular reason why that bottle shouldn't work on 12.1 and the minumum revision was set to 12.2 a part from "12.2 is the most recent Monterey version"?

**Comment by SMillerDev** [comment]
We always build against the newest possible dependencies. That means we'll keep our build OS up to date as well. If a build hardcodes an minimal OS version somewhere that means you'll have to keep your OS up to date to keep up with brew.

It might also just be a bug in the build script for macvim that it requires a minor version match on macOS 11+. Either way, brew did exactly what it's been doing since forever here.

**Comment by danielnachun** [comment]
I think we can update  these lists now because we've bottled `qt@5` for Intel Monterey and that was the main reason some bottles were missing for Intel Monterey but not ARM.

I can also see that a decent number of formulae missing bottles only on ARM are blocked by `openjdk@8`, which Azul has successfully built for ARM on macOS: https://www.azul.com/downloads/?package=jdk.  I don't know if they'd be willing to help us fix our build but it might be worth reaching out.

I can also see some other formulae missing ARM bottles which are deprecated or should be deprecated because they are unmaintained.

It's also worth mentioning that the biggest blocker by far for Monterey bottling across both architectures is `openjdk@11`, which we haven't updated yet because the patch for ARM support is a lot of work to update.  Once that is merged we'll be able to make a lot more progress on Monterey bottling in general.

**Comment by Bo98** [comment]
> can also see that a decent number of formulae missing bottles only on ARM are blocked by `openjdk@8`, which Azul has successfully built for ARM on macOS: https://www.azul.com/downloads/?package=jdk. I don't know if they'd be willing to help us fix our build but it might be worth reaching out.

We're approaching the point where I'd like to see OpenJDK 8 phased out. The amount of patches that would have to be backported for arm64 macOS is likely large - it already is for OpenJDK 11 and has shown to be a maintenance burden.

This is also not Monterey specific anyway.

**Comment by danielnachun** [comment]
That's a very fair point.  I did a cursory check of the dependents of `openjdk@8`, and of those which are not already deprecated or disabled, all but a handful appear to be unmaintained.  We should probably start deprecating all `openjdk@8` dependents unless they are actively maintained and there is a clear upstream plan to migrate at least to `openjdk@11`.

**Comment by MikeMcQuaid** [comment]
> We're approaching the point where I'd like to see OpenJDK 8 phased out as a dependency. The amount of patches that would have to be backported for arm64 macOS is likely large - it already is for OpenJDK 11 and has shown to be a maintenance burden.

Seems reasonable to me 👍🏻

**Comment by YinianFan** [comment]
Not sure if this is the right place for this (if it isn't, I'm sorry, please point me to the right place).
I got problem with installing redis@3.2 on arm64 Monterey as there is no bottle available. Then I tried to manually install redis 3.2 but failed to make on arm64 OS Monterey. Don't know how to install redis 3.2 on my mac with OS Monterey.

**Comment by danielnachun** [comment]
I'll start working on a "deprecate or update formulae that depend on `openjdk@8`" issue like I did for Python 2, which was quite successful.

**Comment by danielnachun** [comment]
I think we should also give serious consideration to deprecating or updating formulae that depend on `gtk+` (GTK2).  GTK2 is EOL as of the release of GTK4: https://blog.gtk.org/2020/12/16/gtk-4-0/.  The `gtkglext` formula is unbottled on Linux because `pangox` doesn't work with the X/OpenGL stack, and is heavily patched on macOS (it is unbottled on Monterey due to a `flat_namespace` audit failure).  

A number of formulae that currently depend on `gtk+` actually support GTK3 or even GTK4 and should be migrated.  Those which do not support a newer GTK version should either have the GUI disabled if it is optional or be deprecated.  I can make another tracking issue for this as well if desired.

**Comment by cho-m** [comment]
> It's also worth mentioning that the biggest blocker by far for Monterey bottling across both architectures is `openjdk@11`, which we haven't updated yet because the patch for ARM support is a lot of work to update. Once that is merged we'll be able to make a lot more progress on Monterey bottling in general.

`openjdk@11` has backported ARM patch into development branch for upcoming 11.0.15. I've switched PR #87638 to use that version (`11.0.15+5`) for ARM  and it successfully builds/tests.

**Comment by Bo98** [comment]
> I think we should also give serious consideration to deprecating or updating formulae that depend on `gtk+` (GTK2). GTK2 is EOL as of the release of GTK4: https://blog.gtk.org/2020/12/16/gtk-4-0/. The `gtkglext` formula is unbottled on Linux because `pangox` doesn't work with the X/OpenGL stack, and is heavily patched on macOS (it is unbottled on Monterey due to a `flat_namespace` audit failure).
> 
> A number of formulae that currently depend on `gtk+` actually support GTK3 or even GTK4 and should be migrated. Those which do not support a newer GTK version should either have the GUI disabled if it is optional or be deprecated. I can make another tracking issue for this as well if desired.

In general yes: dependents of EOL/deprecated formulae should be migrated or deprecated too if there's no upstream activity. This also applies to PCRE1, but that's an example of something that can't really be rushed - I expect migration of dependents for that will not be completed this year.

For SDL 1.2, we have a migration path of `sdl12_compat` - though ideally we'd wait for a bug fix release or two first since that compat layer is very new.

**Comment by mhmdanas** [comment]
Note that `insect` does not depend on `psc-package` anymore, see https://github.com/Homebrew/homebrew-core/pull/106311.

**Comment by Bo98** [comment]
I strongly encourage deprecating `mcrypt`. It's abandonware security software, which is a very good reason for deprecation.

Unfortunately, rdup is still using it...

**Comment by SMillerDev** [comment]
Rdup has 0 installs the last month, let's just deprecate that too. Last release was 6,5 years ago

**Comment by iMichka** [comment]
`rdup` and `mcrypt`: #174544
